Repository swiftlang/swift-package-manager, pull requests merged in 2018-08, with the labels that each got.

#1724 [swift test] Add an "autogenerated" notice to test manifests.
  Sources/Commands/GenerateLinuxMain.swift
  Tests/FunctionalTests/MiscellaneousTests.swift
Labels: ready

#1736 [SRC-8327] Adding error messages if ninja and cmake aren't installed
  Utilities/bootstrap
Labels: wip

#1741 Print missing verbose command description on -v
  Sources/Build/BuildDelegate.swift
  Sources/Commands/SwiftTool.swift
Labels: awaiting review

#1726 OutputByteStream overloads refactoring
  Sources/Basic/OutputByteStream.swift
  Tests/BasicPerformanceTests/OutputByteStreamPerfTests.swift
  Tests/BasicTests/OutputByteStreamTests.swift
Labels: awaiting review

#1751 Allow to create child processes in the same process group
  Sources/Basic/Process.swift
Labels: wip

#1742 Add basic support for Windows targets
  Sources/Build/BuildPlan.swift
  Sources/Build/Triple.swift
  Tests/BuildTests/BuildPlanTests.swift
  Tests/BuildTests/XCTestManifests.swift
Labels: wip
