Repository swiftlang/swift-package-manager, pull requests merged in 2018-09, with the labels that each got.

#1770 Allow a custom env for more `xcrun` invocations
  Sources/Workspace/UserToolchain.swift
Labels: awaiting review

#1771 Improve handling of "extra" files
  Sources/Commands/SwiftPackageTool.swift
  Sources/Xcodeproj/generate().swift
  Sources/Xcodeproj/pbxproj().swift
  Tests/XcodeprojTests/GenerateXcodeprojTests.swift
Labels: awaiting review

#1749 Process streams stdout/stderr through OutputClosure-s
  Sources/Basic/Process.swift
  Sources/Commands/SwiftTestTool.swift
  Sources/Commands/SwiftTool.swift
  Sources/Utility/Process.swift
Labels: ready

#1780 Throwing errors instead of calling fatalError
  Sources/SourceControl/GitRepository.swift
Labels: ready

#1762 [Commands] Fix force unwrap
  Sources/Commands/SwiftTool.swift
Labels: ready

#1725 Thread-safe Output Byte Stream
  Sources/Basic/OutputByteStream.swift
  Sources/Basic/TerminalController.swift
  Sources/Build/BuildDelegate.swift
  Sources/Build/BuildPlan.swift
  Sources/Commands/Error.swift
  Sources/Commands/SwiftTool.swift
  Sources/Utility/ProgressBar.swift
  Tests/BasicTests/OutputByteStreamTests.swift
Labels: awaiting review

#1779 Support tilde expansion for local dependencies on DescriptionV4_2
  Sources/Basic/FileSystem.swift
  Sources/PackageLoading/ManifestLoader.swift
  Sources/PackageLoading/PackageDescription4Loader.swift
  Sources/SourceControl/GitRepository.swift
  Sources/SourceControl/InMemoryGitRepository.swift
  Tests/PackageLoadingTests/PD4_2LoadingTests.swift
Labels: wip
