Repository swiftlang/swift-package-manager, pull requests merged in 2021-09, with the labels that each got.

#3699 refactor managed artifacts
  Sources/SPMTestSupport/MockWorkspace.swift
  Sources/Workspace/ManagedArtifact.swift
  Sources/Workspace/Workspace.swift
  Sources/Workspace/WorkspaceState.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: ready

#3671 Update registry specification to include publishing endpoint
  Documentation/Registry.md
Labels: ready

#3688 Print reason for requiring resolution in verbose mode
  Sources/Commands/SwiftTool.swift
  Sources/Workspace/Workspace.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: ready

#3711 fix potential race in the computation of cache state
  Sources/SourceControl/RepositoryManager.swift
Labels: ready

#3713 relax stricter validation to warning to allow transition
  Sources/PackageGraph/PackageGraph+Loading.swift
  Sources/PackageModel/Manifest.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: ready

#3714 add more tests for additional dependency uniqueness validation
  Sources/PackageGraph/Pubgrub/PubgrubDependencyResolver.swift
  Sources/SPMTestSupport/InMemoryGitRepository.swift
  Sources/SPMTestSupport/MockDependency.swift
  Sources/SPMTestSupport/MockPackage.swift
  Sources/SPMTestSupport/MockWorkspace.swift
  Sources/SPMTestSupport/PackageDependencyDescriptionExtensions.swift
  Tests/CommandsTests/PackageToolTests.swift
  Tests/PackageGraphTests/PackageGraphTests.swift
  Tests/PackageLoadingTests/PackageBuilderTests.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
  Tests/XcodeprojTests/GenerateXcodeprojTests.swift
Labels: ready

#3719 rename resolveToResolvedVersion to resolveBasedOnResolvedVersionsFile
  Sources/Commands/SwiftTool.swift
  Sources/SPMTestSupport/MockWorkspace.swift
  Sources/Workspace/Workspace.swift
Labels: ready

#3720 improve manifest loading diagnostics handling
  Sources/Workspace/Workspace.swift
Labels: ready

#3717 update the resolved file format
  Sources/PackageGraph/PinsStore.swift
  Tests/WorkspaceTests/PinsStoreTests.swift
Labels: ready

#3724 cleanup test manifest creation
  Sources/SPMTestSupport/ManifestExtensions.swift
  Tests/BuildTests/BuildPlanTests.swift
  Tests/CommandsTests/PackageToolTests.swift
  Tests/PackageGraphTests/PackageGraphTests.swift
  Tests/PackageGraphTests/RepositoryPackageContainerProviderTests.swift
  Tests/PackageModelTests/ManifestTests.swift
  Tests/SPMBuildCoreTests/PluginInvocationTests.swift
  Tests/XCBuildSupportTests/PIFBuilderTests.swift
  Tests/XcodeprojTests/GenerateXcodeprojTests.swift
  Tests/XcodeprojTests/PackageGraphTests.swift
Labels: ready

#3725 [5.5] Pass toolchain settings when using XCBuild
  Sources/Build/BuildPlan.swift
  Sources/XCBuildSupport/PIFBuilder.swift
  Sources/XCBuildSupport/XcodeBuildSystem.swift
  Tests/BuildTests/BuildPlanTests.swift
  Tests/XCBuildSupportTests/PIFBuilderTests.swift
Labels: 5.5

#3726 improve manifest loading diagnostics handling
  Sources/Workspace/Workspace.swift
Labels: ready, 5.5

#3094 Git Progress
  Sources/Commands/SwiftTool.swift
  Sources/SPMTestSupport/InMemoryGitRepository.swift
  Sources/SPMTestSupport/MockWorkspace.swift
  Sources/SourceControl/GitRepository.swift
  Sources/SourceControl/Repository.swift
  Sources/SourceControl/RepositoryManager.swift
  Sources/Workspace/Workspace.swift
  Tests/PackageGraphTests/RepositoryPackageContainerProviderTests.swift
  Tests/SourceControlTests/RepositoryManagerTests.swift
Labels: ready

#3729 refactor stream handling
  Sources/Build/BuildOperation.swift
  Sources/Build/BuildPlan.swift
  Sources/Build/ManifestBuilder.swift
  Sources/Commands/APIDigester.swift
  Sources/Commands/CMakeLists.txt
  Sources/Commands/Error.swift
  Sources/Commands/Snippets/CardStack.swift
  Sources/Commands/SwiftPackageTool.swift
  Sources/Commands/SwiftRunTool.swift
  Sources/Commands/SwiftTestTool.swift
  Sources/Commands/SwiftTool.swift
  Sources/Commands/show-dependencies.swift
  Sources/LLBuildManifest/DOTManifestSerializer.swift
  Sources/SPMBuildCore/BuildParameters.swift
  Sources/XCBuildSupport/XcodeBuildSystem.swift
  Sources/Xcodeproj/pbxproj.swift
  Sources/swiftpm-manifest-tool/main.swift
  Tests/PackageGraphTests/PubgrubTests.swift
  Tests/XcodeprojTests/GenerateXcodeprojTests.swift
Labels: ready

#3733 improve package location validation
  Sources/PackageGraph/PackageGraph+Loading.swift
  Sources/PackageModel/PackageIdentity.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: ready

#3734 [5.5] Disambiguate PIF target names
  IntegrationTests/Tests/IntegrationTests/XCBuildTests.swift
  Sources/XCBuildSupport/PIFBuilder.swift
  Sources/XCBuildSupport/XcodeBuildSystem.swift
  Tests/XCBuildSupportTests/PIFBuilderTests.swift
Labels: 5.5

#3736 fix warnings from API changes
  Sources/Build/ManifestBuilder.swift
  Sources/Commands/SwiftPackageTool.swift
  Sources/PackageLoading/PackageBuilder.swift
  Sources/PackageLoading/TargetSourcesBuilder.swift
  Sources/PackageModel/Target.swift
Labels: ready

#3741 use identity in workspace state tracking
  Sources/Workspace/Workspace.swift
Labels: ready

#3738 Mark package plugins as being available in 5.5 again, not 5.6
  Fixtures/Miscellaneous/Plugins/ContrivedTestPlugin/Package.swift
  Fixtures/Miscellaneous/Plugins/MyBinaryToolPlugin/Package.swift
  Fixtures/Miscellaneous/Plugins/MySourceGenClient/Package.swift
  Fixtures/Miscellaneous/Plugins/MySourceGenPlugin/Package.swift
  Fixtures/Miscellaneous/Plugins/SandboxTesterPlugin/Package.swift
  Sources/PackageDescription/Product.swift
  Sources/PackageDescription/Target.swift
  Tests/PackageLoadingTests/PD_5_4_LoadingTests.swift
  Tests/PackageLoadingTests/PD_5_5_LoadingTests.swift
  Tests/WorkspaceTests/ManifestSourceGenerationTests.swift
Labels: ready

#3743 update collections APIs to use package identity
  Sources/Commands/SwiftPackageCollectionsTool.swift
  Sources/PackageCollections/API.swift
  Sources/PackageCollections/Model/Package.swift
  Sources/PackageCollections/Model/TargetListResult.swift
  Sources/PackageCollections/PackageCollections.swift
  Sources/PackageCollections/Providers/GitHubPackageMetadataProvider.swift
  Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift
  Sources/PackageCollections/Providers/PackageMetadataProvider.swift
  Sources/PackageCollections/Storage/SQLitePackageCollectionsStorage.swift
  Sources/PackageCollections/Utility.swift
  Tests/PackageCollectionsTests/GitHubPackageMetadataProviderTests.swift
  Tests/PackageCollectionsTests/JSONPackageCollectionProviderTests.swift
  Tests/PackageCollectionsTests/PackageCollectionsStorageTests.swift
  Tests/PackageCollectionsTests/PackageCollectionsTests.swift
  Tests/PackageCollectionsTests/Utility.swift
Labels: ready

#3624 Update Registry documentation according to SE-0292 amendment
  Documentation/Registry.md
Labels: ready

#3744 use identity instead of location where possible
  Sources/PackageGraph/LocalPackageContainer.swift
  Sources/PackageGraph/PackageModel+Extensions.swift
  Sources/PackageGraph/RepositoryPackageContainer.swift
  Sources/PackageModel/Diagnostics.swift
  Sources/PackageModel/ToolsVersion.swift
  Sources/Workspace/ResolverPrecomputationProvider.swift
  Sources/Workspace/Workspace.swift
  Tests/CommandsTests/PackageToolTests.swift
  Tests/PackageGraphTests/RepositoryPackageContainerProviderTests.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: ready

#3740 [5.5] Fix crash with absolute path to binary artifact
  Sources/Workspace/Workspace.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: 5.5

#3745 do not export modules from workspace
  Examples/package-info/Sources/package-info/main.swift
  Sources/Commands/SwiftTool.swift
  Sources/SPMTestSupport/MockWorkspace.swift
  Sources/SPMTestSupport/misc.swift
  Sources/Workspace/CMakeLists.txt
  Sources/Workspace/Export.swift
  Sources/Workspace/ResolvedFileWatcher.swift
  Sources/Workspace/WorkspaceConfiguration.swift
  Tests/CommandsTests/BuildToolTests.swift
  Tests/CommandsTests/PackageToolTests.swift
  Tests/FunctionalTests/CFamilyTargetTests.swift
  Tests/WorkspaceTests/ManifestSourceGenerationTests.swift
Labels: ready

#3739 Fix the default location for diagnostics resulting from package manifest loading
  Sources/Workspace/Workspace.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: ready

#3723 refactor diagnostics
  NOTICE.txt
  Sources/Basics/CMakeLists.txt
  Sources/Basics/Observability.swift
  Sources/Basics/SQLiteBackedCache.swift
  Sources/Build/BuildPlan.swift
  Sources/Commands/Snippets/CardStack.swift
  Sources/Commands/SwiftBuildTool.swift
  Sources/Commands/SwiftPackageTool.swift
  Sources/Commands/SwiftRunTool.swift
  Sources/Commands/SwiftTestTool.swift
  Sources/Commands/SwiftTool.swift
  Sources/PackageCollections/PackageCollections.swift
  Sources/PackageCollections/Providers/GitHubPackageMetadataProvider.swift
  Sources/PackageGraph/Diagnostics.swift
  Sources/PackageGraph/PackageGraph+Loading.swift
  Sources/PackageLoading/Diagnostics.swift
  Sources/PackageLoading/ManifestLoader.swift
  Sources/PackageLoading/PackageBuilder.swift
  Sources/PackageLoading/Target+PkgConfig.swift
  Sources/PackageLoading/TargetSourcesBuilder.swift
  Sources/PackageModel/Package.swift
  Sources/SPMBuildCore/PluginInvocation.swift
  Sources/SPMTestSupport/MockWorkspace.swift
  Sources/SPMTestSupport/Observability.swift
  Sources/SPMTestSupport/misc.swift
  Sources/Workspace/Workspace.swift
  Sources/Xcodeproj/pbxproj.swift
  Tests/BasicsTests/ObservabilitySystemTests.swift
  Tests/BuildTests/BuildPlanTests.swift
  Tests/CommandsTests/MultiRootSupportTests.swift
  Tests/CommandsTests/PackageToolTests.swift
  Tests/PackageCollectionsSigningTests/CertificatePolicyTests.swift
  Tests/PackageCollectionsSigningTests/PackageCollectionSigningTest.swift
  Tests/PackageCollectionsSigningTests/Utilities.swift
  Tests/PackageGraphPerformanceTests/PackageGraphPerfTests.swift
  Tests/PackageGraphTests/PackageGraphTests.swift
  Tests/PackageLoadingTests/ModuleMapGenerationTests.swift
  Tests/PackageLoadingTests/PDLoadingTests.swift
  Tests/PackageLoadingTests/PD_4_0_LoadingTests.swift
  Tests/PackageLoadingTests/PD_4_2_LoadingTests.swift
  Tests/PackageLoadingTests/PD_5_0_LoadingTests.swift
  Tests/PackageLoadingTests/PD_5_2_LoadingTests.swift
  Tests/PackageLoadingTests/PD_5_3_LoadingTests.swift
  Tests/PackageLoadingTests/PackageBuilderTests.swift
  Tests/PackageLoadingTests/PkgConfigTests.swift
  Tests/PackageLoadingTests/TargetSourcesBuilderTests.swift
  Tests/SPMBuildCoreTests/PluginInvocationTests.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
  Tests/XCBuildSupportTests/PIFBuilderTests.swift
  Tests/XcodeprojTests/GenerateXcodeprojTests.swift
  Tests/XcodeprojTests/PackageGraphTests.swift
Labels: ready

#3755 convert the PackageCollections module to the new diagnostics apis
  Sources/Basics/HTTPClient.swift
  Sources/Basics/SQLiteBackedCache.swift
  Sources/PackageCollections/PackageCollections.swift
  Sources/PackageCollections/Providers/GitHubPackageMetadataProvider.swift
  Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift
  Sources/PackageCollections/Storage/FilePackageCollectionsSourcesStorage.swift
  Sources/PackageCollectionsSigning/Certificate/CertificatePolicy.swift
  Sources/PackageCollectionsSigning/PackageCollectionSigning.swift
  Sources/PackageLoading/ManifestLoader.swift
  Sources/Workspace/Workspace.swift
  Tests/PackageCollectionsSigningTests/CertificatePolicyTests.swift
  Tests/PackageCollectionsSigningTests/PackageCollectionSigningTest.swift
  Tests/PackageCollectionsSigningTests/Utilities.swift
  Tests/PackageCollectionsTests/JSONPackageCollectionProviderTests.swift
Labels: ready

#3753 Fix a unit test that is writing to the checkout of SwiftPM itself
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: ready

#3754 convert the PackageLoading module to the new diagnostics apis
  Sources/PackageLoading/ModuleMapGenerator.swift
  Sources/PackageLoading/PackageBuilder.swift
  Tests/PackageLoadingTests/ModuleMapGenerationTests.swift
Labels: ready

#3757 fix PkgConfigHint test on systems that do not have pkg-config installed
  Tests/BuildTests/BuildPlanTests.swift
Labels: ready

#3698 refactor managed dependencies
  Sources/PackageGraph/PackageGraph+Loading.swift
  Sources/PackageModel/PackageIdentity.swift
  Sources/PackageModel/PackageReference.swift
  Sources/SPMTestSupport/MockWorkspace.swift
  Sources/SPMTestSupport/misc.swift
  Sources/Workspace/ManagedDependency.swift
  Sources/Workspace/ResolverPrecomputationProvider.swift
  Sources/Workspace/Workspace.swift
  Sources/Workspace/WorkspaceState.swift
  Tests/PackageGraphPerformanceTests/PackageGraphPerfTests.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: ready

#3771 rename LLBuild manifest builder to LLBuildManifestBuilder
  Sources/Build/CMakeLists.txt
  Sources/Build/LLBuildManifestBuilder.swift
Labels: ready

#3772 reduce duplicate code in test tool
  Sources/Commands/SwiftTestTool.swift
Labels: ready

#3770 replace use of NSUUID with UUID
  Sources/SPMTestSupport/InMemoryGitRepository.swift
Labels: ready

#3766 refactor workspace repository handling
  Package.swift
  Sources/PackageGraph/CMakeLists.txt
  Sources/PackageGraph/CheckoutState.swift
  Sources/PackageGraph/DependencyMirrors.swift
  Sources/PackageGraph/GraphLoadingNode.swift
  Sources/PackageGraph/PackageContainer.swift
  Sources/PackageGraph/PackageGraph+Loading.swift
  Sources/PackageGraph/PackageGraph.swift
  Sources/PackageGraph/PackageGraphRoot.swift
  Sources/PackageGraph/PackageModel+Extensions.swift
  Sources/PackageGraph/PinsStore.swift
  Sources/PackageGraph/Version+Extensions.swift
  Sources/PackageGraph/VersionSetSpecifier.swift
  Sources/PackageLoading/Diagnostics.swift
  Sources/PackageLoading/IdentityResolver.swift
  Sources/PackageLoading/ManifestJSONParser.swift
  Sources/PackageLoading/ManifestLoader.swift
  Sources/PackageLoading/PackageBuilder.swift
  Sources/PackageLoading/Target+PkgConfig.swift
  Sources/PackageLoading/TargetSourcesBuilder.swift
  Sources/PackageLoading/ToolsVersionLoader.swift
  Sources/PackageModel/PackageReference.swift
  Sources/SPMTestSupport/MockManifestLoader.swift
  Sources/SPMTestSupport/MockWorkspace.swift
  Sources/Workspace/CMakeLists.txt
  Sources/Workspace/FileSystemPackageContainer.swift
  Sources/Workspace/SourceControlPackageContainer.swift
  Sources/Workspace/Workspace.swift
  Sources/Workspace/WorkspaceState.swift
  Tests/PackageLoadingTests/PDLoadingTests.swift
  Tests/WorkspaceTests/PackageContainerProviderTests.swift
Labels: ready
