Repository swiftlang/swift-package-manager, pull requests merged in 2021-07, with the labels that each got.

#3577 [5.5] Android: add cross-compilation configuration file flag
  Utilities/bootstrap
Labels: 5.5, ready

#3586 Allow empty arrays of unsafe flags (already allowed in practice; this removes a debug assertion and adds a test)
  Sources/PackageModel/Manifest/TargetBuildSettingDescription.swift
  Tests/PackageLoadingTests/PackageBuilderTests.swift
Labels: ready

#3585 Fix build failures when two or more plugin-generated build commands have the same name
  Fixtures/Miscellaneous/Plugins/ContrivedTestPlugin/Package.swift
  Fixtures/Miscellaneous/Plugins/ContrivedTestPlugin/Plugins/MyAmbiguouslyNamedCommandPlugin/plugin.swift
  Fixtures/Miscellaneous/Plugins/ContrivedTestPlugin/Sources/MyLocalTool/bar.dat
  Sources/Build/ManifestBuilder.swift
Labels: ready

#3575 [5.5] SwiftPM complains about @main in non main.swift file when integrated driver is not enabled
  Fixtures/Miscellaneous/AtMainSupport/Package.swift
  Fixtures/Miscellaneous/AtMainSupport/Sources/ClangExecSingleFile/NotMain.c
  Fixtures/Miscellaneous/AtMainSupport/Sources/SwiftExecMultiFile/NotMain.swift
  Fixtures/Miscellaneous/AtMainSupport/Sources/SwiftExecMultiFile/OtherFile.swift
  Fixtures/Miscellaneous/AtMainSupport/Sources/SwiftExecSingleFile/NotMain.swift
  Sources/Build/BuildPlan.swift
  Tests/CommandsTests/BuildToolTests.swift
Labels: 5.5, ready

#3536 [5.5] Build PackageDescription and PackagePlugin universal on macOS platform
  Fixtures/Miscellaneous/LibraryEvolution/Package.swift
  Fixtures/Miscellaneous/LibraryEvolution/Sources/A/A.swift
  Fixtures/Miscellaneous/LibraryEvolution/Sources/B/B.swift
  Package.swift
  Sources/Build/BuildPlan.swift
  Sources/PackageDescription/CMakeLists.txt
  Sources/PackagePlugin/CMakeLists.txt
  Sources/XCBuildSupport/PIF.swift
  Sources/XCBuildSupport/PIFBuilder.swift
  Tests/CommandsTests/BuildToolTests.swift
  Tests/XCBuildSupportTests/PIFBuilderTests.swift
  Utilities/bootstrap
Labels: 5.5, ready

#3574 [5.5] Align experimental implementations of SE-0303 and SE-0305 with proposal
  Fixtures/Miscellaneous/Plugins/ContrivedTestPlugin/Plugins/MySourceGenBuildToolPlugin/plugin.swift
  Fixtures/Miscellaneous/Plugins/MyBinaryToolPlugin/Binaries/MyVendedSourceGenBuildTool.artifactbundle/info.json
  Fixtures/Miscellaneous/Plugins/MyBinaryToolPlugin/Binaries/MyVendedSourceGenBuildTool.artifactbundle/mytool-linux/mytool
  Fixtures/Miscellaneous/Plugins/MyBinaryToolPlugin/Binaries/MyVendedSourceGenBuildTool.artifactbundle/mytool-macos/mytool
  Fixtures/Miscellaneous/Plugins/MyBinaryToolPlugin/Package.swift
  Fixtures/Miscellaneous/Plugins/MyBinaryToolPlugin/Plugins/MySourceGenBuildToolPlugin/plugin.swift
  Fixtures/Miscellaneous/Plugins/MySourceGenPlugin/Plugins/MySourceGenBuildToolPlugin/plugin.swift
  Fixtures/Miscellaneous/Plugins/MySourceGenPlugin/Plugins/MySourceGenPrebuildPlugin/plugin.swift
  Fixtures/Miscellaneous/Plugins/SandboxTesterPlugin/Plugins/MySourceGenBuildToolPlugin/plugin.swift
  Sources/PackageDescription/Target.swift
  Sources/PackageLoading/PackageBuilder.swift
  Sources/PackageModel/Manifest/TargetDescription.swift
  Sources/PackageModel/Target.swift
  Sources/PackagePlugin/ImplementationDetails.swift
  Sources/PackagePlugin/PublicAPI/CommandConstructor.swift
  Sources/PackagePlugin/PublicAPI/FileList.swift
  Sources/PackagePlugin/PublicAPI/Globals.swift
  Sources/PackagePlugin/PublicAPI/TargetBuildContext.swift
  Sources/SPMBuildCore/PluginInvocation.swift
  Sources/Workspace/Workspace.swift
  Tests/BuildTests/BuildPlanTests.swift
  Tests/PackageLoadingTests/PD5_3LoadingTests.swift
  Tests/PackageLoadingTests/PD5_5LoadingTests.swift
  Tests/PackageLoadingTests/PackageBuilderTests.swift
  Tests/SPMBuildCoreTests/PluginInvocationTests.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: 5.5, ready

#3473 [5.5] Fix swift package init --help printout
  Package.swift
  Sources/Commands/SwiftBuildTool.swift
  Sources/Commands/SwiftPackageTool.swift
  Sources/Commands/SwiftRunTool.swift
  Sources/Commands/SwiftTestTool.swift
Labels: 5.5

#3596 [SR-14896] `swift build --build-system xcode` doesn't respect `SWIFT_EXEC`
  Sources/XCBuildSupport/XcodeBuildSystem.swift
  Tests/CommandsTests/BuildToolTests.swift
Labels: ready

#3600 [5.5] [SR-14896] `swift build --build-system xcode` doesn't respect `SWIFT_EXEC`
  Sources/XCBuildSupport/XcodeBuildSystem.swift
  Tests/CommandsTests/BuildToolTests.swift
Labels: 5.5, ready

#3597 `swift build --build-system xcode` is hardcoding "x86_64" rather than using the build destination arch
  Sources/XCBuildSupport/XcodeBuildSystem.swift
  Tests/CommandsTests/BuildToolTests.swift
Labels: ready

#3602 [5.5][Collections] Sort packages by name instead of identity
  Sources/PackageCollections/Model/Package.swift
  Sources/PackageCollections/PackageCollections.swift
  Sources/PackageCollections/Storage/SQLitePackageCollectionsStorage.swift
Labels: 5.5

#3606 [5.5][Collections] Support Swift Package Collection cert type
  Sources/PackageCollections/PackageCollections+CertificatePolicy.swift
  Sources/PackageCollectionsSigning/Certificate/CertificatePolicy.swift
  Sources/PackageCollectionsSigning/PackageCollectionSigning.swift
  Tests/PackageCollectionsSigningTests/CertificatePolicyTests.swift
  Tests/PackageCollectionsSigningTests/PackageCollectionSigningTest.swift
Labels: 5.5

#3608 fix a bug where resoved files looses package name case
  Sources/PackageGraph/PinsStore.swift
  Tests/PackageGraphTests/PackageGraphTests.swift
Labels: ready

#3610 fix a bug where resolved file loses package name case
  Sources/PackageGraph/PinsStore.swift
  Tests/PackageGraphTests/PackageGraphTests.swift
Labels: 5.5, ready

#3612 [5.5][Collections] Update test certs
  Fixtures/Collections/Signing/TestIntermediateCA.cer
  Fixtures/Collections/Signing/TestIntermediateCA_ec.cer
  Fixtures/Collections/Signing/TestIntermediateCA_rsa.cer
  Fixtures/Collections/Signing/TestRootCA.cer
  Fixtures/Collections/Signing/TestRootCA_rsa.cer
  Fixtures/Collections/Signing/Test_ec.cer
  Fixtures/Collections/Signing/Test_ec_key.pem
  Fixtures/Collections/Signing/Test_rsa.cer
  Fixtures/Collections/Signing/Test_rsa_key.pem
  Tests/PackageCollectionsSigningTests/CertificatePolicyTests.swift
  Tests/PackageCollectionsSigningTests/CertificateTests.swift
  Tests/PackageCollectionsSigningTests/PackageCollectionSigningTest.swift
  Tests/PackageCollectionsSigningTests/Utilities.swift
Labels: 5.5

#3613 [5.5][Collections] Stale search index data
  Sources/PackageCollections/Storage/SQLitePackageCollectionsStorage.swift
Labels: 5.5

#3609 Ignore .docc files rather than emitting warnings, since it's useful to have them in packages without warnings
  Sources/PackageLoading/TargetSourcesBuilder.swift
  Tests/PackageLoadingTests/TargetSourcesBuilderTests.swift
Labels: ready

#3615 make target dependency lookup case-insensitive
  Fixtures/DependencyResolution/External/PackageLookupCaseInsensitive/dep/Package.swift
  Fixtures/DependencyResolution/External/PackageLookupCaseInsensitive/dep/Sources/Dep/dep.swift
  Fixtures/DependencyResolution/External/PackageLookupCaseInsensitive/pkg/Package.swift
  Fixtures/DependencyResolution/External/PackageLookupCaseInsensitive/pkg/Sources/pkg/pkg.swift
  Sources/PackageModel/Manifest.swift
  Tests/FunctionalTests/DependencyResolutionTests.swift
Labels: ready

#3619 [5.5][Collections] Removed local package collection comes back alive
  Sources/PackageCollections/PackageCollections.swift
Labels: 5.5

#3618 [5.5] make target dependency lookup non-case-sensitive
  Fixtures/DependencyResolution/External/PackageLookupCaseInsensitive/dep/Package.swift
  Fixtures/DependencyResolution/External/PackageLookupCaseInsensitive/dep/Sources/Dep/dep.swift
  Fixtures/DependencyResolution/External/PackageLookupCaseInsensitive/pkg/Package.swift
  Fixtures/DependencyResolution/External/PackageLookupCaseInsensitive/pkg/Sources/pkg/pkg.swift
  Sources/PackageModel/Manifest.swift
  Tests/FunctionalTests/DependencyResolutionTests.swift
Labels: 5.5, ready

#3621 [5.5] Do not print workspace-state diagnostic to stdout
  Sources/Workspace/WorkspaceState.swift
Labels: 5.5

#3620 Refine the change to ignore .docc files rather than emit warnings to avoid having multiple definitions for the same file extension
  Sources/Commands/SwiftTool.swift
  Sources/PackageLoading/TargetSourcesBuilder.swift
  Sources/SPMTestSupport/misc.swift
  Tests/PackageLoadingTests/TargetSourcesBuilderTests.swift
Labels: ready

#3616 [5.5] Ignore .docc files rather than emitting warnings, since it's useful to have them in packages without warnings
  Sources/Commands/SwiftTool.swift
  Sources/PackageLoading/TargetSourcesBuilder.swift
  Sources/SPMTestSupport/misc.swift
  Tests/PackageLoadingTests/TargetSourcesBuilderTests.swift
Labels: 5.5, ready

#3595 adopt swift-collections
  CMakeLists.txt
  CONTRIBUTING.md
  Package.swift
  Sources/Basics/CMakeLists.txt
  Sources/Basics/Exports.swift
  Sources/Build/BuildPlan.swift
  Sources/PackageGraph/PackageGraph+Loading.swift
  Sources/PackageGraph/Pubgrub/Incompatibility.swift
  Sources/PackageGraph/Pubgrub/PartialSolution.swift
  Sources/PackageGraph/Pubgrub/PubgrubDependencyResolver.swift
  Sources/PackageLoading/PackageBuilder.swift
  Tests/PackageGraphTests/PubgrubTests.swift
  Utilities/bootstrap
Labels: ready

#3604 [5.5] Do not crash on relative file URLs in a dependency
  Sources/PackageLoading/ManifestLoader.swift
  Sources/PackageLoading/PackageDescription4Loader.swift
  Tests/PackageLoadingTests/PD4_2LoadingTests.swift
Labels: 5.5

#3637 [5.5][Collections] populateTargetTrie changes
  Sources/PackageCollections/Storage/SQLitePackageCollectionsStorage.swift
  Tests/PackageCollectionsTests/PackageCollectionsTests.swift
Labels: 5.5

#3639 [5.5] Improve diagnostic when automatic resolution is disabled
  Sources/Workspace/Workspace.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: 5.5
