Repository swiftlang/swift-package-manager, pull requests merged in 2021-01, with the labels that each got.

#3157 Fix compiler warnings
  Sources/Build/SwiftCompilerOutputParser.swift
  Sources/SourceControl/RepositoryManager.swift
  Sources/XCBuildSupport/PIF.swift
  Sources/XCBuildSupport/PIFBuilder.swift
  Sources/XCBuildSupport/XCBuildOutputParser.swift
  Sources/Xcodeproj/XcodeProjectModelSerialization.swift
Labels: ready

#3150 Call artifacts download delegate final method
  Sources/Workspace/Workspace.swift
Labels: ready

#3148 Workspace delegate weak property
  Sources/Commands/SwiftTool.swift
  Sources/Workspace/Workspace.swift
Labels: ready

#3146 Add optional delegate perameter to Workspace.create()
  Sources/Workspace/Workspace.swift
Labels: ready

#3143 Update PackageDescription.md
  Documentation/PackageDescription.md
Labels: ready

#3131 performance: shared manifests cache
  Sources/Commands/Options.swift
  Sources/Commands/SwiftTool.swift
  Sources/PackageLoading/ManifestLoader.swift
  Sources/SPMTestSupport/MockManifestLoader.swift
  Sources/Workspace/Workspace.swift
  Tests/PackageLoadingTests/PD4_2LoadingTests.swift
Labels: ready

#3147 make code more resilient when cache directories cannot be created
  Sources/Commands/SwiftTool.swift
Labels: ready

#3149 Add missing dispatch group leave in case of download artifacts download fail
  Sources/Workspace/Workspace.swift
Labels: ready

#3145 [5.3] The llbuild dependency should reference the 5.3 release branch
  Package.swift
Labels: ready

#3116 Refactor generation of SHA256 checksums
  Sources/Basics/ByteString+Extensions.swift
  Sources/Basics/CMakeLists.txt
  Sources/PackageLoading/ManifestLoader.swift
  Sources/SourceControl/Repository.swift
  Sources/Workspace/Workspace.swift
  Sources/XCBuildSupport/PIF.swift
  Tests/BasicsTests/ByteStringExtensionsTests.swift
Labels: ready

#3169 [5.4] remove leftover debug print statement
  Sources/Commands/SwiftTool.swift
Labels: 5.4

#3179 [5.4] identity collisions diagnostics test and fixes
  Sources/PackageGraph/PackageGraph+Loading.swift
  Sources/PackageGraph/PackageGraph.swift
  Sources/Workspace/Workspace.swift
  Tests/PackageGraphTests/PackageGraphTests.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: 5.4

#3177 [5.4] SwiftPM complains about missing tools version comments in SwiftPM v3 version-specific manifest overrides
  CHANGELOG.md
  Sources/PackageLoading/ToolsVersionLoader.swift
  Tests/PackageLoadingTests/PD4_2LoadingTests.swift
Labels: 5.4

#3175 [5.4] change manifest loading deduping logic to be based on identity instead of manifest name
  Sources/PackageModel/Product.swift
  Sources/Workspace/Workspace.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: 5.4

#3104 Add swift package archive-source subcommand
  Sources/Commands/SwiftPackageTool.swift
  Sources/SourceControl/GitRepository.swift
  Tests/CommandsTests/PackageToolTests.swift
Labels: next

#3122 Updates to package collection models
  Fixtures/Collections/GitHub/license.json
  Fixtures/Collections/JSON/good.json
  Sources/Commands/SwiftPackageCollectionsTool.swift
  Sources/PackageCollections/JSONModel/JSONCollection+v1.swift
  Sources/PackageCollections/Model/License.swift
  Sources/PackageCollections/Model/Package.swift
  Sources/PackageCollections/PackageCollections.swift
  Sources/PackageCollections/Providers/GitHubPackageMetadataProvider.swift
  Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift
  Sources/PackageCollections/Providers/PackageMetadataProvider.swift
  Tests/PackageCollectionsTests/GitHubPackageMetadataProviderTests.swift
  Tests/PackageCollectionsTests/JSONPackageCollectionModelTests.swift
  Tests/PackageCollectionsTests/JSONPackageCollectionProviderTests.swift
  Tests/PackageCollectionsTests/PackageCollectionsModelTests.swift
  Tests/PackageCollectionsTests/PackageCollectionsTests.swift
  Tests/PackageCollectionsTests/Utility.swift
Labels: next

#3192 [5.4] Convert preconditions for `TargetDescription` into errors
  Sources/PackageLoading/ManifestLoader.swift
  Sources/PackageLoading/PackageDescription4Loader.swift
  Sources/PackageModel/Manifest/TargetDescription.swift
  Sources/SPMTestSupport/MockPackage.swift
  Sources/SPMTestSupport/MockTarget.swift
  Sources/SPMTestSupport/MockWorkspace.swift
  Tests/BuildTests/BuildPlanTests.swift
  Tests/CommandsTests/PackageToolTests.swift
  Tests/PackageGraphPerformanceTests/PackageGraphPerfTests.swift
  Tests/PackageGraphTests/RepositoryPackageContainerProviderTests.swift
  Tests/PackageLoadingTests/PD5_3LoadingTests.swift
  Tests/PackageLoadingTests/PackageBuilderTests.swift
  Tests/PackageLoadingTests/TargetSourcesBuilderTests.swift
  Tests/PackageModelTests/ManifestTests.swift
Labels: 5.4

#3185 [5.4] Actually skip not needed dependencies during dependency resolution
  Sources/PackageModel/Manifest.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: 5.4

#3194 [5.4] Change 999.0 to 5.4 in package description and related tests
  Fixtures/Miscellaneous/AtMainSupport/Package.swift
  Sources/PackageDescription/LanguageStandardSettings.swift
  Sources/PackageDescription/Target.swift
  Sources/PackageLoading/PackageBuilder.swift
  Sources/PackageModel/ToolsVersion.swift
  Tests/CommandsTests/PackageToolTests.swift
  Tests/PackageLoadingTests/PackageBuilderTests.swift
Labels: 5.4

#3197 [5.4] Fix incorrect use of current tools version in unit tests that assume 5.3 semantics
  Tests/CommandsTests/PackageToolTests.swift
Labels: 5.4

#3183 [5.4] Adjust dependencies on 5.4 branch to `release/5.4`
  Package.swift
Labels: 5.4

#3204 [5.4] limit size of sqlite manifest cache (#3178)
  Sources/PackageLoading/ManifestLoader.swift
  Tests/PackageLoadingTests/ManifestLoaderSQLiteCacheTests.swift
Labels: 5.4

#3108 Package collections: improve search performance
  Sources/Basics/ConcurrencyHelpers.swift
  Sources/PackageCollections/CMakeLists.txt
  Sources/PackageCollections/Model/TargetListResult.swift
  Sources/PackageCollections/Storage/PackageCollectionsStorage.swift
  Sources/PackageCollections/Storage/SQLitePackageCollectionsStorage.swift
  Sources/PackageCollections/Storage/Trie.swift
  Tests/PackageCollectionsTests/PackageCollectionsStorageTests.swift
  Tests/PackageCollectionsTests/TrieTests.swift
Labels: next

#3210 [5.4] Fix a tools version loading failure that occurred when the regular manifest doesn't contain a tools-version.
  Sources/PackageLoading/ToolsVersionLoader.swift
  Tests/PackageLoadingTests/PD4_2LoadingTests.swift
Labels: 5.4

#3211 [5.4] restore generate-linux-main for backwards compatibility (#3207)
  Sources/Commands/CMakeLists.txt
  Sources/Commands/GenerateLinuxMain.swift
  Sources/Commands/SwiftTestTool.swift
  Tests/FunctionalTests/MiscellaneousTests.swift
Labels: 5.4

#3220 [5.4] resolve timeout for repositories with large number of tags (#3218)
  Sources/PackageGraph/Pubgrub/PubgrubDependencyResolver.swift
  Sources/SourceControl/GitRepository.swift
Labels: 5.4

#3219 [5.4] SR-12050: lldb error: could not build C module 'CNIOBoringSSLShims' (Linux 5.1.3) when debugging
  Sources/Build/BuildPlan.swift
  Tests/BuildTests/BuildPlanTests.swift
Labels: 5.4

#3199 Move package collection JSON models to a separate module
  Package.swift
  Sources/CMakeLists.txt
  Sources/PackageCollections/CMakeLists.txt
  Sources/PackageCollections/JSONModel/JSONCollection+v1.swift
  Sources/PackageCollections/PackageCollections+Validation.swift
  Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift
  Sources/PackageCollectionsModel/CMakeLists.txt
  Sources/PackageCollectionsModel/PackageCollectionModel+v1.swift
  Sources/PackageCollectionsModel/PackageCollectionModel.swift
  Tests/PackageCollectionsModelTests/PackageCollectionModelTests.swift
  Tests/PackageCollectionsTests/PackageCollectionValidationTests.swift
Labels: next

#3222 [5.4] Remove the in-memory manifest cache to fix an internal error caused by stale cache data
  Sources/PackageLoading/ManifestLoader.swift
  Tests/PackageLoadingTests/PD4_2LoadingTests.swift
Labels: 5.4

#3201 [Collections] API changes to support signed collections
  Sources/Commands/SwiftPackageCollectionsTool.swift
  Sources/PackageCollections/API.swift
  Sources/PackageCollections/Model/Collection.swift
  Sources/PackageCollections/PackageCollections.swift
  Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift
  Sources/PackageCollections/Storage/FilePackageCollectionsSourcesStorage.swift
  Sources/PackageCollections/Storage/PackageCollectionsSourcesStorage.swift
  Tests/PackageCollectionsTests/PackageCollectionsSourcesStorageTest.swift
  Tests/PackageCollectionsTests/PackageCollectionsTests.swift
  Tests/PackageCollectionsTests/Utility.swift
Labels: next

#3195 [Collections] `add` should only add to config if fetch is successful
  Sources/PackageCollections/PackageCollections.swift
  Tests/PackageCollectionsTests/PackageCollectionsModelTests.swift
  Tests/PackageCollectionsTests/PackageCollectionsTests.swift
Labels: next

#3214 api cleanup in preperation for identity improvements
  Bar-1.2.3.zip
  Sources/Commands/SwiftPackageCollectionsTool.swift
  Sources/Commands/SwiftTool.swift
  Sources/PackageCollections/Providers/GitHubPackageMetadataProvider.swift
  Sources/PackageCollections/Utility.swift
  Sources/PackageGraph/DependencyResolutionNode.swift
  Sources/PackageGraph/LocalPackageContainer.swift
  Sources/PackageGraph/PackageContainer.swift
  Sources/PackageGraph/PackageGraph+Loading.swift
  Sources/PackageGraph/PackageGraphRoot.swift
  Sources/PackageGraph/PackageModel+Extensions.swift
  Sources/PackageGraph/PinsStore.swift
  Sources/PackageGraph/Pubgrub/PubgrubDependencyResolver.swift
  Sources/PackageGraph/RepositoryPackageContainer.swift
  Sources/PackageModel/Manifest/PackageDependencyDescription.swift
  Sources/PackageModel/PackageIdentity.swift
  Sources/PackageModel/PackageReference.swift
  Sources/SPMTestSupport/MockDependencyGraph.swift
  Sources/SPMTestSupport/MockPackageContainer.swift
  Sources/SPMTestSupport/MockWorkspace.swift
  Sources/Workspace/ManagedArtifact.swift
  Sources/Workspace/ManagedDependency.swift
  Sources/Workspace/ResolverPrecomputationProvider.swift
  Sources/Workspace/Workspace.swift
  Tests/PackageCollectionsTests/GitHubPackageMetadataProviderTests.swift
  Tests/PackageGraphTests/PubgrubTests.swift
  Tests/PackageGraphTests/RepositoryPackageContainerProviderTests.swift
  Tests/WorkspaceTests/PinsStoreTests.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: next

#3227 [5.4] Fix potential crash in repository cache fallback
  Sources/SourceControl/RepositoryManager.swift
Labels: 5.4
