Repository swiftlang/swift-package-manager, pull requests merged in 2021-04, with the labels that each got.

#3379 [Collections] Documentation: add more details on the CLI
  Documentation/PackageCollections.md
Labels: ready

#3408 Use implementation only import of Foundation in PackagePlugin
  Sources/PackagePlugin/ImplementationDetails.swift
  Sources/PackagePlugin/PublicAPI/Path.swift
Labels: ready

#3406 Enable symlink support explicitly
  Sources/SourceControl/GitRepository.swift
Labels: ready

#3413 [5.5] Disable the `development` flag on the 5.5 branch, marking 5.5 binaries as release builds
  Sources/Basics/SwiftVersion.swift
Labels: 5.5, ready

#3416 [5.5] MiscellaneousTests.testOverridingSwiftcArguments() fails on Apple Silicon
  Fixtures/Miscellaneous/DistantFutureDeploymentTarget/Package.swift
  Fixtures/Miscellaneous/DistantFutureDeploymentTarget/Sources/main.swift
  Fixtures/Miscellaneous/OverrideSwiftcArgs/Package.swift
  Tests/FunctionalTests/MiscellaneousTests.swift
Labels: 5.5, ready

#3415 Fix a problem in the logic to generate manifest source from existing parsed manifest structs
  Sources/PackageModel/ManifestSourceGeneration.swift
  Tests/WorkspaceTests/ManifestSourceGenerationTests.swift
Labels: ready

#3410 Pass compiler flags to alllow use of `@main` in single-source-file executable modules
  CHANGELOG.md
  Sources/Build/BuildPlan.swift
  Tests/BuildTests/BuildPlanTests.swift
Labels: ready

#3422 [5.5] Fix a problem in the logic to generate manifest source from existing parsed manifest structs
  Sources/PackageModel/ManifestSourceGeneration.swift
  Tests/WorkspaceTests/ManifestSourceGenerationTests.swift
Labels: 5.5, ready

#3421 [5.5] Pass compiler flags to alllow use of @main in single-source-file executable modules
  CHANGELOG.md
  Sources/Build/BuildPlan.swift
  Tests/BuildTests/BuildPlanTests.swift
Labels: 5.5, ready

#3424 Add compiler diagnostics to a test that sometimes fails in CI
  Tests/FunctionalTests/MiscellaneousTests.swift
Labels: ready

#3419 [5.5][Collections] Better handling of spaces in collection file path
  Sources/Commands/SwiftPackageCollectionsTool.swift
Labels: 5.5, ready

#3420 add delegate to track events from the dependency resolver
  Sources/PackageGraph/DependencyResolver.swift
  Sources/PackageGraph/Pubgrub/PartialSolution.swift
  Sources/PackageGraph/Pubgrub/PubgrubDependencyResolver.swift
  Sources/Workspace/Workspace.swift
  Tests/PackageGraphPerformanceTests/DependencyResolverPerfTests.swift
  Tests/PackageGraphTests/PubgrubTests.swift
Labels: ready

#3425 [5.5] add delegate to track events from the dependency resolver
  Sources/PackageGraph/DependencyResolver.swift
  Sources/PackageGraph/Pubgrub/PartialSolution.swift
  Sources/PackageGraph/Pubgrub/PubgrubDependencyResolver.swift
  Sources/Workspace/Workspace.swift
  Tests/PackageGraphPerformanceTests/DependencyResolverPerfTests.swift
  Tests/PackageGraphTests/PubgrubTests.swift
Labels: 5.5, ready

#3428 remove dead code
  Sources/Commands/SwiftTool.swift
Labels: ready

#3429 fix docker SwiftPM cache setup
  Utilities/Docker/docker-compose.yaml
Labels: ready

#3433 fix a bug in test discovery where tests defined in extensions break the discovery
  Fixtures/Miscellaneous/TestDiscovery/Extensions/Package.swift
  Fixtures/Miscellaneous/TestDiscovery/Extensions/Sources/Simple/Simple.swift
  Fixtures/Miscellaneous/TestDiscovery/Extensions/Tests/SimpleTests/SwiftTests1.swift
  Fixtures/Miscellaneous/TestDiscovery/Extensions/Tests/SimpleTests/SwiftTests2.swift
  Fixtures/Miscellaneous/TestDiscovery/Extensions/Tests/SimpleTests/SwiftTests3.swift
  Fixtures/Miscellaneous/TestDiscovery/Extensions/Tests/SimpleTests/SwiftTests4.swift
  Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
  Tests/FunctionalTests/TestDiscoveryTests.swift
Labels: ready

#3434 [5.5] deprecate willClone/didClone in favor of willCreateWorkingCopy/didCreateWorkingCopy
  Sources/Commands/APIDigester.swift
  Sources/Commands/SwiftTool.swift
  Sources/SPMTestSupport/InMemoryGitRepository.swift
  Sources/SPMTestSupport/MockWorkspace.swift
  Sources/SourceControl/GitRepository.swift
  Sources/SourceControl/Repository.swift
  Sources/SourceControl/RepositoryManager.swift
  Sources/Workspace/Workspace.swift
  Sources/Xcodeproj/generate.swift
  Tests/FunctionalTests/DependencyResolutionTests.swift
  Tests/FunctionalTests/MiscellaneousTests.swift
  Tests/PackageGraphTests/RepositoryPackageContainerProviderTests.swift
  Tests/SourceControlTests/GitRepositoryTests.swift
  Tests/SourceControlTests/InMemoryGitRepositoryTests.swift
  Tests/SourceControlTests/RepositoryManagerTests.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: 5.5

#3435 [5.5] fix a bug in test discovery where tests define in extensions break the discovery
  Fixtures/Miscellaneous/TestDiscovery/Extensions/Package.swift
  Fixtures/Miscellaneous/TestDiscovery/Extensions/Sources/Simple/Simple.swift
  Fixtures/Miscellaneous/TestDiscovery/Extensions/Tests/SimpleTests/SwiftTests1.swift
  Fixtures/Miscellaneous/TestDiscovery/Extensions/Tests/SimpleTests/SwiftTests2.swift
  Fixtures/Miscellaneous/TestDiscovery/Extensions/Tests/SimpleTests/SwiftTests3.swift
  Fixtures/Miscellaneous/TestDiscovery/Extensions/Tests/SimpleTests/SwiftTests4.swift
  Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
  Tests/FunctionalTests/TestDiscoveryTests.swift
Labels: 5.5

#3436 make test discovery generation output predictable
  Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
Labels: ready

#3423 [5.4] [Bootstrap] Do not pass `-Ddispatch_DIR` to the Yams CMake build (#3363)
  Tests/BuildTests/BuildPlanTests.swift
  Utilities/bootstrap
Labels: 5.4

#3440 [5.5] make test discovery generation output predictable
  Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
Labels: 5.5

#3442 [5.5][Collections] Improve error message when package collection download times out
  Sources/Commands/SwiftPackageCollectionsTool.swift
Labels: 5.5

#3427 improve output when resolving packages
  Sources/Basics/DispatchTimeInterval+Extensions.swift
  Sources/Commands/SwiftTool.swift
  Sources/PackageGraph/DependencyResolver.swift
  Sources/PackageGraph/Pubgrub/PubgrubDependencyResolver.swift
  Sources/SPMTestSupport/MockWorkspace.swift
  Sources/SourceControl/RepositoryManager.swift
  Sources/Workspace/Workspace.swift
  Tests/FunctionalTests/MiscellaneousTests.swift
  Tests/PackageGraphTests/PubgrubTests.swift
  Tests/PackageGraphTests/RepositoryPackageContainerProviderTests.swift
  Tests/SourceControlTests/RepositoryManagerTests.swift
Labels: ready

#3445 [5.5][Collections] SQLite optimizations
  Sources/PackageCollections/Storage/SQLitePackageCollectionsStorage.swift
Labels: 5.5

#3449 [5.5] Fix new package XCTest file formatting and include throws keyword
  Sources/Workspace/InitPackage.swift
  Tests/WorkspaceTests/InitTests.swift
Labels: 5.5

#3444 [5.5] Add Mac Catalyst as a supported platform
  Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift
  Sources/PackageDescription/SupportedPlatforms.swift
  Sources/PackageLoading/ManifestLoader.swift
  Sources/PackageLoading/MinimumDeploymentTarget.swift
  Sources/PackageLoading/PlatformRegistry.swift
  Sources/PackageModel/ManifestSourceGeneration.swift
  Sources/PackageModel/Platform.swift
  Sources/SPMTestSupport/PIFTester.swift
  Sources/Workspace/InitPackage.swift
  Sources/XCBuildSupport/PIF.swift
  Sources/XCBuildSupport/PIFBuilder.swift
  Tests/PackageLoadingTests/MinimumDeploymentTargetTests.swift
  Tests/PackageLoadingTests/PackageBuilderTests.swift
Labels: 5.5

#3452 [5.5] fix package.resolved interplay with mirrors
  Sources/Commands/SwiftPackageTool.swift
  Sources/PackageGraph/DependencyMirrors.swift
  Sources/PackageGraph/PinsStore.swift
  Sources/SPMTestSupport/MockWorkspace.swift
  Sources/Workspace/Workspace.swift
  Tests/CommandsTests/PackageToolTests.swift
  Tests/FunctionalTests/DependencyResolutionTests.swift
  Tests/PackageGraphTests/PackageGraphTests.swift
  Tests/PackageGraphTests/PubgrubTests.swift
  Tests/WorkspaceTests/PinsStoreTests.swift
  Tests/WorkspaceTests/WorkspaceConfigurationTests.swift
Labels: 5.5

#3453 [5.5][Collections] Use persistent cache for GitHub package metadata (#3441)
  Sources/Basics/CMakeLists.txt
  Sources/Basics/SQLiteBackedCache.swift
  Sources/PackageCollections/PackageCollections.swift
  Sources/PackageCollections/Providers/GitHubPackageMetadataProvider.swift
  Sources/PackageCollections/Providers/PackageMetadataProvider.swift
  Sources/PackageLoading/ManifestLoader.swift
  Tests/BasicsTests/SQLiteBackedCacheTests.swift
  Tests/PackageCollectionsTests/GitHubPackageMetadataProviderTests.swift
  Tests/PackageCollectionsTests/PackageCollectionsTests.swift
  Tests/PackageCollectionsTests/Utility.swift
  Tests/PackageLoadingTests/ManifestLoaderSQLiteCacheTests.swift
Labels: 5.5

#3451 [5.5] improve location of config directory
  Sources/Basics/FileSystem+Extensions.swift
  Sources/Commands/Options.swift
  Sources/Commands/SwiftTool.swift
  Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift
  Sources/PackageCollections/Storage/FilePackageCollectionsSourcesStorage.swift
Labels: 5.5

#3455 [5.5] Make the struct in the default template public
  Sources/Workspace/InitPackage.swift
Labels: 5.5

#3460 [5.5] BuildSettingCondition should offer a Mac Catalyst condition (amend)
  Sources/PackageLoading/PackageBuilder.swift
Labels: 5.5

#3457 [5.5] Fix SQL syntax error
  Sources/Basics/SQLiteBackedCache.swift
Labels: 5.5

#3462 [5.5][Collections] Fix auth token lookup (#3461)
  Sources/PackageCollections/Providers/GitHubPackageMetadataProvider.swift
  Tests/PackageCollectionsTests/GitHubPackageMetadataProviderTests.swift
Labels: 5.5

#3458 [5.5][Collections] Auth tokens need to be mutable (#3443)
  Sources/PackageCollections/PackageCollections+Configuration.swift
  Sources/PackageCollections/PackageCollections.swift
  Sources/PackageCollections/Providers/GitHubPackageMetadataProvider.swift
  Tests/PackageCollectionsTests/GitHubPackageMetadataProviderTests.swift
  Tests/PackageCollectionsTests/PackageCollectionsTests.swift
Labels: 5.5
