Repository swiftlang/swift-package-manager, pull requests merged in 2021-12, with the labels that each got.

#3895 Thread sanitize package loading tests
  Sources/Basics/ConcurrencyHelpers.swift
  Tests/PackageLoadingTests/PDLoadingTests.swift
  Tests/PackageLoadingTests/PD_5_6_LoadingTests.swift
Labels: ready

#3900 Don't use scoped imports when building with library evolution enabled
  Sources/PackageLoading/ContextModel.swift
Labels: ready

#3902 clear warnings
  Sources/Basics/Observability.swift
  Sources/Commands/SwiftTestTool.swift
  Sources/PackageCollectionsSigning/Certificate/CertificatePolicy.swift
  Tests/PackageGraphTests/PubgrubTests.swift
Labels: ready

#3903 move PkgConfig frmo TSC into SwiftPM
  Package.swift
  Sources/PackageLoading/CMakeLists.txt
  Sources/PackageLoading/PkgConfig.swift
  Sources/PackageLoading/Target+PkgConfig.swift
  Tests/PackageLoadingTests/PkgConfigParserTests.swift
  Tests/PackageLoadingTests/PkgConfigTests.swift
  Tests/PackageLoadingTests/pkgconfigInputs/deps_variable.pc
  Tests/PackageLoadingTests/pkgconfigInputs/empty_cflags.pc
  Tests/PackageLoadingTests/pkgconfigInputs/escaped_spaces.pc
  Tests/PackageLoadingTests/pkgconfigInputs/failure_case.pc
  Tests/PackageLoadingTests/pkgconfigInputs/freetype2.pc
  Tests/PackageLoadingTests/pkgconfigInputs/gobject-2.0.pc
  Tests/PackageLoadingTests/pkgconfigInputs/gtk+-3.0.pc
  Tests/PackageLoadingTests/pkgconfigInputs/harfbuzz.pc
  Tests/PackageLoadingTests/pkgconfigInputs/libffi.pc
  Tests/PackageLoadingTests/pkgconfigInputs/quotes_failure.pc
Labels: ready

#3899 Build local and remote tools depended on by command plugins before running the plugins
  Sources/Commands/SwiftPackageTool.swift
  Tests/CommandsTests/PackageToolTests.swift
Labels: ready

#3897 Fix a bug in the plugin context where the top-level package was not always the root package
  Sources/SPMBuildCore/PluginInvocation.swift
  Tests/FunctionalTests/PluginTests.swift
Labels: ready

#3909 adjust precomputation resolution to registry based dependencies
  Sources/Workspace/ResolverPrecomputationProvider.swift
  Sources/Workspace/Workspace.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: ready

#3910 fix error handling in BuildOperation::buildPackageStructure
  Sources/Build/BuildOperation.swift
Labels: ready

#3911 add a test for (simple) mixed graph
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: ready

#3913 Provide better and more detailed error messages when things go wrong compiling and running plugins
  Sources/Workspace/DefaultPluginScriptRunner.swift
Labels: ready

#3918 Make sure that NSTemporaryDirectory() is included in the sandbox when `writableTemporaryDirectory` is set
  Sources/Basics/Sandbox.swift
Labels: ready

#3914 add more registry tests
  Sources/PackageRegistry/RegistryClient.swift
  Sources/SPMTestSupport/MockPackage.swift
  Sources/SPMTestSupport/MockRegistry.swift
  Sources/SPMTestSupport/MockWorkspace.swift
  Tests/PackageRegistryTests/RegistryClientTests.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: ready

#3915 Only recompile plugin scripts to executables when needed
  Sources/Workspace/DefaultPluginScriptRunner.swift
  Tests/FunctionalTests/PluginTests.swift
  Tests/SPMBuildCoreTests/PluginInvocationTests.swift
Labels: ready

#3916 Initial version of the `--list` option for command plugins
  Sources/Commands/SwiftPackageTool.swift
  Tests/CommandsTests/PackageToolTests.swift
Labels: ready

#3921 [5.6] Make sure that NSTemporaryDirectory() is included when `writableTemporaryDirectory` is set.
  Sources/Basics/Sandbox.swift
Labels: ready, 5.6

#3924 [5.6] Only recompile plugin scripts to executables when needed (#3915)
  Sources/Workspace/DefaultPluginScriptRunner.swift
  Tests/FunctionalTests/PluginTests.swift
  Tests/SPMBuildCoreTests/PluginInvocationTests.swift
Labels: ready, 5.6

#3925 [5.6] Implement the `--list` option for command plugins. (#3916)
  Sources/Commands/SwiftPackageTool.swift
  Tests/CommandsTests/PackageToolTests.swift
Labels: ready, 5.6

#3923 [5.6] add more registry tests (#3914)
  Sources/PackageRegistry/RegistryClient.swift
  Sources/SPMTestSupport/MockPackage.swift
  Sources/SPMTestSupport/MockRegistry.swift
  Sources/SPMTestSupport/MockWorkspace.swift
  Tests/PackageRegistryTests/RegistryClientTests.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: 5.6

#3920 Simplify the adding of temporary directories to the sandbox profile when strictness is 'writableTemporaryDirectory'
  Sources/Basics/Sandbox.swift
Labels: ready

#3922 re-introduce Package.Dependency.Requirement::upToNextMajor and ::upToNextMinor
  CHANGELOG.md
  Sources/PackageDescription/PackageDependency.swift
  Sources/PackageDescription/PackageRequirement.swift
Labels: ready

#3926 [5.6] re-introduce Package.Dependency.Requirement::upToNextMajor and ::upToNextMinor
  CHANGELOG.md
  Sources/PackageDescription/PackageDependency.swift
  Sources/PackageDescription/PackageRequirement.swift
Labels: 5.6

#3927 [5.6] Implement TOFU for package downloads
  Package.swift
  Sources/Basics/FileSystem+Extensions.swift
  Sources/Commands/CMakeLists.txt
  Sources/Commands/Options.swift
  Sources/Commands/SwiftTool.swift
  Sources/PackageFingerprint/FilePackageFingerprintStorage.swift
  Sources/PackageFingerprint/Model.swift
  Sources/PackageFingerprint/PackageFingerprintStorage.swift
  Sources/PackageRegistry/CMakeLists.txt
  Sources/PackageRegistry/RegistryClient.swift
  Sources/SPMTestSupport/InMemoryGitRepository.swift
  Sources/SPMTestSupport/MockPackage.swift
  Sources/SPMTestSupport/MockPackageFingerprintStorage.swift
  Sources/SPMTestSupport/MockRegistry.swift
  Sources/SPMTestSupport/MockWorkspace.swift
  Sources/Workspace/CMakeLists.txt
  Sources/Workspace/SourceControlPackageContainer.swift
  Sources/Workspace/Workspace.swift
  Sources/Workspace/WorkspaceConfiguration.swift
  Tests/PackageRegistryTests/RegistryClientTests.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: 5.6

#3929 optimize manifest requests for registry based depedendcies
  Sources/PackageLoading/ToolsVersionLoader.swift
  Sources/PackageRegistry/RegistryClient.swift
  Sources/Workspace/RegistryPackageContainer.swift
  Sources/Workspace/Workspace.swift
  Tests/PackageRegistryTests/RegistryClientTests.swift
  Tests/WorkspaceTests/RegistryPackageContainerTests.swift
  Tests/WorkspaceTests/SourceControlPackageContainerTests.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: ready

#3935 [5.6] Optionally use a per-package filesystem for `PackageBuilder`
  Sources/PackageGraph/GraphLoadingNode.swift
  Sources/PackageGraph/PackageContainer.swift
  Sources/PackageGraph/PackageGraph+Loading.swift
  Sources/SPMTestSupport/MockPackageContainer.swift
  Sources/SPMTestSupport/MockWorkspace.swift
  Sources/SPMTestSupport/misc.swift
  Sources/Workspace/Diagnostics.swift
  Sources/Workspace/FileSystemPackageContainer.swift
  Sources/Workspace/ManagedDependency.swift
  Sources/Workspace/ResolverPrecomputationProvider.swift
  Sources/Workspace/Workspace.swift
  Sources/Workspace/WorkspaceState.swift
  Tests/PackageGraphPerformanceTests/PackageGraphPerfTests.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: 5.6

#3881 begin to integrate SwiftSystem
  CMakeLists.txt
  CONTRIBUTING.md
  Package.swift
  Sources/Basics/CMakeLists.txt
  Sources/Basics/FileSystem+Extensions.swift
  Utilities/bootstrap
Labels: ready

#3894 Load manifests asynchronously
  Sources/PackageLoading/ManifestLoader.swift
Labels: ready

#3931 preserve old formatting of Package.resolved in tools-version < 5.6
  Sources/PackageGraph/PinsStore.swift
Labels: ready

#3934 [5.6] optimize manifest requests for registry based dependencies (#3929)
  Sources/PackageLoading/ToolsVersionLoader.swift
  Sources/PackageRegistry/RegistryClient.swift
  Sources/Workspace/RegistryPackageContainer.swift
  Sources/Workspace/Workspace.swift
  Tests/PackageRegistryTests/RegistryClientTests.swift
  Tests/WorkspaceTests/RegistryPackageContainerTests.swift
  Tests/WorkspaceTests/SourceControlPackageContainerTests.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: 5.6

#3939 [5.6] preserve old formatting of Package.resolved in tools-version < 5.6 (#3931)
  Sources/PackageGraph/PinsStore.swift
Labels: 5.6

#3930 [5.6] Cherry-pick TOFU changes from main branch
  Sources/Commands/SwiftTool.swift
  Sources/PackageFingerprint/Model.swift
  Sources/PackageFingerprint/PackageFingerprintStorage.swift
  Sources/PackageRegistry/RegistryClient.swift
  Sources/Workspace/SourceControlPackageContainer.swift
  Sources/Workspace/Workspace.swift
  Sources/Workspace/WorkspaceConfiguration.swift
  Tests/WorkspaceTests/RegistryPackageContainerTests.swift
Labels: 5.6

#3946 Actually remove the `--output` option from `swift package plugin`
  Sources/Commands/SwiftPackageTool.swift
Labels: ready

#3942 use idiomatic location for security directory and update location of configuration directory
  Sources/Basics/FileSystem+Extensions.swift
  Sources/Commands/Options.swift
  Sources/Commands/SwiftTool.swift
  Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift
  Sources/PackageCollections/Storage/FilePackageCollectionsSourcesStorage.swift
  Sources/SPMTestSupport/MockWorkspace.swift
  Sources/Workspace/WorkspaceConfiguration.swift
  Tests/FunctionalTests/MiscellaneousTests.swift
  Utilities/Docker/docker-compose.2004.55.yaml
  Utilities/Docker/docker-compose.yaml
Labels: ready

#3949 [5.6] fix a warning on linux (#3947)
  Sources/PackageLoading/PackageBuilder.swift
  Tests/PackageGraphTests/PubgrubTests.swift
  Tests/PackageLoadingTests/PackageBuilderTests.swift
Labels: 5.6

#3955 move manifest validation that requires source control to Workspace
  Fixtures/Miscellaneous/InvalidRefs/InvalidBranch/Package.swift
  Fixtures/Miscellaneous/InvalidRefs/InvalidRevision/Package.swift
  Package.swift
  Sources/PackageGraph/PackageGraphRoot.swift
  Sources/PackageLoading/ManifestJSONParser.swift
  Sources/SPMTestSupport/InMemoryGitRepository.swift
  Sources/SourceControl/GitRepository.swift
  Sources/SourceControl/Repository.swift
  Sources/SourceControl/RepositoryManager.swift
  Sources/Workspace/Workspace.swift
  Tests/FunctionalTests/MiscellaneousTests.swift
  Tests/SourceControlTests/RepositoryManagerTests.swift
  Tests/WorkspaceTests/SourceControlPackageContainerTests.swift
Labels: ready

#3954 reduce concurrent manifest loading test contention
  Tests/PackageLoadingTests/PD_4_2_LoadingTests.swift
Labels: ready

#3957 Errors thrown at top level of plugin should be reported as diagnostics
  Sources/PackagePlugin/Plugin.swift
  Sources/Workspace/DefaultPluginScriptRunner.swift
  Tests/FunctionalTests/PluginTests.swift
Labels: ready

#3958 [5.6] Errors thrown at top level of plugin should be reported as diagnostics
  Sources/PackagePlugin/Plugin.swift
  Sources/Workspace/DefaultPluginScriptRunner.swift
  Tests/FunctionalTests/PluginTests.swift
Labels: ready, 5.6

#3956 [5.6] move manifest validation that requires source control to Workspace (#3955)
  Fixtures/Miscellaneous/InvalidRefs/InvalidBranch/Package.swift
  Fixtures/Miscellaneous/InvalidRefs/InvalidRevision/Package.swift
  Package.swift
  Sources/PackageGraph/PackageGraphRoot.swift
  Sources/PackageLoading/ManifestJSONParser.swift
  Sources/SPMTestSupport/InMemoryGitRepository.swift
  Sources/SourceControl/GitRepository.swift
  Sources/SourceControl/Repository.swift
  Sources/SourceControl/RepositoryManager.swift
  Sources/Workspace/Workspace.swift
  Tests/FunctionalTests/MiscellaneousTests.swift
  Tests/SourceControlTests/RepositoryManagerTests.swift
  Tests/WorkspaceTests/SourceControlPackageContainerTests.swift
Labels: ready, 5.6

#3963 adjust to TSC SHA256 API changes
  Sources/Basics/ByteString+Extensions.swift
  Sources/Workspace/Workspace.swift
Labels: ready

#3940 [5.6] Load manifests asynchronously [cherry pick]
  Sources/PackageLoading/ManifestLoader.swift
  Tests/PackageLoadingTests/PD_4_2_LoadingTests.swift
Labels: 5.6

#3962 adjust FileSystem implementations to TSC API changes
  Sources/Basics/VirtualFileSystem.swift
  Sources/Commands/SwiftTool.swift
  Sources/SPMTestSupport/InMemoryGitRepository.swift
  Sources/SourceControl/GitRepository.swift
  Tests/BasicsTests/URLSessionHTTPClientTests.swift
Labels: ready

#3964 Fix an ordering issue of a print statement and a diagnostic arriving right at the exit of a plugin
  Sources/Workspace/DefaultPluginScriptRunner.swift
  Tests/FunctionalTests/PluginTests.swift
Labels: ready

#3961 [5.6] add more information about resolution (#3960)
  Sources/Workspace/Workspace.swift
Labels: ready, 5.6

#3966 [5.6] Fix an ordering issue of a print statement and a diagnostic arriving right at the exit of a plugin
  Sources/Workspace/DefaultPluginScriptRunner.swift
  Tests/FunctionalTests/PluginTests.swift
Labels: ready, 5.6

#3965 [5.6] adjust FileSystem implementations to TSC API changes (#3962)
  Sources/Basics/VirtualFileSystem.swift
  Sources/Commands/SwiftTool.swift
  Sources/SPMTestSupport/InMemoryGitRepository.swift
  Sources/SourceControl/GitRepository.swift
  Tests/BasicsTests/URLSessionHTTPClientTests.swift
Labels: ready, 5.6
