Repository swiftlang/swift-package-manager, pull requests merged in 2021-06, with the labels that each got.

#3523 [5.5][Collections] testPopulateTargetTrie sometimes gets stuck
  Sources/PackageCollections/Storage/SQLitePackageCollectionsStorage.swift
  Tests/PackageCollectionsTests/PackageCollectionsStorageTests.swift
Labels: 5.5

#3531 [5.5][Collections] Fix useSearchIndices race
  Sources/PackageCollections/Storage/SQLitePackageCollectionsStorage.swift
Labels: 5.5

#3535 [5.5][Collections] PackageCollectionsTests.testUpdateAuthTokens sometimes causes signal 11
  Sources/PackageCollections/Storage/SQLitePackageCollectionsStorage.swift
  Tests/PackageCollectionsTests/PackageCollectionsTests.swift
  Tests/PackageCollectionsTests/Utility.swift
Labels: 5.5

#3525 [5.5] Check what compiler flags are available (#3398)
  Package.swift
  Sources/Build/BuildPlan.swift
  Sources/SPMTestSupport/Resources.swift
Labels: 5.5

#3524 [5.5] Revert "Use implementation-only imports (#3404)"
  Sources/PackageDescription/PackageDescription.swift
  Sources/PackageDescription/Target.swift
Labels: 5.5

#3540 Revert the bootstrap changes to copy the SwiftPM-built universal PackageDescription and PackagePlugin libraries
  Utilities/bootstrap
Labels: ready

#3542 Fix pluralization of 'package-collection refresh' text
  Sources/Commands/SwiftPackageCollectionsTool.swift
Labels: ready

#3492 [5.5] Unify the two versions of PackageDescription into a single one using availability annotations instead of compile conditionals
  Package.swift
  Sources/PackageDescription/CMakeLists.txt
  Sources/PackageDescription/LanguageStandardSettings.swift
  Sources/PackageDescription/PackageDependency.swift
  Sources/PackageDescription/PackageDescription.swift
  Sources/PackageDescription/PackageRequirement.swift
  Sources/PackageDescription/Target.swift
  Sources/PackageLoading/ManifestLoader.swift
  Sources/PackagePlugin/CMakeLists.txt
  Sources/Workspace/DefaultPluginScriptRunner.swift
  Sources/Xcodeproj/pbxproj.swift
  Tests/PackageLoadingTests/PD4_2LoadingTests.swift
  Utilities/bootstrap
Labels: 5.5, ready

#3544 [5.5][Collections] 'describe' package matching is too loose
  Sources/PackageCollections/PackageCollections+Storage.swift
  Sources/PackageCollections/PackageCollections.swift
  Sources/PackageCollections/Storage/PackageCollectionsStorage.swift
  Sources/PackageCollections/Storage/SQLitePackageCollectionsStorage.swift
  Sources/PackageCollectionsModel/Formats/v1.md
Labels: 5.5

#3550 [5.5] Remove a remaining stray reference to PACKAGE_DESCRIPTION_4
  Sources/PackageDescription/Target.swift
Labels: 5.5, ready

#3555 [5.5][Collections] Support multiple cert pinning configs per domain
  Sources/PackageCollections/PackageCollections+CertificatePolicy.swift
  Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift
  Sources/PackageCollectionsSigning/Certificate/CertificatePolicy.swift
  Tests/PackageCollectionsTests/JSONPackageCollectionProviderTests.swift
  Tests/PackageCollectionsTests/PackageCollectionSourceCertificatePolicyTests.swift
  Tests/PackageCollectionsTests/Utility.swift
Labels: 5.5

#3560 Make the lookup of the PackageDescription dylib fall back on the versioned location if needed
  Sources/PackageLoading/ManifestLoader.swift
Labels: ready

#3556 [SR-14782] `swift package describe` is omitting product dependencies from per-target output
  Sources/Commands/Describe.swift
  Tests/CommandsTests/PackageToolTests.swift
Labels: ready

#3568 [5.5][Collections] listCollections always returns all configured collections
  Sources/PackageCollections/PackageCollections.swift
  Tests/PackageCollectionsTests/PackageCollectionsTests.swift
Labels: 5.5

#3567 [5.5] Make the lookup of the PackageDescription dylib fall back on the versioned location if needed
  Sources/PackageLoading/ManifestLoader.swift
Labels: 5.5, ready

#3558 [5.5] Change symlink error to warning
  Sources/Build/BuildOperation.swift
Labels: 5.5

#3563 [5.5] Avoid calling `supportedFrontendFlags` on Windows
  Sources/Build/BuildPlan.swift
Labels: 5.5

#3570 [5.5][Collections] Add listPackages API
  Sources/PackageCollections/API.swift
  Sources/PackageCollections/PackageCollections.swift
  Tests/PackageCollectionsTests/PackageCollectionsTests.swift
Labels: 5.5

#3518 [5.5] Avoid warnings when using SDKs without a Concurrency module
  Sources/Commands/SwiftTool.swift
Labels: 5.5
