Repository swiftlang/swift-package-manager, pull requests merged in 2021-10, with the labels that each got.

#3775 `ProductFilter` type is not `Decodable` for the `everything` case
  Sources/PackageModel/Product.swift
  Tests/PackageModelTests/PackageModelTests.swift
Labels: ready

#3776 [5.5] `ProductFilter` type is not `Decodable` for the `everything` case (#3775)
  Sources/PackageModel/Product.swift
  Tests/PackageModelTests/PackageModelTests.swift
Labels: ready, 5.5

#3778 fix workspace to notify delegate on any result of manifest loading
  Sources/SPMTestSupport/MockWorkspace.swift
  Sources/Workspace/Workspace.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: ready

#3587 Add development-time assertions to catch errors where two llbuild commands are created with the same name
  Sources/LLBuildManifest/BuildManifest.swift
Labels: wip

#3783 [5.5] Fix the default location for diagnostics resulting from package manifest loading
  Sources/Workspace/Workspace.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: ready, 5.5

#3782 Allow libSwiftPM clients additional flexibility in the manifest source generation
  Sources/PackageModel/ManifestSourceGeneration.swift
  Tests/WorkspaceTests/ManifestSourceGenerationTests.swift
Labels: ready

#3777 remove global observability scope
  Examples/package-info/Sources/package-info/main.swift
  Sources/Basics/HTPClient+URLSession.swift
  Sources/Basics/HTTPClient.swift
  Sources/Basics/Observability.swift
  Sources/Basics/SQLiteBackedCache.swift
  Sources/Commands/APIDigester.swift
  Sources/Commands/Snippets/CardStack.swift
  Sources/Commands/SwiftBuildTool.swift
  Sources/Commands/SwiftPackageCollectionsTool.swift
  Sources/Commands/SwiftPackageTool.swift
  Sources/Commands/SwiftRunTool.swift
  Sources/Commands/SwiftTestTool.swift
  Sources/Commands/SwiftTool.swift
  Sources/PackageCollections/PackageCollections.swift
  Sources/PackageCollections/Providers/GitHubPackageMetadataProvider.swift
  Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift
  Sources/PackageCollectionsSigning/Certificate/CertificatePolicy.swift
  Sources/PackageCollectionsSigning/PackageCollectionSigning.swift
  Sources/PackageGraph/PackageGraph+Loading.swift
  Sources/PackageLoading/Diagnostics.swift
  Sources/PackageLoading/ManifestLoader.swift
  Sources/PackageLoading/PackageBuilder.swift
  Sources/PackageModel/Package.swift
  Sources/SPMTestSupport/MockWorkspace.swift
  Sources/SPMTestSupport/Observability.swift
  Sources/SPMTestSupport/misc.swift
  Sources/Workspace/Workspace.swift
  Tests/BasicsTests/ObservabilitySystemTests.swift
  Tests/BuildTests/BuildPlanTests.swift
  Tests/CommandsTests/MultiRootSupportTests.swift
  Tests/CommandsTests/PackageToolTests.swift
  Tests/PackageCollectionsSigningTests/CertificatePolicyTests.swift
  Tests/PackageCollectionsSigningTests/PackageCollectionSigningTest.swift
  Tests/PackageCollectionsSigningTests/Utilities.swift
  Tests/PackageCollectionsTests/GitHubPackageMetadataProviderTests.swift
  Tests/PackageCollectionsTests/JSONPackageCollectionProviderTests.swift
  Tests/PackageCollectionsTests/PackageCollectionsTests.swift
  Tests/PackageCollectionsTests/Utility.swift
  Tests/PackageGraphPerformanceTests/PackageGraphPerfTests.swift
  Tests/PackageGraphTests/PackageGraphTests.swift
  Tests/PackageLoadingTests/ModuleMapGenerationTests.swift
  Tests/PackageLoadingTests/PDLoadingTests.swift
  Tests/PackageLoadingTests/PD_4_0_LoadingTests.swift
  Tests/PackageLoadingTests/PD_4_2_LoadingTests.swift
  Tests/PackageLoadingTests/PD_5_0_LoadingTests.swift
  Tests/PackageLoadingTests/PackageBuilderTests.swift
  Tests/PackageLoadingTests/PkgConfigTests.swift
  Tests/PackageLoadingTests/TargetSourcesBuilderTests.swift
  Tests/SPMBuildCoreTests/PluginInvocationTests.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
  Tests/XCBuildSupportTests/PIFBuilderTests.swift
  Tests/XcodeprojTests/GenerateXcodeprojTests.swift
  Tests/XcodeprojTests/PackageGraphTests.swift
Labels: ready

#3779 migrate SwiftTestTool to Observability APIs
  Sources/Commands/SwiftTestTool.swift
  Tests/CommandsTests/TestToolTests.swift
Labels: ready

#3773 fix an issue where user defined DYLD_LIBRARY_PATH gets ignored
  Sources/Basics/CMakeLists.txt
  Sources/Basics/EnvironmentVariables.swift
  Sources/Build/SPMSwiftDriverExecutor.swift
  Sources/Commands/SwiftTestTool.swift
  Sources/LLBuildManifest/BuildManifest.swift
  Sources/LLBuildManifest/Tools.swift
  Sources/PackageLoading/ManifestLoader.swift
  Sources/PackageModel/ToolchainConfiguration.swift
  Sources/SPMTestSupport/XCTAssertHelpers.swift
  Sources/SPMTestSupport/misc.swift
  Sources/SourceControl/GitRepository.swift
  Sources/Workspace/Destination.swift
  Sources/Workspace/UserToolchain.swift
  Tests/BasicsTests/EnvironmentVariablesTests.swift
  Tests/CommandsTests/APIDiffTests.swift
  Tests/CommandsTests/PackageRegistryToolTests.swift
  Tests/CommandsTests/PackageToolTests.swift
  Tests/XcodeprojTests/FunctionalTests.swift
Labels: ready

#3750 Additional refactoring of ManagedDependencies
  Sources/Workspace/ManagedDependency.swift
  Sources/Workspace/Workspace.swift
  Sources/Workspace/WorkspaceConfiguration.swift
  Sources/Workspace/WorkspaceState.swift
Labels: ready

#3786 [5.5] Allow libSwiftPM clients additional flexibility in the manifest source generation (#3782
  Sources/PackageModel/ManifestSourceGeneration.swift
  Tests/WorkspaceTests/ManifestSourceGenerationTests.swift
Labels: ready, 5.5

#3756 convert the build modules to the new diagnostics apis
  Sources/Build/BuildOperation.swift
  Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
  Sources/Build/BuildPlan.swift
  Sources/Build/LLBuildManifestBuilder.swift
  Sources/Commands/APIDigester.swift
  Sources/Commands/SwiftBuildTool.swift
  Sources/Commands/SwiftPackageTool.swift
  Sources/Commands/SwiftRunTool.swift
  Sources/Commands/SwiftTool.swift
  Sources/Commands/WatchmanHelper.swift
  Sources/PackageGraph/PackageGraph+Loading.swift
  Sources/PackageLoading/PackageBuilder.swift
  Sources/PackageLoading/Target+PkgConfig.swift
  Sources/PackageLoading/TargetSourcesBuilder.swift
  Sources/XCBuildSupport/PIFBuilder.swift
  Sources/XCBuildSupport/XCBuildDelegate.swift
  Sources/XCBuildSupport/XcodeBuildSystem.swift
  Sources/Xcodeproj/generate.swift
  Sources/Xcodeproj/pbxproj.swift
  Tests/BuildTests/BuildPlanTests.swift
  Tests/CommandsTests/APIDiffTests.swift
  Tests/CommandsTests/PackageToolTests.swift
  Tests/PackageGraphTests/PackageGraphTests.swift
  Tests/PackageLoadingTests/PkgConfigTests.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
  Tests/XCBuildSupportTests/PIFBuilderTests.swift
  Tests/XcodeprojTests/GenerateXcodeprojTests.swift
  Tests/XcodeprojTests/PackageGraphTests.swift
Labels: ready

#3791 re-organize docs
  CONTRIBUTING.md
  Documentation/Design/EvolutionIdeas.md
  Documentation/Design/PackageManagerCommunityProposal.md
  Documentation/Design/README.md
  Documentation/Design/SwiftBasedManifestFormat.md
  Documentation/Internals/README.md
  Documentation/README.md
  Documentation/Resources.md
  Documentation/Usage.md
  README.md
Labels: ready

#3797 cleanup use of package location where we can avoid it
  Sources/PackageCollections/PackageCollections.swift
  Sources/PackageModel/PackageReference.swift
  Sources/PackageRegistry/RegistryManager.swift
  Sources/SPMTestSupport/MockWorkspace.swift
  Sources/SourceControl/GitRepository.swift
  Sources/SourceControl/Repository.swift
  Sources/SourceControl/RepositoryManager.swift
  Sources/Workspace/ManagedDependency.swift
  Sources/Workspace/SourceControlPackageContainer.swift
  Sources/Workspace/Workspace.swift
  Sources/Workspace/WorkspaceState.swift
  Tests/SourceControlTests/RepositoryManagerTests.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: ready

#3803 add backwards compatibility for workspace-state.json v4
  Sources/Workspace/WorkspaceState.swift
  Tests/WorkspaceTests/WorkspaceStateTests.swift
Labels: ready

#3814 improve treatment of directories with extensions
  Sources/PackageLoading/TargetSourcesBuilder.swift
  Tests/PackageLoadingTests/TargetSourcesBuilderTests.swift
Labels: ready

#3816 remove the use of ObjectIdentifierProtocol
  Sources/PackageGraph/PackageGraph+Loading.swift
  Sources/PackageGraph/ResolvedPackage.swift
  Sources/PackageGraph/ResolvedProduct.swift
  Sources/PackageGraph/ResolvedTarget.swift
  Sources/PackageModel/Manifest.swift
  Sources/PackageModel/Package.swift
  Sources/PackageModel/Product.swift
  Sources/PackageModel/Target.swift
  Sources/XCBuildSupport/PIF.swift
  Tests/PackageLoadingTests/PackageBuilderTests.swift
Labels: ready

#3817 fix regression in test output
  Sources/Commands/SwiftTestTool.swift
Labels: ready
