Repository swiftlang/swift-package-manager, pull requests merged in 2021-02, with the labels that each got.

#3233 fix potential race in PackageCollections.refreshCollections
  Sources/Basics/ConcurrencyHelpers.swift
  Sources/PackageCollections/PackageCollections.swift
Labels: 5.4

#3202 Add swift-crypto dependency
  CMakeLists.txt
  Documentation/Contributing.md
  Package.swift
  Sources/PackageCollections/CMakeLists.txt
  Sources/PackageCollections/Signing/PackageCollectionSignature.swift
  Utilities/bootstrap
Labels: next

#3261 [5.4] Prevent manifest load errors from causing SwiftPM to display "fatalError" in CLI
  Sources/Workspace/Workspace.swift
Labels: 5.4

#3258 [5.4] Duplicate error message on package resolve
  Sources/Commands/SwiftPackageTool.swift
Labels: 5.4

#3278 The "duplicate target dependency" warning should say what package it's coming from
  Sources/PackageLoading/Diagnostics.swift
  Sources/PackageLoading/PackageBuilder.swift
  Tests/PackageLoadingTests/PackageBuilderTests.swift
Labels: ready

#3281 [Collections] Missing Content-Length header
  Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift
Labels: ready

#3273 [Collections] Fetch releases from GitHub
  Fixtures/Collections/GitHub/releases.json
  Fixtures/Collections/GitHub/tags.json
  Sources/PackageCollections/PackageCollections.swift
  Sources/PackageCollections/Providers/GitHubPackageMetadataProvider.swift
  Sources/PackageCollections/Providers/PackageMetadataProvider.swift
  Tests/PackageCollectionsTests/GitHubPackageMetadataProviderTests.swift
  Tests/PackageCollectionsTests/PackageCollectionsTests.swift
  Tests/PackageCollectionsTests/Utility.swift
Labels: ready

#3283 reduce use of fatalError
  Sources/SourceControl/GitRepository.swift
  Sources/SourceControl/Repository.swift
Labels: ready

#3259 [Collections] Signing (apple, 1): certificate and key types
  Fixtures/Collections/Signing/Test_ec.cer
  Fixtures/Collections/Signing/Test_rsa.cer
  Package.swift
  Sources/CMakeLists.txt
  Sources/PackageCollections/CMakeLists.txt
  Sources/PackageCollectionsSigning/CMakeLists.txt
  Sources/PackageCollectionsSigning/Certificate/Certificate.swift
  Sources/PackageCollectionsSigning/Key/ASN1/ASN1.swift
  Sources/PackageCollectionsSigning/Key/ASN1/ASN1Error.swift
  Sources/PackageCollectionsSigning/Key/ASN1/PEMDocument.swift
  Sources/PackageCollectionsSigning/Key/ASN1/SEC1PrivateKey.swift
  Sources/PackageCollectionsSigning/Key/ASN1/SubjectPublicKeyInfo.swift
  Sources/PackageCollectionsSigning/Key/ASN1/Types/ASN1BitString.swift
  Sources/PackageCollectionsSigning/Key/ASN1/Types/ASN1Identifier.swift
  Sources/PackageCollectionsSigning/Key/ASN1/Types/ASN1Integer.swift
  Sources/PackageCollectionsSigning/Key/ASN1/Types/ASN1ObjectIdentifier.swift
  Sources/PackageCollectionsSigning/Key/ASN1/Types/ASN1OctetString.swift
  Sources/PackageCollectionsSigning/Key/Key+EC.swift
  Sources/PackageCollectionsSigning/Key/Key+RSA.swift
  Sources/PackageCollectionsSigning/Key/Key.swift
  Sources/PackageCollectionsSigning/Utilities/Utilities.swift
  Tests/PackageCollectionsSigningTests/CertificateTests.swift
  Tests/PackageCollectionsSigningTests/KeyTests+EC.swift
  Tests/PackageCollectionsSigningTests/KeyTests+RSA.swift
  Tests/PackageCollectionsSigningTests/Utilities.swift
Labels: ready

#3264 [Collections] Signing (apple, 2): signed collections
  Fixtures/Collections/Signing/TestIntermediateCA_ec.cer
  Fixtures/Collections/Signing/TestIntermediateCA_rsa.cer
  Fixtures/Collections/Signing/TestRootCA_rsa.cer
  Fixtures/Collections/Signing/Test_ec_key.pem
  Fixtures/Collections/Signing/Test_rsa_key.pem
  Package.swift
  Sources/PackageCollectionsSigning/CMakeLists.txt
  Sources/PackageCollectionsSigning/Certificate/CertificatePolicy.swift
  Sources/PackageCollectionsSigning/Key/Key+RSA.swift
  Sources/PackageCollectionsSigning/Key/Key.swift
  Sources/PackageCollectionsSigning/PackageCollectionSigning.swift
  Sources/PackageCollectionsSigning/Signing/Signature.swift
  Sources/PackageCollectionsSigning/Signing/Signing+ECKey.swift
  Sources/PackageCollectionsSigning/Signing/Signing+RSAKey.swift
  Sources/PackageCollectionsSigning/Signing/Signing.swift
  Sources/PackageCollectionsSigning/Utilities/Base64URL.swift
  Sources/PackageCollectionsSigning/Utilities/Utilities.swift
  Tests/PackageCollectionsSigningTests/PackageCollectionSigningTest.swift
  Tests/PackageCollectionsSigningTests/SignatureTests.swift
  Tests/PackageCollectionsSigningTests/SigningTests+ECKey.swift
  Tests/PackageCollectionsSigningTests/SigningTests+RSAKey.swift
  Tests/PackageCollectionsSigningTests/Utilities.swift
Labels: ready

#3284 Don't trap on empty resource lists
  Sources/PackageLoading/PackageDescription4Loader.swift
Labels: ready

#3236 Improved the error message when using a local package dependency as 'url:' instead of 'path:'
  Fixtures/Miscellaneous/LocalPackageAsURL/Bar/Package.swift
  Fixtures/Miscellaneous/LocalPackageAsURL/Bar/main.swift
  Fixtures/Miscellaneous/LocalPackageAsURL/Foo/Foo.swift
  Fixtures/Miscellaneous/LocalPackageAsURL/Foo/Package.swift
  Package.swift
  Sources/PackageLoading/PackageDescription4Loader.swift
  Sources/SPMTestSupport/misc.swift
  Sources/SourceControl/GitRepository.swift
  Tests/FunctionalTests/MiscellaneousTests.swift
Labels: ready

#3285 Allow unit tests to enable feature flag controlling extension feature
  Sources/PackageGraph/PackageGraph+Loading.swift
  Sources/PackageLoading/PackageBuilder.swift
  Sources/SPMTestSupport/misc.swift
Labels: ready

#3269 [Collections] Signing (apple, 3): certificate validations
  Package.swift
  Sources/PackageCollectionsSigning/CMakeLists.txt
  Sources/PackageCollectionsSigning/Certificate/CertificatePolicy.swift
  Sources/PackageCollectionsSigning/PackageCollectionSigning.swift
  Tests/PackageCollectionsSigningTests/CertificatePolicyTests.swift
  Tests/PackageCollectionsSigningTests/PackageCollectionSigningTest.swift
  Tests/PackageCollectionsSigningTests/Utilities.swift
Labels: ready

#3291 [Collections] Add skip signature check option to 'add'
  Sources/Commands/SwiftPackageCollectionsTool.swift
  Sources/PackageCollections/API.swift
  Sources/PackageCollections/Model/Collection.swift
  Sources/PackageCollections/PackageCollections.swift
  Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift
  Sources/PackageCollections/Storage/FilePackageCollectionsSourcesStorage.swift
  Tests/PackageCollectionsTests/JSONPackageCollectionProviderTests.swift
  Tests/PackageCollectionsTests/PackageCollectionsSourcesStorageTest.swift
  Tests/PackageCollectionsTests/PackageCollectionsTests.swift
  Tests/PackageCollectionsTests/Utility.swift
Labels: ready

#3287 Add PackageExtension library and incorporate build tool commands into native build system
  Fixtures/Miscellaneous/Extensions/MySourceGenExtension/Package.swift
  Fixtures/Miscellaneous/Extensions/MySourceGenExtension/Sources/MyLocalTool/Foo.dat
  Fixtures/Miscellaneous/Extensions/MySourceGenExtension/Sources/MyLocalTool/main.swift
  Fixtures/Miscellaneous/Extensions/MySourceGenExtension/Sources/MySourceGenExt/extension.swift
  Fixtures/Miscellaneous/Extensions/MySourceGenExtension/Sources/MySourceGenTool/main.swift
  Fixtures/Miscellaneous/Extensions/MySourceGenExtension/Sources/MySourceGenToolLib/library.swift
  Package.swift
  Sources/Build/BuildOperation.swift
  Sources/Build/BuildPlan.swift
  Sources/Build/ManifestBuilder.swift
  Sources/CMakeLists.txt
  Sources/Commands/APIDigester.swift
  Sources/Commands/SwiftRunTool.swift
  Sources/Commands/SwiftTool.swift
  Sources/PackageExtension/CMakeLists.txt
  Sources/PackageExtension/ImplementationDetails.swift
  Sources/PackageExtension/PublicAPI/CommandConstructor.swift
  Sources/PackageExtension/PublicAPI/DiagnosticsEmitter.swift
  Sources/PackageExtension/PublicAPI/Globals.swift
  Sources/PackageExtension/PublicAPI/Path.swift
  Sources/PackageExtension/PublicAPI/TargetBuildContext.swift
  Sources/PackageLoading/PackageBuilder.swift
  Sources/PackageLoading/TargetSourcesBuilder.swift
  Sources/PackageModel/Target.swift
  Sources/SPMBuildCore/ExtensionEvaluator.swift
  Sources/Workspace/CMakeLists.txt
  Sources/Workspace/DefaultExtensionRunner.swift
  Tests/CommandsTests/PackageToolTests.swift
  Tests/FunctionalTests/ExtensionTests.swift
  Tests/PackageLoadingTests/TargetSourcesBuilderTests.swift
  Tests/SPMBuildCoreTests/ExtensionEvaluationTests.swift
  Utilities/bootstrap
Labels: ready

#3289 infrastructure for binary dependencies beyond xcframeworks
  Sources/Build/BuildPlan.swift
  Sources/PackageGraph/PackageGraph+Loading.swift
  Sources/PackageLoading/ManifestLoader.swift
  Sources/PackageLoading/PackageBuilder.swift
  Sources/PackageModel/Target.swift
  Sources/SPMTestSupport/MockArchiver.swift
  Sources/SPMTestSupport/MockWorkspace.swift
  Sources/SPMTestSupport/misc.swift
  Sources/Workspace/ManagedArtifact.swift
  Sources/Workspace/Workspace.swift
  Tests/BuildTests/BuildPlanTests.swift
  Tests/PackageLoadingTests/PackageBuilderTests.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
  Tests/XCBuildSupportTests/PIFBuilderTests.swift
Labels: ready

#3271 [Collections] Signing (apple, 4): signature validation
  Package.swift
  Sources/Commands/SwiftPackageCollectionsTool.swift
  Sources/PackageCollections/API.swift
  Sources/PackageCollections/CMakeLists.txt
  Sources/PackageCollections/PackageCollections+CertificatePolicy.swift
  Sources/PackageCollections/PackageCollections.swift
  Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift
  Sources/PackageCollectionsModel/PackageCollectionModel+v1.swift
  Sources/PackageCollectionsSigning/Certificate/CertificatePolicy.swift
  Sources/PackageCollectionsSigning/PackageCollectionSigning.swift
  Sources/PackageCollectionsSigning/Signing/Signature.swift
  Tests/PackageCollectionsModelTests/PackageCollectionModelTests.swift
  Tests/PackageCollectionsSigningTests/CertificatePolicyTests.swift
  Tests/PackageCollectionsSigningTests/PackageCollectionSigningTest.swift
  Tests/PackageCollectionsSigningTests/SignatureTests.swift
  Tests/PackageCollectionsTests/JSONPackageCollectionProviderTests.swift
  Tests/PackageCollectionsTests/PackageCollectionsTests.swift
  Tests/PackageCollectionsTests/Utility.swift
Labels: ready

#3275 [Collections] Export PackageCollectionsSigning as library
  Package.swift
Labels: ready

#3293 Add DriverKit as a supported platform
  Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift
  Sources/PackageDescription/SupportedPlatforms.swift
  Sources/PackageLoading/MinimumDeploymentTarget.swift
  Sources/PackageLoading/PlatformRegistry.swift
  Sources/PackageModel/ManifestSourceGeneration.swift
  Sources/PackageModel/Platform.swift
  Sources/Workspace/InitPackage.swift
  Sources/XCBuildSupport/PIF.swift
  Sources/XCBuildSupport/PIFBuilder.swift
  Sources/Xcodeproj/XcodeProjectModel.swift
  Sources/Xcodeproj/pbxproj.swift
  Tests/PackageLoadingTests/PackageBuilderTests.swift
Labels: ready

#3299 [Extensions] Allow commands passed back from extensions to reference a relative or absolute path
  Sources/Build/ManifestBuilder.swift
  Sources/SPMBuildCore/ExtensionEvaluator.swift
  Tests/SPMBuildCoreTests/ExtensionEvaluationTests.swift
Labels: ready

#3300 [Extensions] Pass through the `allowExtensionTargets` flag from the Workspace to PackageGraph
  Sources/Workspace/Workspace.swift
Labels: ready

#3301 Fix an assertion failure with XCFramework inside a subdirectory
  Sources/Workspace/Workspace.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: ready

#3295 add artifacts archive file format
  Sources/Build/ArtifactsArchiveMetadata.swift
  Sources/Build/BuildPlan.swift
  Sources/Build/CMakeLists.txt
  Sources/Build/XCFrameworkMetadata.swift
  Sources/PackageModel/Target.swift
  Tests/BuildTests/ArtifactsArchiveMetadataTests.swift
  Tests/BuildTests/BuildPlanTests.swift
  Tests/BuildTests/XCFrameworkInfoTests.swift
  Tests/BuildTests/XCFrameworkMetadataTests.swift
  Tests/PackageLoadingTests/PD5_3LoadingTests.swift
Labels: ready

#3297 [Collections] Check for collections that are required to be signed
  Sources/Commands/SwiftPackageCollectionsTool.swift
  Sources/PackageCollections/API.swift
  Sources/PackageCollections/PackageCollections+CertificatePolicy.swift
  Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift
  Tests/PackageCollectionsSigningTests/CertificatePolicyTests.swift
  Tests/PackageCollectionsTests/JSONPackageCollectionProviderTests.swift
  Tests/PackageCollectionsTests/PackageCollectionSourceCertificatePolicyTests.swift
Labels: ready

#3303 replace custom downloader with http-client
  Sources/Basics/HTPClient+URLSession.swift
  Sources/Basics/HTTPClient.swift
  Sources/SPMTestSupport/MockDownloader.swift
  Sources/SPMTestSupport/MockHTTPClient.swift
  Sources/SPMTestSupport/MockWorkspace.swift
  Sources/Workspace/Workspace.swift
  Tests/BasicsTests/URLSessionHTTPClientTests.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: ready

#3302 introduce archive index files
  Sources/Basics/ConcurrencyHelpers.swift
  Sources/SPMTestSupport/MockHTTPClient.swift
  Sources/SPMTestSupport/MockHashAlgorithm.swift
  Sources/SPMTestSupport/MockWorkspace.swift
  Sources/Workspace/Diagnostics.swift
  Sources/Workspace/Workspace.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: ready

#3257 Duplicate error message on package resolve
  Sources/Commands/SwiftPackageTool.swift
Labels: ready

#3305 [Collections] Trigger collection refresh if deserialization of SQLite data fails
  Sources/PackageCollections/Model/Collection.swift
  Sources/PackageCollections/PackageCollections.swift
  Tests/PackageCollectionsTests/PackageCollectionsTests.swift
Labels: ready

#3304 Do not pass `-framework` to compiler tasks
  Sources/Build/BuildPlan.swift
  Tests/BuildTests/BuildPlanTests.swift
Labels: ready

#3263 Use `executableTarget` in generated new executable packages
  Sources/Workspace/InitPackage.swift
Labels: next

#3282 Update swift-crypto dependency to use version instead of main
  Package.swift
Labels: ready

#3308 improve identity handling
  Sources/PackageGraph/PackageGraph+Loading.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: ready

#3296 [Collections] Tighten import conditions
  Sources/PackageCollections/API.swift
  Sources/PackageCollections/PackageCollections.swift
  Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift
  Sources/PackageCollectionsSigning/Certificate/Certificate.swift
  Sources/PackageCollectionsSigning/Certificate/CertificatePolicy.swift
  Sources/PackageCollectionsSigning/Key/Key+EC.swift
  Sources/PackageCollectionsSigning/Key/Key+RSA.swift
  Sources/PackageCollectionsSigning/Signing/Signing+RSAKey.swift
  Tests/PackageCollectionsSigningTests/CertificatePolicyTests.swift
  Tests/PackageCollectionsSigningTests/CertificateTests.swift
  Tests/PackageCollectionsSigningTests/KeyTests+EC.swift
  Tests/PackageCollectionsSigningTests/KeyTests+RSA.swift
  Tests/PackageCollectionsSigningTests/PackageCollectionSigningTest.swift
  Tests/PackageCollectionsSigningTests/SignatureTests.swift
  Tests/PackageCollectionsSigningTests/SigningTests+ECKey.swift
  Tests/PackageCollectionsSigningTests/SigningTests+RSAKey.swift
  Tests/PackageCollectionsSigningTests/Utilities.swift
  Tests/PackageCollectionsTests/JSONPackageCollectionProviderTests.swift
  Tests/PackageCollectionsTests/PackageCollectionsTests.swift
Labels: ready

#3292 Allow for .package(url: , branch:) syntax
  CHANGELOG.md
  Documentation/PackageDescription.md
  Fixtures/DependencyResolution/External/Branch/Bar/Package.swift
  Fixtures/DependencyResolution/External/Branch/Bar/Sources/Bar/Bar.swift
  Fixtures/DependencyResolution/External/Branch/Foo/Package.swift
  Fixtures/DependencyResolution/External/Branch/Foo/Sources/Foo/Foo.swift
  Sources/PackageDescription/PackageDependency.swift
  Sources/SPMTestSupport/misc.swift
  Tests/FunctionalTests/DependencyResolutionTests.swift
  Tests/PackageLoadingTests/PD4_0LoadingTests.swift
  Tests/SourceControlTests/GitRepositoryTests.swift
Labels: ready

#3280 improve and simplify validation of target based dependencies
  Sources/PackageGraph/PackageGraph+Loading.swift
  Sources/PackageGraph/PackageGraph.swift
  Sources/PackageModel/Manifest.swift
  Tests/PackageGraphTests/PackageGraphTests.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: ready

#3311 Rename "extension" to "plugin" in the implementation of SE-0303 to align with the proposal
  Fixtures/Miscellaneous/Plugins/MySourceGenClient/Package.swift
  Fixtures/Miscellaneous/Plugins/MySourceGenClient/Sources/MyTool/Foo.dat
  Fixtures/Miscellaneous/Plugins/MySourceGenClient/Sources/MyTool/main.swift
  Fixtures/Miscellaneous/Plugins/MySourceGenClient/Tests/MyTests/MyTests.swift
  Fixtures/Miscellaneous/Plugins/MySourceGenPlugin/Package.swift
  Fixtures/Miscellaneous/Plugins/MySourceGenPlugin/Sources/MyLocalTool/Foo.dat
  Fixtures/Miscellaneous/Plugins/MySourceGenPlugin/Sources/MyLocalTool/main.swift
  Fixtures/Miscellaneous/Plugins/MySourceGenPlugin/Sources/MySourceGenPlugin/plugin.swift
  Fixtures/Miscellaneous/Plugins/MySourceGenPlugin/Sources/MySourceGenRuntimeLib/library.swift
  Fixtures/Miscellaneous/Plugins/MySourceGenPlugin/Sources/MySourceGenTool/main.swift
  Fixtures/Miscellaneous/Plugins/MySourceGenPlugin/Sources/MySourceGenToolLib/library.swift
  Fixtures/Miscellaneous/Plugins/MySourceGenPlugin/Tests/MySourceGenPluginTests/MySourceGenPluginTests.swift
  Package.swift
  Sources/Build/BuildOperation.swift
  Sources/Build/BuildPlan.swift
  Sources/Build/ManifestBuilder.swift
  Sources/CMakeLists.txt
  Sources/Commands/APIDigester.swift
  Sources/Commands/Describe.swift
  Sources/Commands/SwiftRunTool.swift
  Sources/Commands/SwiftTool.swift
  Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift
  Sources/PackageDescription/PackageDescription.swift
  Sources/PackageDescription/Product.swift
  Sources/PackageDescription/Target.swift
  Sources/PackageGraph/PackageGraph+Loading.swift
  Sources/PackageLoading/Diagnostics.swift
  Sources/PackageLoading/PackageBuilder.swift
  Sources/PackageLoading/PackageDescription4Loader.swift
  Sources/PackageModel/Manifest/TargetDescription.swift
  Sources/PackageModel/ManifestSourceGeneration.swift
  Sources/PackageModel/Product.swift
  Sources/PackageModel/Target.swift
  Sources/PackagePlugin/CMakeLists.txt
  Sources/PackagePlugin/ImplementationDetails.swift
  Sources/PackagePlugin/PublicAPI/CommandConstructor.swift
  Sources/PackagePlugin/PublicAPI/DiagnosticsEmitter.swift
  Sources/PackagePlugin/PublicAPI/Globals.swift
  Sources/PackagePlugin/PublicAPI/Path.swift
  Sources/PackagePlugin/PublicAPI/TargetBuildContext.swift
  Sources/SPMBuildCore/BuildParameters.swift
  Sources/SPMBuildCore/CMakeLists.txt
  Sources/SPMBuildCore/PluginInvocation.swift
  Sources/Workspace/CMakeLists.txt
  Sources/Workspace/DefaultPluginScriptRunner.swift
  Sources/XCBuildSupport/PIFBuilder.swift
  Sources/Xcodeproj/SchemesGenerator.swift
  Sources/Xcodeproj/Target+PBXProj.swift
  Sources/Xcodeproj/pbxproj.swift
  Tests/CommandsTests/PackageToolTests.swift
  Tests/FunctionalTests/PluginTests.swift
  Tests/PackageLoadingTests/PD5_4LoadingTests.swift
  Tests/PackageLoadingTests/PDNextVersionLoadingTests.swift
  Tests/PackageLoadingTests/PackageBuilderTests.swift
  Tests/SPMBuildCoreTests/PluginInvocationTests.swift
  Tests/WorkspaceTests/ManifestSourceGenerationTests.swift
  Utilities/bootstrap
Labels: ready

#3313 fix "build complete" message
  Sources/Build/BuildOperation.swift
  Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
  Tests/CommandsTests/BuildToolTests.swift
  Tests/FunctionalTests/PluginTests.swift
Labels: ready

#3312 Move usage of plugins from `dependencies` to `plugins` parameter to align with SE-0303
  Fixtures/Miscellaneous/Plugins/MySourceGenClient/Package.swift
  Fixtures/Miscellaneous/Plugins/MySourceGenPlugin/Package.swift
  Sources/PackageDescription/Target.swift
  Sources/PackageLoading/PackageBuilder.swift
  Sources/PackageLoading/PackageDescription4Loader.swift
  Sources/PackageModel/Manifest/TargetDescription.swift
  Sources/PackageModel/Target.swift
Labels: ready
