Repository swiftlang/swift-package-manager, pull requests merged in 2021-05, with the labels that each got.

#3407 Fix swift package init --help printout
  Package.swift
  Sources/Commands/Options.swift
  Sources/Commands/SwiftBuildTool.swift
  Sources/Commands/SwiftPackageTool.swift
  Sources/Commands/SwiftRunTool.swift
  Sources/Commands/SwiftTestTool.swift
Labels: wip

#3364 Add revised package registry server specification
  Documentation/RegistryDraft.md
Labels: next

#3465 Change branch dependencies on TSC, LLBuild, and SwiftDriver from `main` to `release/5.5`
  Package.swift
Labels: 5.5

#3466 enable netrc on non-darwin platforms
  Fixtures/DependencyResolution/External/XCFramework/Foo.xcframework/Info.plist
  Fixtures/DependencyResolution/External/XCFramework/Foo/Foo.swift
  Fixtures/DependencyResolution/External/XCFramework/Package.swift
  Sources/Commands/SwiftTool.swift
  Sources/Workspace/Workspace.swift
  Tests/BasicsTests/URLSessionHTTPClientTests.swift
  Tests/CommandsTests/PackageToolTests.swift
Labels: ready

#3467 [5.5] Fix resource bundle lookup (cherry-pick of #3463)
  Sources/Build/BuildPlan.swift
  Tests/BuildTests/BuildPlanTests.swift
Labels: 5.5

#3474 [5.5][Collections] Improve error handling (#3471)
  Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift
  Tests/PackageCollectionsTests/JSONPackageCollectionProviderTests.swift
Labels: 5.5

#3478 fix silent crash when output from compiler is too large
  Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
Labels: ready

#3480 [5.5][Collections] Add information about metadata provider to getPackageMetadata result
  Sources/PackageCollections/Model/Package.swift
  Sources/PackageCollections/PackageCollections.swift
  Sources/PackageCollections/Providers/GitHubPackageMetadataProvider.swift
  Sources/PackageCollections/Providers/PackageMetadataProvider.swift
  Tests/PackageCollectionsTests/GitHubPackageMetadataProviderTests.swift
  Tests/PackageCollectionsTests/PackageCollectionsTests.swift
  Tests/PackageCollectionsTests/Utility.swift
Labels: 5.5

#3483 [5.5] fix silent crash when output from compiler is too large
  Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
Labels: 5.5

#3481 [5.5] Fix PackageCollectionsTests.testUpdateAuthTokens (#3479)
  Tests/PackageCollectionsTests/PackageCollectionsTests.swift
Labels: 5.5

#3417 [5.4] Enable symlink support explicitly
  Sources/SourceControl/GitRepository.swift
Labels: 5.4

#3493 [5.5] Update index store to enum
  Sources/Commands/Options.swift
  Sources/Commands/SwiftTool.swift
Labels: 5.5

#3498 [5.5] Update BuildToolTests.testBuildCompleteMessage
  Tests/CommandsTests/BuildToolTests.swift
Labels: 5.5

#3499 [5.5][Collections] Support 'v' prefix in version
  Fixtures/Collections/GitHub/releases.json
  Fixtures/Collections/JSON/good.json
  Fixtures/Collections/JSON/good_signed.json
  Sources/Basics/CMakeLists.txt
  Sources/Basics/Version+Extensions.swift
  Sources/PackageCollections/PackageCollections+Validation.swift
  Sources/PackageCollections/Providers/GitHubPackageMetadataProvider.swift
  Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift
  Sources/PackageGraph/RepositoryPackageContainer.swift
  Tests/PackageCollectionsTests/GitHubPackageMetadataProviderTests.swift
  Tests/PackageCollectionsTests/JSONPackageCollectionProviderTests.swift
  Tests/PackageCollectionsTests/PackageCollectionValidationTests.swift
Labels: 5.5

#3484 [5.4] fix "build complete" message
  Sources/Build/BuildDelegate.swift
  Sources/Build/BuildOperation.swift
  Tests/CommandsTests/BuildToolTests.swift
Labels: 5.4

#3482 [5.4] fix silent crash when output from compiler is too large
  Sources/Build/BuildDelegate.swift
Labels: 5.4

#3506 [5.5][Collections] Dedupe package versions in GitHub metadata (#3504)
  Sources/PackageCollections/PackageCollections.swift
Labels: 5.5

#3503 [5.5] run trie generation thread with QOS set to background
  Sources/PackageCollections/Storage/SQLitePackageCollectionsStorage.swift
  Tests/PackageCollectionsTests/PackageCollectionsStorageTests.swift
Labels: 5.5

#3510 [5.5][Collections] Update CLI output for 'describe'
  Documentation/PackageCollections.md
  Sources/Commands/SwiftPackageCollectionsTool.swift
Labels: 5.5
