Repository swiftlang/swift-package-manager, pull requests merged in 2022-12, with the labels that each got.

#5632 [SE-0362] Add `enableUpcomingFeature` and `enableExperimentalFeature` Swift settings
  Sources/PackageDescription/BuildSettings.swift
  Sources/PackageLoading/ManifestJSONParser.swift
  Sources/PackageLoading/PackageBuilder.swift
  Sources/PackageModel/Manifest/TargetBuildSettingDescription.swift
  Sources/PackageModel/ManifestSourceGeneration.swift
  Tests/BuildTests/BuildPlanTests.swift
Labels: pending evolution proposal

#5894 Utilities/bootstrap: fix ignored `--clang-path` option
  Utilities/bootstrap
Labels: linux

#5911 Commands: add `experimental-destination` command
  Package.swift
  Sources/Basics/FileSystem+Extensions.swift
  Sources/CoreCommands/Options.swift
  Sources/CoreCommands/SwiftTool.swift
  Sources/CrossCompilationDestinationsTool/ListDestinations.swift
  Sources/CrossCompilationDestinationsTool/SwiftDestinationCommand.swift
  Sources/SPMBuildCore/ArtifactsArchiveMetadata.swift
  Sources/SPMBuildCore/CMakeLists.txt
  Sources/SPMBuildCore/DestinationsBundle.swift
  Sources/swift-experimental-destination/main.swift
  Sources/swift-package-manager/main.swift
  Utilities/bootstrap
Labels: enhancement

#5977 Update old link to Swift Jira in `README.md`
  README.md
Labels: documentation

#5973 InitPackage.swift: remove redundant `public`
  Sources/Workspace/InitPackage.swift
Labels: enhancement

#5949 Add `--pkg-config-path` to `LocationOptions`
  CHANGELOG.md
  Sources/Build/BuildOperation.swift
  Sources/Build/BuildPlan.swift
  Sources/Commands/PackageTools/PluginCommand.swift
  Sources/CoreCommands/BuildSystemSupport.swift
  Sources/CoreCommands/Options.swift
  Sources/CoreCommands/SwiftTool.swift
  Sources/PackageLoading/Target+PkgConfig.swift
  Sources/PackageModel/BuildEnvironment.swift
  Sources/SPMBuildCore/BuildParameters.swift
  Sources/SPMBuildCore/PluginContextSerializer.swift
  Sources/SPMBuildCore/PluginInvocation.swift
  Sources/XCBuildSupport/PIFBuilder.swift
  Sources/XCBuildSupport/XcodeBuildSystem.swift
  Tests/BuildTests/MockBuildTestHelper.swift
  Tests/FunctionalTests/MiscellaneousTests.swift
  Tests/PackageLoadingTests/PkgConfigTests.swift
  Tests/SPMBuildCoreTests/PluginInvocationTests.swift
  Tests/XCBuildSupportTests/PIFBuilderTests.swift
Labels: enhancement

#5983 Fix broken links in `CHANGELOG.md`
  CHANGELOG.md
Labels: documentation

#5986 [5.8] Add package metadata to a few more ObservabilityScopes in workspace-wide package operations
  Sources/PackageGraph/PackageGraph+Loading.swift
  Sources/PackageGraph/Pubgrub/PubgrubDependencyResolver.swift
  Sources/Workspace/Workspace.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: 5.8

#5985 Fix "Add emit extension block symbols option to dump-symbol-graph and SymbolGraphOptions"
  Sources/Commands/PackageTools/DumpCommands.swift
  Sources/Commands/Utilities/PluginDelegate.swift
  Sources/Commands/Utilities/SymbolGraphExtract.swift
  Sources/PackagePlugin/PackageManagerProxy.swift
  Sources/PackagePlugin/PluginMessages.swift
  Sources/SPMBuildCore/PluginInvocation.swift
Labels: 5.8
