Repository swiftlang/swift-package-manager, pull requests merged in 2022-02, with the labels that each got.

#4067 [5.6] Fix issues caused by having the plugin subcommand be the default subcommand (#4060)
  Sources/Commands/SwiftPackageTool.swift
  Tests/CommandsTests/PackageToolTests.swift
Labels: 5.6

#4068 refactor repository manager
  Sources/Basics/CMakeLists.txt
  Sources/Basics/String+Extensions.swift
  Sources/PackageRegistry/RegistryDownloadsManager.swift
  Sources/SPMTestSupport/InMemoryGitRepository.swift
  Sources/SourceControl/GitRepository.swift
  Sources/SourceControl/Repository.swift
  Sources/SourceControl/RepositoryManager.swift
  Sources/Workspace/Workspace.swift
  Tests/SourceControlTests/GitRepositoryProviderTests.swift
  Tests/SourceControlTests/GitRepositoryTests.swift
  Tests/SourceControlTests/RepositoryManagerTests.swift
  Tests/WorkspaceTests/SourceControlPackageContainerTests.swift
Labels: ready

#4071 refactor workspace delegates
  Package.swift
  Sources/Commands/SwiftTool.swift
  Sources/SPMTestSupport/MockWorkspace.swift
  Sources/SourceControl/CMakeLists.txt
  Sources/SourceControl/RepositoryManager.swift
  Sources/Workspace/Workspace.swift
  Tests/SourceControlTests/RepositoryManagerTests.swift
  Tests/WorkspaceTests/SourceControlPackageContainerTests.swift
Labels: ready

#4077 adjust FileSystem implementation to new APIs
  Sources/Basics/VirtualFileSystem.swift
  Sources/SPMTestSupport/InMemoryGitRepository.swift
  Sources/SourceControl/GitRepository.swift
  Tests/BasicsTests/URLSessionHTTPClientTests.swift
Labels: ready

#4078 improve concurrency handling in RepositoryManager
  Sources/SourceControl/RepositoryManager.swift
  Tests/SourceControlTests/RepositoryManagerTests.swift
Labels: ready

#4082 move netrc parser into SwiftPM (from TSC)
  Sources/Basics/AuthorizationProvider.swift
  Sources/Basics/CMakeLists.txt
  Sources/Basics/Netrc.swift
  Tests/BasicsTests/NetrcTests.swift
Labels: ready

#4083 move archiver to SwiftPM (from TSC)
  Sources/Basics/Archiver+Zip.swift
  Sources/Basics/Archiver.swift
  Sources/Basics/CMakeLists.txt
  Sources/PackageRegistry/RegistryClient.swift
  Sources/SPMTestSupport/MockArchiver.swift
  Sources/SPMTestSupport/MockRegistry.swift
  Sources/Workspace/Workspace.swift
  Tests/BasicsTests/Inputs/archive.zip
  Tests/BasicsTests/Inputs/invalid_archive.zip
  Tests/BasicsTests/ZipArchiverTests.swift
  Tests/WorkspaceTests/RegistryPackageContainerTests.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: ready

#4080 Compile plugins defined in a package when building the package
  Sources/Build/BuildOperation.swift
  Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
  Sources/Build/BuildPlan.swift
  Sources/Commands/APIDigester.swift
  Sources/Commands/SwiftPackageTool.swift
  Sources/Commands/SwiftRunTool.swift
  Sources/Commands/SwiftTool.swift
  Sources/SPMBuildCore/PluginInvocation.swift
  Sources/Workspace/DefaultPluginScriptRunner.swift
  Tests/CommandsTests/PackageToolTests.swift
  Tests/SPMBuildCoreTests/PluginInvocationTests.swift
Labels: ready

#4084 Mark plugin Command input parameters as CustomStringConvertible instead of String
  Sources/PackagePlugin/CMakeLists.txt
  Sources/PackagePlugin/Command.swift
  Sources/PackagePlugin/PackageModel.swift
  Sources/PackagePlugin/Utilities.swift
  Tests/CommandsTests/PackageToolTests.swift
Labels: ready

#4087 [5.6] Mark plugin Command input parameters as CustomStringConvertible instead of String (#4084)
  Sources/PackagePlugin/CMakeLists.txt
  Sources/PackagePlugin/Command.swift
  Sources/PackagePlugin/PackageModel.swift
  Sources/PackagePlugin/Utilities.swift
  Tests/CommandsTests/PackageToolTests.swift
Labels: ready, 5.6

#4092 [5.6] update netrc auth provider to read file "live"
  Sources/Basics/AuthorizationProvider.swift
Labels: 5.6

#4086 [5.6] Compile plugins defined in a package when building the package (#4080)
  Sources/Build/BuildOperation.swift
  Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
  Sources/Build/BuildPlan.swift
  Sources/Commands/APIDigester.swift
  Sources/Commands/SwiftPackageTool.swift
  Sources/Commands/SwiftRunTool.swift
  Sources/Commands/SwiftTool.swift
  Sources/SPMBuildCore/PluginInvocation.swift
  Sources/Workspace/DefaultPluginScriptRunner.swift
  Tests/CommandsTests/PackageToolTests.swift
  Tests/SPMBuildCoreTests/PluginInvocationTests.swift
Labels: ready, 5.6

#4095 [5.6] Add `products(ofType:)`, `targets(ofType:)`, and `sourceFiles(withSuffix:)` utilities to PackagePlugin API
  Sources/PackagePlugin/Utilities.swift
  Tests/CommandsTests/PackageToolTests.swift
Labels: 5.6

#4074 refactor authorization provider setup
  Sources/Basics/AuthorizationProvider.swift
  Sources/Commands/SwiftTool.swift
  Sources/Workspace/WorkspaceConfiguration.swift
  Tests/CommandsTests/SwiftToolTests.swift
  Tests/WorkspaceTests/AuthorizationProviderTests.swift
Labels: ready

#4104 Cancelling `swift package` with Control-C doesn't stop any running plugins
  Sources/Commands/SwiftTool.swift
  Sources/Workspace/DefaultPluginScriptRunner.swift
  Tests/FunctionalTests/PluginTests.swift
Labels: ready

#4098 Add module kind enum to the package plugin API
  Sources/PackagePlugin/PackageModel.swift
  Sources/PackagePlugin/PluginInput.swift
  Sources/SPMBuildCore/PluginInvocation.swift
  Tests/CommandsTests/PackageToolTests.swift
Labels: ready

#4072 Increment SwiftArgumentParser dependency to 1.0.3
  Package.swift
Labels: ready

#4076 [5.6] Increment SwiftArgumentParser dependency to 1.0.3
  Package.swift
Labels: ready, 5.6

#4107 [5.6] Disable a flaky part of the unit test `PackageToolTests.testPluginCompilationBeforeBuilding`
  Tests/CommandsTests/PackageToolTests.swift
Labels: ready, 5.6

#4101 [5.6] Add module kind enum to the package plugin API
  Sources/PackagePlugin/PackageModel.swift
  Sources/PackagePlugin/PluginInput.swift
  Sources/SPMBuildCore/PluginInvocation.swift
  Tests/CommandsTests/PackageToolTests.swift
Labels: ready, 5.6

#4105 [5.6] Cancelling `swift package` with Control-C doesn't stop any running plugins
  Sources/Commands/SwiftTool.swift
  Sources/Workspace/DefaultPluginScriptRunner.swift
  Tests/FunctionalTests/PluginTests.swift
Labels: ready, 5.6

#4118 improve handling of redundant output on stdout for commands that emit consumable information
  Sources/Commands/SwiftPackageTool.swift
  Sources/Commands/SwiftTestTool.swift
  Tests/FunctionalTests/DependencyResolutionTests.swift
Labels: ready

#4119 add flag to disable building with testablity when running tests
  Fixtures/Miscellaneous/TestableExe/Tests/TestableExeTests/TestableExeTests.swift
  Sources/Build/BuildPlan.swift
  Sources/Build/LLBuildManifestBuilder.swift
  Sources/Commands/SwiftTestTool.swift
  Sources/Commands/TestingSupport.swift
  Sources/LLBuildManifest/BuildManifest.swift
  Sources/SPMBuildCore/BuildParameters.swift
  Tests/CommandsTests/TestToolTests.swift
Labels: ready

#4120 improve the readabilty of diagnostics that have a "location prefix"
  Sources/Commands/SwiftTool.swift
Labels: ready

#4124 refactor test fixtures throw underlying error
  Sources/SPMTestSupport/misc.swift
  Tests/BasicsTests/URLSessionHTTPClientTests.swift
  Tests/BuildTests/IncrementalBuildTests.swift
  Tests/CommandsTests/APIDiffTests.swift
  Tests/CommandsTests/BuildToolTests.swift
  Tests/CommandsTests/PackageRegistryToolTests.swift
  Tests/CommandsTests/PackageToolTests.swift
  Tests/CommandsTests/RunToolTests.swift
  Tests/CommandsTests/SwiftToolTests.swift
  Tests/CommandsTests/TestToolTests.swift
  Tests/FunctionalPerformanceTests/BuildPerfTests.swift
  Tests/FunctionalTests/CFamilyTargetTests.swift
  Tests/FunctionalTests/DependencyResolutionTests.swift
  Tests/FunctionalTests/MiscellaneousTests.swift
  Tests/FunctionalTests/ModuleAliasingTests.swift
  Tests/FunctionalTests/ModuleMapTests.swift
  Tests/FunctionalTests/PluginTests.swift
  Tests/FunctionalTests/ResourcesTests.swift
  Tests/FunctionalTests/SwiftPMXCTestHelperTests.swift
  Tests/FunctionalTests/TestDiscoveryTests.swift
  Tests/PackageCollectionsSigningTests/CertificatePolicyTests.swift
  Tests/PackageCollectionsSigningTests/CertificateTests.swift
  Tests/PackageCollectionsSigningTests/KeyTests+EC.swift
  Tests/PackageCollectionsSigningTests/KeyTests+RSA.swift
  Tests/PackageCollectionsSigningTests/PackageCollectionSigningTest.swift
  Tests/PackageCollectionsSigningTests/SignatureTests.swift
  Tests/PackageCollectionsTests/GitHubPackageMetadataProviderTests.swift
  Tests/PackageCollectionsTests/JSONPackageCollectionProviderTests.swift
  Tests/PackageCollectionsTests/PackageCollectionsModelTests.swift
  Tests/PackageGraphPerformanceTests/DependencyResolverPerfTests.swift
  Tests/PackageGraphPerformanceTests/PackageGraphPerfTests.swift
  Tests/PackageLoadingPerformanceTests/ManifestLoadingTests.swift
  Tests/PackageLoadingTests/MinimumDeploymentTargetTests.swift
  Tests/PackageLoadingTests/PD_5_2_LoadingTests.swift
  Tests/PackageLoadingTests/PD_5_3_LoadingTests.swift
  Tests/SourceControlTests/RepositoryManagerTests.swift
  Tests/XCBuildSupportTests/PIFBuilderTests.swift
  Tests/XcodeprojTests/FunctionalTests.swift
  Tests/XcodeprojTests/GenerateXcodeprojTests.swift
Labels: ready

#4122 improve example created by package init --type executable
  IntegrationTests/Package.swift
  IntegrationTests/Tests/IntegrationTests/BasicTests.swift
  IntegrationTests/Tests/IntegrationTests/Helpers.swift
  IntegrationTests/Tests/IntegrationTests/SwiftPMTests.swift
  IntegrationTests/Tests/IntegrationTests/XCBuildTests.swift
  Sources/Workspace/InitPackage.swift
  Tests/CommandsTests/PackageToolTests.swift
  Tests/WorkspaceTests/InitTests.swift
Labels: ready

#4132 Refactor nested `if`s into a switch statement
  Sources/Workspace/Workspace.swift
Labels: ready

#4127 add customization point for host toolchain
  Sources/Commands/SwiftTool.swift
  Sources/Workspace/Workspace.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: ready

#4131 Make it impossible to create an invalid `BuildSettingCondition`
  Sources/PackageDescription/BuildSettings.swift
Labels: ready, add to change log

#4129 improve error message when using invalid path for local binary artifacts
  Sources/PackageLoading/ManifestLoader.swift
  Sources/Workspace/Workspace.swift
  Tests/PackageLoadingTests/PD_5_3_LoadingTests.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: ready

#4142 improve registry client handling of alternative locations
  Sources/Basics/HTPClient+URLSession.swift
  Sources/Basics/HTTPClient.swift
  Sources/Basics/String+Extensions.swift
  Sources/PackageRegistry/RegistryClient.swift
  Sources/Workspace/RegistryPackageContainer.swift
  Tests/BasicsTests/StringExtensionsTests.swift
  Tests/PackageRegistryTests/RegistryClientTests.swift
Labels: ready

#4135 Add -dead_strip / --gc-sections for release builds
  CHANGELOG.md
  Sources/Build/BuildPlan.swift
  Sources/Commands/Options.swift
  Sources/Commands/SwiftTool.swift
  Sources/SPMBuildCore/BuildParameters.swift
  Tests/BuildTests/BuildPlanTests.swift
Labels: add to change log

#4134 improve example created by package init --type executable
  IntegrationTests/Package.swift
  IntegrationTests/Tests/IntegrationTests/BasicTests.swift
  IntegrationTests/Tests/IntegrationTests/Helpers.swift
  IntegrationTests/Tests/IntegrationTests/SwiftPMTests.swift
  IntegrationTests/Tests/IntegrationTests/XCBuildTests.swift
  Sources/Workspace/InitPackage.swift
  Tests/CommandsTests/PackageToolTests.swift
  Tests/WorkspaceTests/InitTests.swift
Labels: ready

#4147 cleanup workspace binary artifacts tests
  Sources/SPMTestSupport/MockWorkspace.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: ready

#4145 cleanup dependency location sanitization in manifest parser
  Sources/PackageLoading/ManifestJSONParser.swift
Labels: ready

#4146 make XCTest optional on macOS for operations that do not require testing
  Sources/Commands/SwiftTestTool.swift
  Sources/PackageModel/ToolchainConfiguration.swift
  Sources/Workspace/UserToolchain.swift
Labels: ready

#4143 [NFC] cleanup
  Sources/Basics/AuthorizationProvider.swift
  Sources/Basics/HTPClient+URLSession.swift
  Sources/Basics/SQLiteBackedCache.swift
  Sources/Build/BuildPlan.swift
  Sources/Commands/SwiftPackageCollectionsTool.swift
  Sources/Commands/SwiftTool.swift
  Sources/PackageCollections/API.swift
  Sources/PackageCollections/Model/Search.swift
  Sources/PackageCollections/PackageIndex+Configuration.swift
  Sources/PackageCollections/PackageIndex.swift
  Sources/PackageCollections/Providers/GitHubPackageMetadataProvider.swift
  Sources/PackageCollections/Providers/PackageMetadataProvider.swift
  Sources/PackageCollections/Storage/SQLitePackageCollectionsStorage.swift
  Sources/PackageCollectionsModel/PackageCollectionModel+v1.swift
  Sources/PackageFingerprint/FilePackageFingerprintStorage.swift
  Sources/PackageFingerprint/Model.swift
  Sources/PackageGraph/PackageModel+Extensions.swift
  Sources/PackageGraph/Pubgrub/PubgrubDependencyResolver.swift
  Sources/PackageLoading/Diagnostics.swift
  Sources/PackageLoading/ManifestLoader.swift
  Sources/PackageLoading/PkgConfig.swift
  Sources/PackageModel/Manifest/PackageDependencyDescription.swift
  Sources/PackageModel/PackageIdentity.swift
  Sources/PackageModel/PackageReference.swift
  Sources/PackageRegistry/Registry.swift
  Sources/PackageRegistry/RegistryDownloadsManager.swift
  Sources/SPMTestSupport/ManifestExtensions.swift
  Sources/SPMTestSupport/MockPackage.swift
  Sources/SPMTestSupport/PackageDependencyDescriptionExtensions.swift
  Sources/Workspace/DefaultPluginScriptRunner.swift
  Sources/Workspace/Diagnostics.swift
  Sources/Workspace/RegistryPackageContainer.swift
  Sources/Workspace/Workspace.swift
  Sources/Xcodeproj/XcodeProjectModelSerialization.swift
  Tests/BasicsTests/AuthorizationProviderTests.swift
  Tests/BasicsTests/HTTPClientTests.swift
  Tests/BuildTests/BuildPlanTests.swift
  Tests/PackageCollectionsTests/PackageIndexAndCollectionsTests.swift
  Tests/PackageFingerprintTests/FilePackageFingerprintStorageTests.swift
  Tests/PackageGraphTests/PackageGraphTests.swift
  Tests/PackageGraphTests/PubgrubTests.swift
  Tests/PackageRegistryTests/RegistryClientTests.swift
  Tests/WorkspaceTests/SourceControlPackageContainerTests.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: ready

#4151 improve validation of local binary dependencies
  Fixtures/DependencyResolution/External/XCFramework/Bar.xcframework/Info.plist
  Fixtures/DependencyResolution/External/XCFramework/Package.swift
  Sources/Workspace/Diagnostics.swift
  Sources/Workspace/Workspace.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: ready

#4148 resolve source control dependencies via the registry when available
  Sources/Commands/Options.swift
  Sources/Commands/SwiftTool.swift
  Sources/PackageGraph/PackageModel+Extensions.swift
  Sources/PackageModel/Manifest.swift
  Sources/PackageModel/Manifest/PackageDependencyDescription.swift
  Sources/PackageRegistry/RegistryClient.swift
  Sources/SPMTestSupport/MockPackage.swift
  Sources/SPMTestSupport/MockRegistry.swift
  Sources/SPMTestSupport/MockWorkspace.swift
  Sources/Workspace/FileSystemPackageContainer.swift
  Sources/Workspace/Workspace.swift
  Sources/Workspace/WorkspaceConfiguration.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: ready

#4154 improve output stream handling in CLI
  Sources/Build/BuildOperation.swift
  Sources/Commands/APIDigester.swift
  Sources/Commands/Snippets/CardStack.swift
  Sources/Commands/SwiftBuildTool.swift
  Sources/Commands/SwiftPackageTool.swift
  Sources/Commands/SwiftRunTool.swift
  Sources/Commands/SwiftTestTool.swift
  Sources/Commands/SwiftTool.swift
  Tests/CommandsTests/SwiftToolTests.swift
  Tests/CommandsTests/TestToolTests.swift
  Tests/FunctionalTests/MiscellaneousTests.swift
  Tests/FunctionalTests/TestDiscoveryTests.swift
Labels: ready

#4157 audit and use abstract FileSystem instead of localFileSystem where possible
  Sources/Basics/Archiver+Zip.swift
  Sources/Build/BuildOperation.swift
  Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
  Sources/Build/BuildPlan.swift
  Sources/Build/LLBuildManifestBuilder.swift
  Sources/Commands/APIDigester.swift
  Sources/Commands/SwiftPackageCollectionsTool.swift
  Sources/Commands/SwiftPackageRegistryTool.swift
  Sources/Commands/SwiftPackageTool.swift
  Sources/Commands/SwiftRunTool.swift
  Sources/Commands/SwiftTestTool.swift
  Sources/Commands/SwiftTool.swift
  Sources/Commands/SymbolGraphExtract.swift
  Sources/Commands/TestingSupport.swift
  Sources/LLBuildManifest/ManifestWriter.swift
  Sources/PackageCollections/PackageCollections+Validation.swift
  Sources/PackageCollections/PackageCollections.swift
  Sources/PackageCollections/PackageIndexAndCollections.swift
  Sources/PackageCollections/Providers/GitHubPackageMetadataProvider.swift
  Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift
  Sources/PackageCollections/Storage/FilePackageCollectionsSourcesStorage.swift
  Sources/SPMBuildCore/PluginInvocation.swift
  Sources/SPMPackageEditor/PackageEditor.swift
  Sources/Workspace/DefaultPluginScriptRunner.swift
  Sources/Workspace/Destination.swift
  Sources/Workspace/InitPackage.swift
  Sources/Workspace/Workspace.swift
  Sources/XCBuildSupport/XcodeBuildSystem.swift
  Tests/BasicsTests/ZipArchiverTests.swift
  Tests/BuildTests/BuildPlanTests.swift
  Tests/BuildTests/LLBuildManifestTests.swift
  Tests/FunctionalTests/PluginTests.swift
  Tests/PackageCollectionsTests/JSONPackageCollectionProviderTests.swift
  Tests/PackageCollectionsTests/PackageCollectionsModelTests.swift
  Tests/PackageCollectionsTests/PackageCollectionsTests.swift
  Tests/PackageCollectionsTests/PackageIndexAndCollectionsTests.swift
  Tests/PackageCollectionsTests/Utility.swift
  Tests/SPMBuildCoreTests/PluginInvocationTests.swift
  Tests/WorkspaceTests/InitTests.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: ready

#4164 [5.6] Fix a bug that caused a plugin dependency on a local executable to not work properly
  Fixtures/Miscellaneous/Plugins/PluginUsingLocalAndRemoteTool/MyLibrary/Package.swift
  Fixtures/Miscellaneous/Plugins/PluginUsingLocalAndRemoteTool/MyLibrary/Sources/MyLibrary/library.swift
  Fixtures/Miscellaneous/Plugins/PluginUsingLocalAndRemoteTool/MyLibrary/Tests/MyLibraryTests/test.swift
  Fixtures/Miscellaneous/Plugins/PluginUsingLocalAndRemoteTool/MyPlugin/Libraries/LocalToolHelperLibrary/library.swift
  Fixtures/Miscellaneous/Plugins/PluginUsingLocalAndRemoteTool/MyPlugin/Package.swift
  Fixtures/Miscellaneous/Plugins/PluginUsingLocalAndRemoteTool/MyPlugin/Plugins/MyPlugin/plugin.swift
  Fixtures/Miscellaneous/Plugins/PluginUsingLocalAndRemoteTool/MyPlugin/Tools/ImpliedLocalTool/main.swift
  Fixtures/Miscellaneous/Plugins/PluginUsingLocalAndRemoteTool/MyPlugin/Tools/LocalTool/main.swift
  Fixtures/Miscellaneous/Plugins/PluginUsingLocalAndRemoteTool/RemoteTool/Libraries/RemoteToolHelperLibrary/library.swift
  Fixtures/Miscellaneous/Plugins/PluginUsingLocalAndRemoteTool/RemoteTool/Package.swift
  Fixtures/Miscellaneous/Plugins/PluginUsingLocalAndRemoteTool/RemoteTool/Tools/RemoteTool/main.swift
  Sources/Commands/SwiftPackageTool.swift
  Tests/FunctionalTests/PluginTests.swift
Labels: ready, 5.6

#4156 tests cleanup
  Sources/SPMTestSupport/XCTAssertHelpers.swift
  Tests/CommandsTests/APIDiffTests.swift
  Tests/CommandsTests/BuildToolTests.swift
  Tests/CommandsTests/PackageToolTests.swift
  Tests/CommandsTests/RunToolTests.swift
  Tests/CommandsTests/TestToolTests.swift
  Tests/FunctionalTests/MiscellaneousTests.swift
  Tests/FunctionalTests/PluginTests.swift
  Tests/FunctionalTests/ToolsVersionTests.swift
Labels: ready

#4162 cleanup force unwraps in a test utillity
  Sources/SPMTestSupport/InMemoryGitRepository.swift
  Tests/SourceControlTests/InMemoryGitRepositoryTests.swift
Labels: ready

#4161 use newer testing conventions in plugin tests
  Tests/FunctionalTests/PluginTests.swift
Labels: ready

#4165 address warning from TSC netrc deprecaton
  Tests/BasicsTests/URLSessionHTTPClientTests.swift
Labels: ready

#4155 Refactor and clean up plugin communication and wire messages
  Sources/Commands/SwiftPackageTool.swift
  Sources/PackagePlugin/CMakeLists.txt
  Sources/PackagePlugin/PackageManagerProxy.swift
  Sources/PackagePlugin/Plugin.swift
  Sources/PackagePlugin/PluginContextDeserializer.swift
  Sources/PackagePlugin/PluginMessages.swift
  Sources/SPMBuildCore/CMakeLists.txt
  Sources/SPMBuildCore/PluginContextSerializer.swift
  Sources/SPMBuildCore/PluginInvocation.swift
  Sources/SPMBuildCore/PluginMessages.swift
  Sources/SPMBuildCore/PluginScriptRunner.swift
  Sources/Workspace/DefaultPluginScriptRunner.swift
  Tests/FunctionalTests/PluginTests.swift
  Tests/SPMBuildCoreTests/PluginInvocationTests.swift
Labels: ready

#4169 reduce use of preconditions and asserts
  Sources/Build/BuildPlan.swift
  Sources/Build/LLBuildManifestBuilder.swift
  Sources/PackageGraph/Pubgrub/Incompatibility.swift
  Sources/PackageGraph/Pubgrub/PubgrubDependencyResolver.swift
  Sources/PackageGraph/ResolvedProduct.swift
  Sources/PackageLoading/ManifestLoader.swift
  Sources/PackageLoading/PackageBuilder.swift
  Sources/PackageLoading/PkgConfig.swift
  Sources/PackageModel/Manifest/ProductDescription.swift
  Sources/PackageModel/Product.swift
  Sources/PackageModel/Target.swift
  Sources/SPMTestSupport/MockWorkspace.swift
  Tests/BuildTests/BuildPlanTests.swift
  Tests/CommandsTests/PackageToolTests.swift
  Tests/PackageGraphPerformanceTests/PackageGraphPerfTests.swift
  Tests/PackageLoadingTests/PackageBuilderTests.swift
  Tests/PackageLoadingTests/PkgConfigParserTests.swift
  Tests/PackageModelTests/ManifestTests.swift
  Tests/WorkspaceTests/ManifestSourceGenerationTests.swift
  Tests/WorkspaceTests/SourceControlPackageContainerTests.swift
Labels: ready

#4168 Update to manifest API to make it impossible to create an invalid target dependency condition.
  CHANGELOG.md
  Sources/PackageDescription/BuildSettings.swift
  Sources/PackageDescription/PackageDescriptionSerialization.swift
  Sources/PackageDescription/Target.swift
  Tests/PackageLoadingTests/PD_5_3_LoadingTests.swift
  Tests/PackageLoadingTests/PD_5_7_LoadingTests .swift
Labels: ready

#4171 refactor target build settings model
  Sources/PackageLoading/ManifestJSONParser.swift
  Sources/PackageLoading/PackageBuilder.swift
  Sources/PackageModel/BuildSettings.swift
  Sources/PackageModel/Manifest/TargetBuildSettingDescription.swift
  Sources/PackageModel/ManifestSourceGeneration.swift
  Sources/XCBuildSupport/PIFBuilder.swift
  Sources/Xcodeproj/pbxproj.swift
  Tests/BuildTests/BuildPlanTests.swift
  Tests/PackageGraphTests/PackageGraphTests.swift
  Tests/PackageLoadingTests/PD_5_0_LoadingTests.swift
  Tests/PackageLoadingTests/PackageBuilderTests.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
  Tests/XCBuildSupportTests/PIFBuilderTests.swift
  Tests/XcodeprojTests/PackageGraphTests.swift
Labels: ready

#4174 move global functions to a namespace
  Sources/Commands/SwiftPackageTool.swift
  Sources/Xcodeproj/generate.swift
  Tests/XcodeprojTests/GenerateXcodeprojTests.swift
Labels: ready

#4167 refactor resource localization model
  Sources/PackageLoading/ManifestJSONParser.swift
  Sources/PackageLoading/PackageBuilder.swift
  Sources/PackageLoading/TargetSourcesBuilder.swift
  Sources/PackageModel/Manifest/TargetDescription.swift
  Sources/PackageModel/ManifestSourceGeneration.swift
  Sources/PackageModel/Resource.swift
  Tests/BasicsTests/URLSessionHTTPClientTests.swift
  Tests/BuildTests/BuildPlanTests.swift
  Tests/PackageLoadingTests/PD_5_3_LoadingTests.swift
  Tests/PackageLoadingTests/PackageBuilderTests.swift
  Tests/PackageLoadingTests/TargetSourcesBuilderTests.swift
  Tests/XCBuildSupportTests/PIFBuilderTests.swift
Labels: ready

#4170 Fixed some typos
  Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
  Sources/Build/BuildPlan.swift
  Sources/Build/LLBuildManifestBuilder.swift
  Sources/Commands/WatchmanHelper.swift
  Sources/PackageCollectionsModel/PackageCollectionModel+v1.swift
  Sources/PackageCollectionsSigning/Key/ASN1/ASN1.swift
  Sources/PackageDescription/Version.swift
  Sources/PackageGraph/PackageGraph+Loading.swift
  Sources/PackageGraph/Pubgrub/PartialSolution.swift
  Sources/PackageGraph/Pubgrub/PubgrubDependencyResolver.swift
  Sources/PackageGraph/ResolvedTarget.swift
  Sources/PackageLoading/PkgConfig.swift
  Sources/PackageLoading/PlatformRegistry.swift
  Sources/PackageModel/Manifest.swift
  Sources/PackageModel/ManifestSourceGeneration.swift
  Sources/PackageModel/Product.swift
  Sources/PackagePlugin/PackageManagerProxy.swift
  Sources/SPMPackageEditor/ManifestRewriter.swift
  Sources/SPMTestSupport/InMemoryGitRepository.swift
  Sources/SourceControl/GitRepository.swift
  Sources/Workspace/DefaultPluginScriptRunner.swift
  Sources/XCBuildSupport/PIF.swift
  Sources/XCBuildSupport/PIFBuilder.swift
  Sources/Xcodeproj/XcodeProjectModel.swift
  Sources/Xcodeproj/XcodeProjectModelSerialization.swift
  Sources/Xcodeproj/pbxproj.swift
  Tests/BuildTests/BuildPlanTests.swift
  Tests/CommandsTests/PackageToolTests.swift
  Tests/PackageDescriptionTests/VersionTests.swift
  Tests/PackageFingerprintTests/FilePackageFingerprintStorageTests.swift
  Tests/SourceControlTests/GitRepositoryTests.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
  Tests/XcodeprojTests/GenerateXcodeprojTests.swift
Labels: ready

#4177 improve repository manager lookup concurrency control
  Sources/SourceControl/RepositoryManager.swift
  Sources/Workspace/Workspace.swift
  Tests/PackageRegistryTests/RegistryDownloadsManagerTests.swift
  Tests/SourceControlTests/RepositoryManagerTests.swift
Labels: ready

#4178 improve manfiest loader concurrency control
  Sources/PackageLoading/ManifestLoader.swift
  Sources/SPMTestSupport/MockManifestLoader.swift
  Sources/Workspace/FileSystemPackageContainer.swift
  Sources/Workspace/RegistryPackageContainer.swift
  Sources/Workspace/SourceControlPackageContainer.swift
  Sources/Workspace/Workspace.swift
  Tests/PackageLoadingTests/PD_4_2_LoadingTests.swift
  Tests/WorkspaceTests/ManifestSourceGenerationTests.swift
  Tests/WorkspaceTests/RegistryPackageContainerTests.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: ready
