Repository swiftlang/swift-package-manager, pull requests merged in 2022-01, with the labels that each got.

#3919 [5.6] Set `relatedDependenciesBranch` to `release/5.6`
  Package.swift
Labels: 5.6

#3973 [5.6] Don't emit "unhandled files" warnings for files that are handled by build commands from package plugins (#3971)
  Sources/Build/BuildOperation.swift
  Sources/PackageLoading/TargetSourcesBuilder.swift
  Sources/PackageModel/Target.swift
  Tests/CommandsTests/PackageToolTests.swift
  Tests/PackageLoadingTests/TargetSourcesBuilderTests.swift
Labels: ready, 5.6

#3969 Mark command plugins as 5.6 instead of 999.0 now that SE-0332 has been accepted
  CHANGELOG.md
  Sources/Commands/SwiftPackageTool.swift
  Sources/PackageDescription/Target.swift
  Tests/CommandsTests/PackageToolTests.swift
  Tests/FunctionalTests/PluginTests.swift
Labels: ready

#3974 gracefully fail workspace state loading when duplicate entries found
  Sources/Workspace/ManagedArtifact.swift
  Sources/Workspace/ManagedDependency.swift
  Sources/Workspace/WorkspaceState.swift
  Tests/WorkspaceTests/WorkspaceStateTests.swift
Labels: ready

#3976 [5.6] gracefully fail workspace state loading when duplicate entries found (#3974)
  Sources/Workspace/ManagedArtifact.swift
  Sources/Workspace/ManagedDependency.swift
  Sources/Workspace/WorkspaceState.swift
  Tests/WorkspaceTests/WorkspaceStateTests.swift
Labels: ready, 5.6

#3975 [5.6] Mark command plugins as 5.6 instead of 999.0 now that SE-0332 has been accepted (#3969
  CHANGELOG.md
  Sources/Commands/SwiftPackageTool.swift
  Sources/PackageDescription/Target.swift
  Tests/CommandsTests/PackageToolTests.swift
  Tests/FunctionalTests/PluginTests.swift
Labels: ready, 5.6

#3967 make package.resolved more deterministic in edge cases
  Sources/PackageCollections/PackageCollections.swift
  Sources/PackageGraph/PackageGraph+Loading.swift
  Sources/PackageGraph/PinsStore.swift
  Sources/PackageModel/Manifest.swift
  Sources/PackageModel/Manifest/PackageDependencyDescription.swift
  Sources/PackageModel/PackageIdentity.swift
  Sources/PackageModel/PackageReference.swift
  Sources/SPMTestSupport/Observability.swift
  Sources/Workspace/Workspace.swift
  Tests/PackageModelTests/CanonicalPackageLocationTests.swift
  Tests/PackageModelTests/LegacyPackageIdentityTests.swift
  Tests/PackageModelTests/PackageIdentityParser.swift
  Tests/PackageModelTests/PackageModelTests.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: ready

#3977 Allow package plugins to be invoked using just `swift package`, and not require `swift package plugin`.
  Sources/Commands/SwiftPackageTool.swift
  Tests/CommandsTests/PackageToolTests.swift
Labels: ready

#3972 Support `--allow-writing-to-package-directory` as described in SE-0332 and `--allow-writing-to-directory` to allow arbitrary directories
  Sources/Commands/SwiftPackageTool.swift
  Sources/SPMBuildCore/PluginInvocation.swift
  Sources/Workspace/DefaultPluginScriptRunner.swift
  Tests/CommandsTests/PackageToolTests.swift
  Tests/FunctionalTests/PluginTests.swift
Labels: ready

#3979 [5.6] make package.resolved more deterministic in edge cases (#3967)
  Sources/PackageCollections/PackageCollections.swift
  Sources/PackageGraph/PackageGraph+Loading.swift
  Sources/PackageGraph/PinsStore.swift
  Sources/PackageModel/Manifest.swift
  Sources/PackageModel/Manifest/PackageDependencyDescription.swift
  Sources/PackageModel/PackageIdentity.swift
  Sources/PackageModel/PackageReference.swift
  Sources/SPMTestSupport/Observability.swift
  Sources/Workspace/Workspace.swift
  Tests/PackageModelTests/CanonicalPackageLocationTests.swift
  Tests/PackageModelTests/LegacyPackageIdentityTests.swift
  Tests/PackageModelTests/PackageIdentityParser.swift
  Tests/PackageModelTests/PackageModelTests.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: ready, 5.6

#3982 [5.6] Support `--allow-writing-to-package-directory` as described in SE-0332 and `--allow-writing-to-directory` to allow arbitrary directories (#3972)
  Sources/Commands/SwiftPackageTool.swift
  Sources/SPMBuildCore/PluginInvocation.swift
  Sources/Workspace/DefaultPluginScriptRunner.swift
  Tests/CommandsTests/PackageToolTests.swift
  Tests/FunctionalTests/PluginTests.swift
Labels: ready, 5.6

#3981 [5.6] Allow package plugins to be invoked using just `swift package`, and not require `swift package plugin` (#3977)
  Sources/Commands/SwiftPackageTool.swift
  Tests/CommandsTests/PackageToolTests.swift
Labels: ready, 5.6

#3983 Don't prefix each line of command plugin output with the name of the plugin
  Sources/Commands/SwiftPackageTool.swift
Labels: ready

#3984 Include the default command search paths for plugin tool lookup
  Sources/Commands/SwiftPackageTool.swift
  Tests/CommandsTests/PackageToolTests.swift
Labels: ready

#3986 [5.6] Don't prefix each line of command plugin output with the name of the plugin (#3983)
  Sources/Commands/SwiftPackageTool.swift
Labels: ready, 5.6

#3987 [5.6] Include the default command search paths for plugin tool lookup. (#3984)
  Sources/Commands/SwiftPackageTool.swift
  Tests/CommandsTests/PackageToolTests.swift
Labels: ready, 5.6

#3992 avoid deprecation warnings from test discovery
  Fixtures/Miscellaneous/TestDiscovery/Async/Tests/AsyncTests/SwiftTests.swift
  Fixtures/Miscellaneous/TestDiscovery/Deprecation/Package.swift
  Fixtures/Miscellaneous/TestDiscovery/Deprecation/Sources/Simple/Simple.swift
  Fixtures/Miscellaneous/TestDiscovery/Deprecation/Tests/SimpleTests/SwiftTests.swift
  Fixtures/Miscellaneous/TestDiscovery/Simple/Tests/SimpleTests/SwiftTests.swift
  Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
  Sources/Build/BuildPlan.swift
  Sources/Build/LLBuildManifestBuilder.swift
  Sources/LLBuildManifest/Tools.swift
  Tests/FunctionalTests/MiscellaneousTests.swift
  Tests/FunctionalTests/TestDiscoveryTests.swift
Labels: ready

#3994 cleanup use test-discovery main file name
  Sources/Build/BuildPlan.swift
Labels: ready

#3985 fix dependency resolution edge cases issues
  Sources/PackageGraph/Pubgrub/PubgrubDependencyResolver.swift
  Sources/Workspace/Workspace.swift
  Tests/PackageGraphTests/PubgrubTests.swift
Labels: ready

#3989 Update CHANGELOG to describe manifest API changes
  CHANGELOG.md
Labels: ready

#3990 Update CHANGELOG to describe configuration files location changes
  CHANGELOG.md
Labels: ready

#3991 Update CHANGELOG to describe new Package.resolved format
  CHANGELOG.md
Labels: ready

#3993 Make the symbol graph extraction requested by plugins more robust
  Sources/Commands/SwiftPackageTool.swift
  Sources/Commands/SymbolGraphExtract.swift
  Tests/CommandsTests/PackageToolTests.swift
Labels: ready

#3997 [5.6] fix dependency resolution edge cases issues (#3985)
  Sources/PackageGraph/Pubgrub/PubgrubDependencyResolver.swift
  Sources/Workspace/Workspace.swift
  Tests/PackageGraphTests/PubgrubTests.swift
Labels: ready, 5.6

#3996 Enforce read-only-ness of package directory even when it's inside writable directories
  Sources/Basics/Sandbox.swift
  Sources/Build/BuildOperation.swift
  Sources/Build/LLBuildManifestBuilder.swift
  Sources/Commands/SwiftPackageTool.swift
  Sources/PackageLoading/ManifestLoader.swift
  Sources/SPMBuildCore/PluginInvocation.swift
  Sources/Workspace/DefaultPluginScriptRunner.swift
  Tests/BasicsTests/SandboxTests.swift
  Tests/CommandsTests/PackageToolTests.swift
  Tests/FunctionalTests/PluginTests.swift
  Tests/SPMBuildCoreTests/PluginInvocationTests.swift
Labels: ready

#3998 [5.6] Make the symbol graph extraction requested by plugins more robust (#3993)
  Sources/Commands/SwiftPackageTool.swift
  Sources/Commands/SymbolGraphExtract.swift
  Tests/CommandsTests/PackageToolTests.swift
Labels: ready, 5.6

#3999 [5.6] Enforce read-only-ness of package directory even when it's inside writable directories (#3996)
  Sources/Basics/Sandbox.swift
  Sources/Build/BuildOperation.swift
  Sources/Build/LLBuildManifestBuilder.swift
  Sources/Commands/SwiftPackageTool.swift
  Sources/PackageLoading/ManifestLoader.swift
  Sources/SPMBuildCore/PluginInvocation.swift
  Sources/Workspace/DefaultPluginScriptRunner.swift
  Tests/BasicsTests/SandboxTests.swift
  Tests/CommandsTests/PackageToolTests.swift
  Tests/FunctionalTests/PluginTests.swift
  Tests/SPMBuildCoreTests/PluginInvocationTests.swift
Labels: ready, 5.6

#3912 [5.5] Add automatic library product for SwiftPMDataModel
  Package.swift
Labels: 5.5

#4002 Allow running tests from a command plugin
  Sources/Basics/DispatchTimeInterval+Extensions.swift
  Sources/Commands/CMakeLists.txt
  Sources/Commands/SwiftPackageTool.swift
  Sources/Commands/SwiftTestTool.swift
  Sources/Commands/TestingSupport.swift
  Sources/Workspace/UserToolchain.swift
  Tests/CommandsTests/PackageToolTests.swift
Labels: ready

#4007 dependency resolution performance
  Sources/PackageGraph/Pubgrub/PubgrubDependencyResolver.swift
  Sources/PackageLoading/ManifestLoader.swift
  Sources/Workspace/Workspace.swift
  Tests/PackageLoadingTests/PD_5_0_LoadingTests.swift
  Tests/SPMBuildCoreTests/PluginInvocationTests.swift
Labels: ready

#4021 gracefully handle pre-existing binary artifact from failed downloads
  Sources/Workspace/Workspace.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: ready

#4024 [5.6] Limit concurrent HTTP requests when downloading binary dependencies
  Sources/Workspace/Workspace.swift
Labels: ready, 5.6

#4025 [5.6] gracefully handle pre-existing binary artifact from failed downloads (#4021)
  Sources/Workspace/Workspace.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: ready, 5.6

#4008 [5.6] Allow running tests from a command plugin (#4002)
  Sources/Basics/DispatchTimeInterval+Extensions.swift
  Sources/Commands/CMakeLists.txt
  Sources/Commands/SwiftPackageTool.swift
  Sources/Commands/SwiftTestTool.swift
  Sources/Commands/TestingSupport.swift
  Sources/Workspace/UserToolchain.swift
  Tests/CommandsTests/PackageToolTests.swift
Labels: ready, 5.6

#4018 [5.6] Sandbox blocks output to default plugin output directory when it's under `<pkgdir>/.build`
  Sources/Basics/Sandbox.swift
  Tests/BasicsTests/SandboxTests.swift
Labels: ready, 5.6

#4022 [5.6] Package command plugins should have the same initial working directory as the invocation
  Sources/Commands/SwiftPackageTool.swift
  Sources/SPMBuildCore/PluginInvocation.swift
  Sources/Workspace/DefaultPluginScriptRunner.swift
  Tests/CommandsTests/PackageToolTests.swift
  Tests/FunctionalTests/PluginTests.swift
  Tests/SPMBuildCoreTests/PluginInvocationTests.swift
Labels: ready, 5.6

#4015 [5.6] Mark the SwiftPM 5.6 branch as a release branch
  Sources/Basics/SwiftVersion.swift
Labels: ready, 5.6

#4028 Don't emit a "this package dependency is unused" warning for packages that vend command plugins
  Sources/PackageGraph/PackageGraph+Loading.swift
  Tests/FunctionalTests/PluginTests.swift
Labels: ready

#4027 add a test for new binary artifact download concurrent download limit
  Sources/SPMTestSupport/MockWorkspace.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: ready

#4026 cleanup redundant maps
  Sources/PackageGraph/Pubgrub/PubgrubDependencyResolver.swift
  Sources/PackageLoading/PackageBuilder.swift
  Sources/Workspace/Workspace.swift
  Tests/PackageGraphTests/PubgrubTests.swift
  Tests/WorkspaceTests/RegistryPackageContainerTests.swift
  Tests/WorkspaceTests/SourceControlPackageContainerTests.swift
Labels: ready

#4011 manifest loading performance
  Sources/PackageLoading/ManifestLoader.swift
Labels: ready

#4031 [5.6] Don't emit "package dependency is unused" warning for packages containing command plugin products
  Sources/PackageGraph/PackageGraph+Loading.swift
  Tests/FunctionalTests/PluginTests.swift
Labels: ready, 5.6

#4030 improve dependency resolution diagnostics when resolving non-versioned dependencies
  Sources/Basics/Dictionary+Extensions.swift
  Sources/PackageGraph/DependencyResolutionNode.swift
  Sources/PackageGraph/Pubgrub/PubgrubDependencyResolver.swift
  Tests/PackageGraphTests/PubgrubTests.swift
Labels: ready

#4020 support binary artifact archives that require first level component stripping
  Sources/Basics/FileSystem+Extensions.swift
  Sources/Workspace/Workspace.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: ready

#4034 [5.6] SourceControl: avoid the builtin FS monitor (#4032)
  Sources/SourceControl/GitRepository.swift
Labels: 5.6

#4035 [5.6] support binary artifact archives that require first level component stripping (#4020)
  Sources/Basics/FileSystem+Extensions.swift
  Sources/Workspace/Workspace.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: ready, 5.6

#4037 Emit output and diagnostics from build tool plugin invocations as diagnostics
  Sources/Build/BuildOperation.swift
  Sources/SPMBuildCore/PluginInvocation.swift
  Tests/CommandsTests/PackageToolTests.swift
Labels: ready

#4039 Fix bugs in builds that are run from a command plugin
  Sources/Commands/SwiftPackageTool.swift
  Tests/CommandsTests/PackageToolTests.swift
Labels: ready

#4041 [5.6] Emit output and diagnostics from build tool plugin invocations as diagnostics
  Sources/Build/BuildOperation.swift
  Sources/SPMBuildCore/PluginInvocation.swift
  Tests/CommandsTests/PackageToolTests.swift
Labels: ready, 5.6

#4042 [5.6] Fix bugs in builds done on request from command plugins
  Sources/Commands/SwiftPackageTool.swift
  Tests/CommandsTests/PackageToolTests.swift
Labels: ready, 5.6

#4040 [5.6][Collections] Honor --config-path and --cache-path options
  Sources/Commands/SwiftPackageCollectionsTool.swift
  Sources/PackageCollections/PackageCollections+Configuration.swift
  Sources/PackageCollections/PackageCollections.swift
  Tests/PackageCollectionsSigningTests/CertificatePolicyTests.swift
  Tests/PackageCollectionsSigningTests/CertificateTests.swift
  Tests/PackageCollectionsSigningTests/KeyTests+EC.swift
  Tests/PackageCollectionsSigningTests/KeyTests+RSA.swift
  Tests/PackageCollectionsSigningTests/PackageCollectionSigningTest.swift
  Tests/PackageCollectionsSigningTests/SignatureTests.swift
  Tests/PackageCollectionsTests/GitHubPackageMetadataProviderTests.swift
  Tests/PackageCollectionsTests/JSONPackageCollectionProviderTests.swift
  Tests/PackageCollectionsTests/PackageCollectionsModelTests.swift
Labels: 5.6

#4045 [5.6] Fix the `Target.recursiveTargetDependencies` plugin API function
  Sources/PackagePlugin/PackageModel.swift
  Tests/CommandsTests/PackageToolTests.swift
Labels: ready, 5.6

#4048 improve observability error description interpolation, especially for manifest parsing error
  Sources/Basics/Observability.swift
  Sources/PackageLoading/ManifestLoader.swift
  Tests/BasicsTests/ObservabilitySystemTests.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: ready

#4049 do not use Dictionary::uniqueKeysWithValues when input is not sanitized
  Sources/Basics/Dictionary+Extensions.swift
  Sources/Commands/TestingSupport.swift
  Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift
  Sources/PackageFingerprint/FilePackageFingerprintStorage.swift
  Sources/PackageGraph/PackageGraph.swift
  Sources/Workspace/Workspace.swift
  Sources/XCBuildSupport/PIFBuilder.swift
  Sources/swiftpm-manifest-tool/main.swift
  Tests/BasicsTests/DictionaryTest.swift
  Tests/BuildTests/BuildPlanTests.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: ready

#4046 [5.6] Add function to check whether a file affects swift or clang build settings
  Sources/Workspace/Workspace.swift
Labels: 5.6

#3933 refactor workspace initializers
  Sources/Basics/FileSystem+Extensions.swift
  Sources/Commands/APIDigester.swift
  Sources/Commands/SwiftPackageRegistryTool.swift
  Sources/Commands/SwiftPackageTool.swift
  Sources/Commands/SwiftTool.swift
  Sources/PackageGraph/Pubgrub/PubgrubDependencyResolver.swift
  Sources/PackageRegistry/RegistryClient.swift
  Sources/SPMTestSupport/MockWorkspace.swift
  Sources/SPMTestSupport/misc.swift
  Sources/SourceControl/RepositoryManager.swift
  Sources/Workspace/Workspace.swift
  Sources/Workspace/WorkspaceConfiguration.swift
  Sources/Workspace/WorkspaceState.swift
  Tests/FunctionalTests/MiscellaneousTests.swift
  Tests/FunctionalTests/PluginTests.swift
  Tests/SPMBuildCoreTests/PluginInvocationTests.swift
  Tests/SourceControlTests/RepositoryManagerTests.swift
  Tests/WorkspaceTests/MirrorsConfigurationTests.swift
  Tests/WorkspaceTests/RegistryPackageContainerTests.swift
  Tests/WorkspaceTests/SourceControlPackageContainerTests.swift
  Tests/WorkspaceTests/WorkspaceStateTests.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: ready

#4056 [5.5] Update the Swift version to 5.5.3
  Sources/Basics/SwiftVersion.swift
Labels: ready, 5.5

#4059 cache registry downloads
  Sources/Commands/Options.swift
  Sources/Commands/SwiftTool.swift
  Sources/PackageRegistry/CMakeLists.txt
  Sources/PackageRegistry/RegistryClient.swift
  Sources/PackageRegistry/RegistryDownloadsManager.swift
  Sources/SPMTestSupport/MockRegistry.swift
  Sources/SPMTestSupport/MockWorkspace.swift
  Sources/SourceControl/RepositoryManager.swift
  Sources/Workspace/ToolsVersionSpecificationRewriter.swift
  Sources/Workspace/Workspace.swift
  Sources/Workspace/WorkspaceConfiguration.swift
  Tests/CommandsTests/PackageToolTests.swift
  Tests/PackageRegistryTests/RegistryClientTests.swift
  Tests/PackageRegistryTests/RegistryDownloadsManagerTests.swift
  Tests/SourceControlTests/RepositoryManagerTests.swift
  Tests/WorkspaceTests/RegistryPackageContainerTests.swift
  Tests/WorkspaceTests/SourceControlPackageContainerTests.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: ready

#4063 [5.6] Some cleanup related to package plugins (#4052)
  Fixtures/Miscellaneous/Plugins/ClientOfPluginWithInternalExecutable/Package.swift
  Fixtures/Miscellaneous/Plugins/ContrivedTestPlugin/Package.swift
  Fixtures/Miscellaneous/Plugins/ContrivedTestPlugin/Plugins/MyAmbiguouslyNamedCommandPlugin/plugin.swift
  Fixtures/Miscellaneous/Plugins/ContrivedTestPlugin/Plugins/MySourceGenBuildToolPlugin/plugin.swift
  Fixtures/Miscellaneous/Plugins/InvalidUseOfInternalPluginExecutable/Package.swift
  Fixtures/Miscellaneous/Plugins/MyBinaryToolPlugin/Package.swift
  Fixtures/Miscellaneous/Plugins/MyBinaryToolPlugin/Plugins/MySourceGenBuildToolPlugin/plugin.swift
  Fixtures/Miscellaneous/Plugins/MySourceGenClient/Package.swift
  Fixtures/Miscellaneous/Plugins/MySourceGenPlugin/Package.swift
  Fixtures/Miscellaneous/Plugins/MySourceGenPlugin/Plugins/MySourceGenBuildToolPlugin/plugin.swift
  Fixtures/Miscellaneous/Plugins/MySourceGenPlugin/Plugins/MySourceGenPrebuildPlugin/plugin.swift
  Fixtures/Miscellaneous/Plugins/PluginWithInternalExecutable/Package.swift
  Fixtures/Miscellaneous/Plugins/PluginWithInternalExecutable/Plugins/PluginScriptTarget/Script.swift
  Fixtures/Miscellaneous/Plugins/SandboxTesterPlugin/Package.swift
  Fixtures/Miscellaneous/Plugins/SandboxTesterPlugin/Plugins/MySourceGenBuildToolPlugin/plugin.swift
  Sources/PackagePlugin/Command.swift
  Sources/PackagePlugin/Context.swift
  Sources/PackagePlugin/Plugin.swift
  Sources/PackagePlugin/PluginInput.swift
  Sources/PackagePlugin/Protocols.swift
  Sources/SPMBuildCore/PluginInvocation.swift
  Tests/FunctionalTests/PluginTests.swift
Labels: ready, 5.6

#4047 [5.6] Make the `@main` entry points for plugins be `async` so it can call other `async` APIs
  Sources/PackagePlugin/Plugin.swift
  Sources/PackagePlugin/Protocols.swift
  Sources/SPMTestSupport/Toolchain.swift
  Sources/Workspace/DefaultPluginScriptRunner.swift
  Tests/CommandsTests/PackageToolTests.swift
  Tests/FunctionalTests/PluginTests.swift
Labels: ready, 5.6

#4065 [5.6] Simplify the command plugin method to get all the inputs in `arguments` instead of a specific targets parameter (#4055)
  Sources/Commands/SwiftPackageTool.swift
  Sources/PackagePlugin/Errors.swift
  Sources/PackagePlugin/PackageModel.swift
  Sources/PackagePlugin/Plugin.swift
  Sources/PackagePlugin/PluginInput.swift
  Sources/PackagePlugin/Protocols.swift
  Sources/SPMBuildCore/PluginInvocation.swift
  Tests/CommandsTests/PackageToolTests.swift
  Tests/FunctionalTests/PluginTests.swift
Labels: 5.6

#4066 [5.6] Make PackagePlugin Path.init() public, clean up conformances (#4058)
  Sources/PackagePlugin/Diagnostics.swift
  Sources/PackagePlugin/Path.swift
  Tests/CommandsTests/PackageToolTests.swift
  Tests/PackagePluginAPITests/PathTests.swift
Labels: 5.6
