Repository swiftlang/swift-package-manager, pull requests merged in 2022-06, with the labels that each got.

#5558 [5.6] Update the Swift version to 5.6.2
  Sources/Basics/SwiftVersion.swift
Labels: 5.6

#5561 [5.7] fix an edge case where dependency resolution can go into endless loop
  Sources/PackageGraph/Pubgrub/PubgrubDependencyResolver.swift
  Sources/SPMTestSupport/Observability.swift
  Tests/PackageGraphTests/PubgrubTests.swift
Labels: ready, 5.7

#5562 [5.7] fix mirrors reverse mapping to be more deterministic
  Sources/PackageGraph/DependencyMirrors.swift
  Tests/WorkspaceTests/PinsStoreTests.swift
Labels: ready, 5.7

#5570 Avoid emitting a `.info` diagnostic with an empty message when there is no compiler output at all (#5566)
  Sources/Workspace/DefaultPluginScriptRunner.swift
  Tests/FunctionalTests/PluginTests.swift
Labels: 5.7

#4203 consolidate and improve manifest validation
  Sources/Basics/Observability.swift
  Sources/PackageLoading/CMakeLists.txt
  Sources/PackageLoading/ManifestLoader+Validation.swift
  Sources/PackageLoading/ManifestLoader.swift
  Sources/Workspace/Workspace.swift
  Tests/FunctionalTests/MiscellaneousTests.swift
  Tests/PackageLoadingTests/PDLoadingTests.swift
  Tests/PackageLoadingTests/PD_4_0_LoadingTests.swift
  Tests/PackageLoadingTests/PD_4_2_LoadingTests.swift
  Tests/PackageLoadingTests/PD_5_0_LoadingTests.swift
  Tests/PackageLoadingTests/PD_5_2_LoadingTests.swift
  Tests/PackageLoadingTests/PD_5_3_LoadingTests.swift
  Tests/PackageLoadingTests/PD_5_4_LoadingTests.swift
  Tests/PackageLoadingTests/PD_5_5_LoadingTests.swift
  Tests/PackageLoadingTests/PD_5_6_LoadingTests.swift
  Tests/PackageLoadingTests/PD_5_7_LoadingTests .swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: ready, next

#5576 refactor LLBuildManifest graphviz file visualization flow
  Sources/Build/BuildOperation.swift
  Sources/Commands/CMakeLists.txt
  Sources/Commands/Options.swift
  Sources/Commands/SwiftBuildTool.swift
  Sources/Commands/SwiftTool.swift
  Sources/Commands/Utilities/APIDigester.swift
  Sources/Commands/Utilities/DOTManifestSerializer.swift
  Sources/Commands/Utilities/DependenciesSerializer.swift
  Sources/Commands/Utilities/Describe.swift
  Sources/Commands/Utilities/GenerateLinuxMain.swift
  Sources/Commands/Utilities/MultiRootSupport.swift
  Sources/Commands/Utilities/SymbolGraphExtract.swift
  Sources/Commands/Utilities/TestingSupport.swift
  Sources/Commands/Utilities/WatchmanHelper.swift
  Sources/LLBuildManifest/CMakeLists.txt
  Sources/SPMBuildCore/BuildParameters.swift
  Tests/CommandsTests/BuildToolTests.swift
Labels: ready

#5586 [5.7] Allow duplicate product names when module aliasing is used
  Sources/PackageGraph/CMakeLists.txt
  Sources/PackageGraph/ModuleAliasTracker.swift
  Sources/PackageGraph/PackageGraph+Loading.swift
  Sources/PackageLoading/PackageBuilder.swift
  Sources/PackageModel/Product.swift
  Sources/PackageModel/Target.swift
  Tests/BuildTests/BuildPlanTests.swift
  Tests/BuildTests/MockBuildTestHelper.swift
  Tests/BuildTests/ModuleAliasingBuildTests.swift
  Tests/FunctionalTests/ModuleAliasingFixtureTests.swift
Labels: 5.7

#5577 refactor stream output and progress bars (part 1)
  Sources/Build/BuildOperation.swift
  Sources/Commands/SwiftTool.swift
  Tests/CommandsTests/SwiftToolTests.swift
Labels: ready

#5600 [5.7] Module aliases override updates
  Sources/PackageGraph/ModuleAliasTracker.swift
  Sources/PackageGraph/PackageGraph+Loading.swift
  Tests/BuildTests/ModuleAliasingBuildTests.swift
Labels: 5.7

#5603 [5.7] Adjust SwiftPM 5.7 to minimum supported deployment target changes
  Sources/PackageDescription/SupportedPlatforms.swift
  Sources/PackageGraph/PackageGraph+Loading.swift
  Sources/PackageModel/Platform.swift
  Tests/BuildTests/BuildPlanTests.swift
  Tests/BuildTests/MockBuildTestHelper.swift
  Tests/PackageGraphTests/PackageGraphTests.swift
  Tests/XCBuildSupportTests/PIFBuilderTests.swift
Labels: 5.7

#5605 suppress warnings from remote dependencies
  Fixtures/Miscellaneous/DependenciesWarnings/app/Package.swift
  Fixtures/Miscellaneous/DependenciesWarnings/app/app.swift
  Fixtures/Miscellaneous/DependenciesWarnings/dep1/Package.swift
  Fixtures/Miscellaneous/DependenciesWarnings/dep1/code.swift
  Fixtures/Miscellaneous/DependenciesWarnings/dep2/Package.swift
  Fixtures/Miscellaneous/DependenciesWarnings/dep2/code.swift
  Sources/Build/BuildPlan.swift
  Tests/FunctionalTests/MiscellaneousTests.swift
Labels: ready

#5608 [5.7] suppress warnings from remote dependencies
  Fixtures/Miscellaneous/DependenciesWarnings/app/Package.swift
  Fixtures/Miscellaneous/DependenciesWarnings/app/app.swift
  Fixtures/Miscellaneous/DependenciesWarnings/dep1/Package.swift
  Fixtures/Miscellaneous/DependenciesWarnings/dep1/code.swift
  Fixtures/Miscellaneous/DependenciesWarnings/dep2/Package.swift
  Fixtures/Miscellaneous/DependenciesWarnings/dep2/code.swift
  Sources/Build/BuildPlan.swift
  Tests/FunctionalTests/MiscellaneousTests.swift
Labels: ready, 5.7

#5607 [5.7] Add diagnostics to use module aliasing when duplicate targets found
  Sources/PackageLoading/PackageBuilder.swift
  Tests/PackageGraphTests/PackageGraphTests.swift
Labels: 5.7

#5629 [5.7] Validation of package products should check that a library product doesn't try to include executable targets (#5625)
  Fixtures/Miscellaneous/PackageWithMalformedLibraryProduct/Package.swift
  Fixtures/Miscellaneous/PackageWithMalformedLibraryProduct/Sources/PackageWithMalformedLibraryProduct/main.swift
  Sources/PackageLoading/Diagnostics.swift
  Sources/PackageLoading/PackageBuilder.swift
  Tests/FunctionalTests/MiscellaneousTests.swift
Labels: ready, 5.7

#5622 [5.7] Modify driver invocation on `swift run --repl` to match new REPL behavior.
  Sources/Build/BuildPlan.swift
  Tests/BuildTests/BuildPlanTests.swift
Labels: 5.7

#5631 [5.7] Fix typo in in-source docs for Target (#5624)
  Sources/PackageDescription/Target.swift
Labels: 5.7
