Repository swiftlang/swift-package-manager, pull requests merged in 2022-04, with the labels that each got.

#4279 [5.6] Remove use of `AbsolutePath.appending(RelativePath(_:))`
  Fixtures/CFamilyTargets/CLibraryParentSearchPath/.gitignore
  Fixtures/CFamilyTargets/CLibraryParentSearchPath/Package.swift
  Fixtures/CFamilyTargets/CLibraryParentSearchPath/Sources/CHeaderInclude/answers.c
  Fixtures/CFamilyTargets/CLibraryParentSearchPath/Sources/CHeaderInclude/include/answers.h
  Fixtures/CFamilyTargets/CLibraryParentSearchPath/Sources/Constants/Constants.h
  Fixtures/CFamilyTargets/CLibraryParentSearchPath/Sources/HeaderInclude/FinalForm.swift
  Sources/Build/BuildPlan.swift
  Sources/Commands/SwiftPackageTool.swift
  Sources/PackageLoading/ManifestJSONParser.swift
  Sources/PackageLoading/MinimumDeploymentTarget.swift
  Sources/PackageLoading/TargetSourcesBuilder.swift
  Sources/SPMBuildCore/BinaryTarget+Extensions.swift
  Sources/SPMBuildCore/Toolchain.swift
  Sources/SPMTestSupport/MockRegistry.swift
  Sources/SPMTestSupport/MockWorkspace.swift
  Sources/SPMTestSupport/misc.swift
  Sources/Workspace/InitPackage.swift
  Sources/Workspace/UserToolchain.swift
  Sources/Workspace/Workspace.swift
  Sources/XCBuildSupport/PIFBuilder.swift
  Sources/XCBuildSupport/XcodeBuildSystem.swift
  Sources/Xcodeproj/SchemesGenerator.swift
  Sources/Xcodeproj/generate.swift
  Tests/FunctionalTests/CFamilyTargetTests.swift
Labels: 5.6

#4070 Getting Started with Plugins document
  Documentation/Plugins.md
Labels: ready

#4288 [5.7] Fix ArgumentExtractor implementation bug (#4287)
  Sources/PackagePlugin/ArgumentExtractor.swift
  Tests/PackagePluginAPITests/ArgumentExtractorTests.swift
Labels: 5.7

#4296 [5.7] update CommandTaskTracker to match llbuild's reporting of CustomTasks
  Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
Labels: 5.7

#4303 [5.7] Module aliasing: validate source files / only allow Swift files for modules aliased
  Sources/PackageGraph/PackageGraph+Loading.swift
  Sources/PackageGraph/PackageGraph.swift
  Sources/PackageModel/Sources.swift
  Tests/BuildTests/BuildPlanTests.swift
Labels: 5.7

#4308 [5.7] The `shouldDisableSandbox` setting wasn't being passed along to build tool plugin commands (#4283)
  Fixtures/Miscellaneous/Plugins/SandboxViolatingBuildToolPluginCommands/MyLibrary/Package.swift
  Fixtures/Miscellaneous/Plugins/SandboxViolatingBuildToolPluginCommands/MyLibrary/Sources/MyLibrary/library.swift
  Fixtures/Miscellaneous/Plugins/SandboxViolatingBuildToolPluginCommands/MyPlugin/Package.swift
  Fixtures/Miscellaneous/Plugins/SandboxViolatingBuildToolPluginCommands/MyPlugin/Plugins/PackageScribblerPlugin/plugin.swift
  Sources/Commands/SwiftTool.swift
  Tests/FunctionalTests/PluginTests.swift
Labels: 5.7

#4309 [5.7] Clean up the code and some of the API of compiling plugins, and improve persistence of cached compiler outputs (#4290 & #4299)
  Sources/Basics/JSON+Extensions.swift
  Sources/Build/BuildOperation.swift
  Sources/SPMBuildCore/PluginInvocation.swift
  Sources/SPMBuildCore/PluginScriptRunner.swift
  Sources/Workspace/DefaultPluginScriptRunner.swift
  Tests/SPMBuildCoreTests/PluginInvocationTests.swift
Labels: 5.7

#4305 [5.7] Change default FingerprintCheckingMode to 'strict'
  Sources/Commands/Options.swift
  Sources/Workspace/Workspace+Configuration.swift
  Sources/Workspace/Workspace.swift
  Tests/PackageRegistryTests/RegistryClientTests.swift
Labels: 5.7

#4302 Restore unsupported tools-version error
  Sources/PackageLoading/ToolsVersionParser.swift
Labels: ready

#4314 [5.7] Make 'PackageCollectionsSigningLibc' target conditional
  Package.swift
Labels: 5.7

#4315 [5.6] Make 'PackageCollectionsSigningLibc' target conditional
  Package.swift
Labels: 5.6

#4306 Handle generated resources from plugins
  Fixtures/Miscellaneous/PluginGeneratedResources/Package.swift
  Fixtures/Miscellaneous/PluginGeneratedResources/Plugins/Generator/plugin.swift
  Fixtures/Miscellaneous/PluginGeneratedResources/Sources/PluginGeneratedResources/PluginGeneratedResources.swift
  Sources/Build/BuildOperation.swift
  Sources/Build/BuildPlan.swift
  Sources/Build/LLBuildManifestBuilder.swift
  Sources/Commands/SwiftTool.swift
  Sources/PackageLoading/PackageBuilder.swift
  Sources/PackageLoading/TargetSourcesBuilder.swift
  Sources/PackageModel/Target.swift
  Sources/SPMBuildCore/PrebuildCommandResult.swift
  Tests/FunctionalTests/MiscellaneousTests.swift
  Tests/PackageGraphTests/TargetTests.swift
Labels: ready

#4318 [5.7] Handle generated resources from plugins
  Fixtures/Miscellaneous/PluginGeneratedResources/Package.swift
  Fixtures/Miscellaneous/PluginGeneratedResources/Plugins/Generator/plugin.swift
  Fixtures/Miscellaneous/PluginGeneratedResources/Sources/PluginGeneratedResources/PluginGeneratedResources.swift
  Sources/Build/BuildOperation.swift
  Sources/Build/BuildPlan.swift
  Sources/Build/LLBuildManifestBuilder.swift
  Sources/Commands/SwiftTool.swift
  Sources/PackageLoading/PackageBuilder.swift
  Sources/PackageLoading/TargetSourcesBuilder.swift
  Sources/PackageModel/Target.swift
  Sources/SPMBuildCore/PrebuildCommandResult.swift
  Tests/FunctionalTests/MiscellaneousTests.swift
  Tests/PackageGraphTests/TargetTests.swift
Labels: 5.7

#4323 [5.7] Speculatively work around issue with linking concurrency libs
  Examples/package-info/Package.swift
  Examples/package-info/Sources/package-info/example.swift
  Examples/package-info/Sources/package-info/main.swift
  Sources/Workspace/Workspace.swift
Labels: 5.7

#4325 [5.7] rdar://92275318 (Swift CI Unblock:OSS - Swift Incremental RA - macOS - Apple Silicon - testPluginGeneratedResources Failure)
  Tests/FunctionalTests/MiscellaneousTests.swift
Labels: 5.7

#4326 [5.7] Updated the links that point to using Swift packages with Xcode. (#4324)
  Sources/PackageDescription/PackageDescription.docc/PackageDescription.md
Labels: 5.7
