Repository swiftlang/swift-package-manager, pull requests merged in 2022-03, with the labels that each got.

#4181 http client to support configurable max concurrent requests
  Sources/Basics/ConcurrencyHelpers.swift
  Sources/Basics/Errors.swift
  Sources/Basics/HTPClient+URLSession.swift
  Sources/Basics/HTTPClient.swift
  Sources/Workspace/Workspace.swift
  Tests/BasicsTests/HTTPClientTests.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: ready

#4185 refactor how plugins call the build system when using the CLI
  Sources/Commands/SwiftPackageTool.swift
  Sources/Commands/SwiftTool.swift
Labels: ready

#4187 add reference to SE-0303 in 5.6 changelog
  CHANGELOG.md
Labels: ready

#4188 update docker setup
  Utilities/Docker/Dockerfile
  Utilities/Docker/docker-compose.2004.56.yaml
  Utilities/Docker/docker-compose.yaml
Labels: ready

#4190 refactor CLI options
  Sources/Commands/Options.swift
  Sources/Commands/SwiftBuildTool.swift
  Sources/Commands/SwiftPackageCollectionsTool.swift
  Sources/Commands/SwiftPackageRegistryTool.swift
  Sources/Commands/SwiftPackageTool.swift
  Sources/Commands/SwiftRunTool.swift
  Sources/Commands/SwiftTestTool.swift
  Sources/Commands/SwiftTool.swift
  Sources/Commands/TestingSupport.swift
  Tests/CommandsTests/BuildToolTests.swift
  Tests/CommandsTests/SwiftToolTests.swift
Labels: ready

#4194 work around argument parser usage synopsis issue
  Sources/Commands/Options.swift
Labels: ready

#4197 factor binary dependencies handling outside workspace class [nfc]
  Sources/Commands/SwiftPackageTool.swift
  Sources/PackageLoading/ManifestLoader.swift
  Sources/SPMTestSupport/MockWorkspace.swift
  Sources/Workspace/CMakeLists.txt
  Sources/Workspace/Workspace+BinaryArtifacts.swift
  Sources/Workspace/Workspace+Configuration.swift
  Sources/Workspace/Workspace+State.swift
  Sources/Workspace/Workspace.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: ready

#4198 fix a bug in resolving registry dependencies with alternative manifest versions
  Sources/Workspace/RegistryPackageContainer.swift
  Tests/WorkspaceTests/RegistryPackageContainerTests.swift
Labels: ready

#4204 improve validation and error message for mismatch between binary target and artifact name
  Sources/Commands/SwiftTool.swift
  Sources/PackageGraph/PackageGraph+Loading.swift
  Sources/PackageLoading/PackageBuilder.swift
  Sources/SPMTestSupport/misc.swift
  Sources/Workspace/Diagnostics.swift
  Sources/Workspace/Workspace+BinaryArtifacts.swift
  Sources/Workspace/Workspace.swift
  Tests/BuildTests/BuildPlanTests.swift
  Tests/PackageGraphPerformanceTests/PackageGraphPerfTests.swift
  Tests/PackageLoadingTests/PackageBuilderTests.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
  Tests/XCBuildSupportTests/PIFBuilderTests.swift
Labels: ready

#4191 expose both raw and derived platform support information
  Sources/Build/BuildPlan.swift
  Sources/PackageGraph/PackageGraph+Loading.swift
  Sources/PackageGraph/ResolvedPackage.swift
  Sources/PackageGraph/ResolvedProduct.swift
  Sources/PackageGraph/ResolvedTarget.swift
  Sources/PackageLoading/PackageBuilder.swift
  Sources/PackageLoading/PkgConfig.swift
  Sources/PackageLoading/TargetSourcesBuilder.swift
  Sources/PackageModel/Platform.swift
  Sources/PackageModel/Target.swift
  Sources/SPMTestSupport/PackageGraphTester.swift
  Sources/SPMTestSupport/misc.swift
  Sources/Workspace/Workspace.swift
  Sources/XCBuildSupport/PIFBuilder.swift
  Sources/Xcodeproj/pbxproj.swift
  Tests/BuildTests/BuildPlanTests.swift
  Tests/CommandsTests/PackageToolTests.swift
  Tests/PackageGraphTests/PackageGraphTests.swift
  Tests/PackageGraphTests/TargetTests.swift
  Tests/PackageLoadingTests/PackageBuilderTests.swift
  Tests/SPMBuildCoreTests/PluginInvocationTests.swift
  Tests/XCBuildSupportTests/PIFBuilderTests.swift
  Tests/XcodeprojTests/GenerateXcodeprojTests.swift
  Tests/XcodeprojTests/PackageGraphTests.swift
Labels: ready

#4195 improve location CLI options
  Sources/Commands/APIDigester.swift
  Sources/Commands/Options.swift
  Sources/Commands/SwiftPackageTool.swift
  Sources/Commands/SwiftTool.swift
  Sources/SPMTestSupport/MockWorkspace.swift
  Sources/Workspace/Workspace+Configuration.swift
  Sources/Workspace/Workspace.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: ready

#4207 tools-version APIs refactoring
  Sources/Basics/HTTPClient.swift
  Sources/Basics/SwiftVersion.swift
  Sources/Commands/SwiftBuildTool.swift
  Sources/Commands/SwiftPackageCollectionsTool.swift
  Sources/Commands/SwiftPackageRegistryTool.swift
  Sources/Commands/SwiftPackageTool.swift
  Sources/Commands/SwiftRunTool.swift
  Sources/Commands/SwiftTestTool.swift
  Sources/PackageLoading/CMakeLists.txt
  Sources/PackageLoading/ManifestLoader.swift
  Sources/PackageLoading/PackageBuilder.swift
  Sources/PackageLoading/TargetSourcesBuilder.swift
  Sources/PackageLoading/ToolsVersionParser.swift
  Sources/PackageModel/Package.swift
  Sources/PackageModel/Target.swift
  Sources/PackageModel/ToolsVersion.swift
  Sources/PackageRegistry/RegistryClient.swift
  Sources/SPMBuildCore/BuildParameters.swift
  Sources/SPMTestSupport/MockManifestLoader.swift
  Sources/SPMTestSupport/MockPackageContainer.swift
  Sources/SPMTestSupport/MockRegistry.swift
  Sources/SPMTestSupport/MockWorkspace.swift
  Sources/Workspace/FileSystemPackageContainer.swift
  Sources/Workspace/InitPackage.swift
  Sources/Workspace/RegistryPackageContainer.swift
  Sources/Workspace/ResolverPrecomputationProvider.swift
  Sources/Workspace/SourceControlPackageContainer.swift
  Sources/Workspace/ToolsVersionSpecificationRewriter.swift
  Sources/Workspace/Workspace.swift
  Tests/FunctionalTests/ToolsVersionTests.swift
  Tests/FunctionalTests/VersionSpecificTests.swift
  Tests/PackageGraphTests/PubgrubTests.swift
  Tests/PackageLoadingPerformanceTests/ManifestLoadingTests.swift
  Tests/PackageLoadingTests/ManifestLoaderSQLiteCacheTests.swift
  Tests/PackageLoadingTests/PDLoadingTests.swift
  Tests/PackageLoadingTests/PD_4_0_LoadingTests.swift
  Tests/PackageLoadingTests/PD_4_2_LoadingTests.swift
  Tests/PackageLoadingTests/PD_5_0_LoadingTests.swift
  Tests/PackageLoadingTests/PackageBuilderTests.swift
  Tests/PackageLoadingTests/TargetSourcesBuilderTests.swift
  Tests/PackageLoadingTests/ToolsVersionParserTests.swift
  Tests/PackageRegistryTests/RegistryClientTests.swift
  Tests/WorkspaceTests/ManifestSourceGenerationTests.swift
  Tests/WorkspaceTests/PinsStoreTests.swift
  Tests/WorkspaceTests/RegistryPackageContainerTests.swift
  Tests/WorkspaceTests/SourceControlPackageContainerTests.swift
  Tests/WorkspaceTests/ToolsVersionSpecificationRewriterTests.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: ready

#4173 cancellation handler
  Sources/Basics/Archiver+Zip.swift
  Sources/Basics/CMakeLists.txt
  Sources/Basics/Cancellator.swift
  Sources/Basics/ConcurrencyHelpers.swift
  Sources/Basics/DispatchTimeInterval+Extensions.swift
  Sources/Basics/HTTPClient.swift
  Sources/Build/BuildOperation.swift
  Sources/Commands/APIDigester.swift
  Sources/Commands/SwiftPackageTool.swift
  Sources/Commands/SwiftTestTool.swift
  Sources/Commands/SwiftTool.swift
  Sources/PackageRegistry/RegistryClient.swift
  Sources/PackageRegistry/RegistryDownloadsManager.swift
  Sources/SPMBuildCore/BuildSystem.swift
  Sources/SPMTestSupport/GitRepositoryExtensions.swift
  Sources/SPMTestSupport/InMemoryGitRepository.swift
  Sources/SourceControl/GitRepository.swift
  Sources/SourceControl/Repository.swift
  Sources/SourceControl/RepositoryManager.swift
  Sources/Workspace/Workspace+BinaryArtifacts.swift
  Sources/Workspace/Workspace.swift
  Sources/XCBuildSupport/XcodeBuildSystem.swift
  Sources/Xcodeproj/generate.swift
  Tests/BasicsTests/CancellatorTests.swift
  Tests/BasicsTests/HTTPClientTests.swift
  Tests/BasicsTests/ZipArchiverTests.swift
  Tests/SourceControlTests/GitRepositoryProviderTests.swift
  Tests/SourceControlTests/GitRepositoryTests.swift
  Tests/SourceControlTests/RepositoryManagerTests.swift
  Tests/WorkspaceTests/SourceControlPackageContainerTests.swift
  Tests/XcodeprojTests/GenerateXcodeprojTests.swift
Labels: ready

#4244 make registry dependencies available in 5.7
  Sources/PackageDescription/PackageDependency.swift
  Tests/PackageLoadingTests/PD_5_7_LoadingTests .swift
  Tests/PackageLoadingTests/PD_Next_LoadingTests.swift
Labels: ready

#4245 ignore empty configuration files in legacy check
  Sources/Basics/FileSystem+Extensions.swift
  Sources/Workspace/Workspace+Configuration.swift
Labels: ready

#4251 add a test case to make sure binary artifact is deleted when download fails
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: ready

#4250 add test fixture for handling SIGINT on "swift run"
  Fixtures/Miscellaneous/SwiftRun/Package.swift
  Fixtures/Miscellaneous/SwiftRun/main.swift
  Tests/FunctionalTests/MiscellaneousTests.swift
Labels: ready

#4234 [5.6] Re-add class name to '__allTests' for test discovery
  Fixtures/Miscellaneous/TestDiscovery/Subclass/Package.swift
  Fixtures/Miscellaneous/TestDiscovery/Subclass/Sources/Subclass/Subclass.swift
  Fixtures/Miscellaneous/TestDiscovery/Subclass/Tests/SubclassTests/SubclassTestsBase.swift
  Fixtures/Miscellaneous/TestDiscovery/Subclass/Tests/SubclassTests/SubclassTestsDerived.swift
  Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
  Tests/FunctionalTests/TestDiscoveryTests.swift
Labels: 5.6

#4239 [5.6] Remove binary target downloads on failure
  Sources/Workspace/Workspace.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: 5.6

#4246 [5.6] Package plugin dependency on executable product from different package doesn't find the tool (#4200)
  Fixtures/Miscellaneous/Plugins/LibraryWithLocalBuildToolPluginUsingRemoteTool/Package.swift
  Fixtures/Miscellaneous/Plugins/LibraryWithLocalBuildToolPluginUsingRemoteTool/Plugins/MyLocalSourceGenBuildToolPlugin/plugin.swift
  Fixtures/Miscellaneous/Plugins/LibraryWithLocalBuildToolPluginUsingRemoteTool/Sources/MyLibrary/generated.dat
  Fixtures/Miscellaneous/Plugins/LibraryWithLocalBuildToolPluginUsingRemoteTool/Sources/MyLibrary/library.swift
  Fixtures/Miscellaneous/Plugins/LibraryWithLocalBuildToolPluginUsingRemoteTool/Tests/MyLibraryTests/test.swift
  Sources/SPMBuildCore/PluginInvocation.swift
  Tests/FunctionalTests/PluginTests.swift
Labels: 5.6

#4231 [5.6] Fix SIGINT handling during `swift run` (Cherry-pick of #4224, #4235, #4250)
  Fixtures/Miscellaneous/SwiftRun/Package.swift
  Fixtures/Miscellaneous/SwiftRun/main.swift
  Sources/Commands/SwiftTool.swift
  Tests/FunctionalTests/MiscellaneousTests.swift
Labels: 5.6

#4128 troubleshoot module aliasing
  Tests/FunctionalTests/ModuleAliasingTests.swift
Labels: DO NOT MERGE

#4263 update example to use async await APIs
  Examples/package-info/Package.swift
  Examples/package-info/Sources/package-info/example.swift
  Examples/package-info/Sources/package-info/main.swift
  Sources/Workspace/Workspace.swift
Labels: ready
