Repository swiftlang/swift-package-manager, pull requests merged in 2023-10, with the labels that each got.

#6971 [NFC] Build/Commands: fix `triple` property deprecation warnings
  Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
  Sources/Commands/SwiftTestTool.swift
Labels: cross-compilation

#6973 [5.9] improve validation of existing checkouts
  Sources/SPMTestSupport/InMemoryGitRepository.swift
  Sources/SourceControl/GitRepository.swift
  Sources/SourceControl/Repository.swift
  Sources/SourceControl/RepositoryManager.swift
  Sources/Workspace/Workspace.swift
  Tests/SourceControlTests/GitRepositoryTests.swift
  Tests/SourceControlTests/RepositoryManagerTests.swift
Labels: swift 5.9

#6772 Patch `*.sdk` paths from pkgConfig files to the current SDK
  Sources/Build/BuildOperation.swift
  Sources/Build/BuildPlan.swift
  Sources/Commands/PackageTools/PluginCommand.swift
  Sources/PackageLoading/Target+PkgConfig.swift
  Sources/PackageModel/Toolchain.swift
  Sources/SPMBuildCore/PluginContextSerializer.swift
  Sources/SPMBuildCore/PluginInvocation.swift
  Sources/XCBuildSupport/PIFBuilder.swift
  Sources/XCBuildSupport/XcodeBuildSystem.swift
  Tests/BuildTests/MockBuildTestHelper.swift
  Tests/FunctionalTests/PluginTests.swift
  Tests/PackageLoadingTests/PkgConfigAllowlistTests.swift
  Tests/SPMBuildCoreTests/PluginInvocationTests.swift
  Tests/XCBuildSupportTests/PIFBuilderTests.swift
Labels: system libraries

#6975 [NFC] LLBuildManifest: add `WriteAuxiliary.EntitlementPlist`
  .swiftpm/xcode/xcshareddata/xcschemes/SwiftPM-Package.xcscheme
  Package.swift
  Sources/LLBuildManifest/BuildManifest.swift
  Sources/LLBuildManifest/Node.swift
  Sources/LLBuildManifest/Tools.swift
  Tests/LLBuildManifestTests/LLBuildManifestTests.swift
Labels: enhancement

#6972 [NFC] Build/PackageModel: split `Target.swift` and `BuildPlan.swift`
  Sources/Build/BuildDescription/ProductBuildDescription.swift
  Sources/Build/BuildManifest/LLBuildManifestBuilder+Product.swift
  Sources/Build/BuildManifest/LLBuildManifestBuilder+Swift.swift
  Sources/Build/BuildManifest/LLBuildManifestBuilder.swift
  Sources/Build/BuildPlan.swift
  Sources/Build/BuildPlan/BuildPlan+Clang.swift
  Sources/Build/BuildPlan/BuildPlan+Product.swift
  Sources/Build/BuildPlan/BuildPlan+Swift.swift
  Sources/Build/BuildPlan/BuildPlan+Test.swift
  Sources/Build/BuildPlan/BuildPlan.swift
  Sources/Build/CMakeLists.txt
  Sources/PackageModel/CMakeLists.txt
  Sources/PackageModel/Target.swift
  Sources/PackageModel/Target/BinaryTarget.swift
  Sources/PackageModel/Target/ClangTarget.swift
  Sources/PackageModel/Target/PluginTarget.swift
  Sources/PackageModel/Target/SwiftTarget.swift
  Sources/PackageModel/Target/SystemLibraryTarget.swift
  Sources/PackageModel/Target/Target.swift
Labels: build system, no functional change

#6708 Fix Swift SDK handling URLs without filename components
  Fixtures/SwiftSDKs/test-sdk.artifactbundle.tar.gz
  Sources/Basics/FileSystem/FileSystem+Extensions.swift
  Sources/Commands/SwiftBuildTool.swift
  Sources/CoreCommands/SwiftTool.swift
  Sources/PackageModel/ArtifactsArchiveMetadata.swift
  Sources/PackageModel/CMakeLists.txt
  Sources/PackageModel/SwiftSDKBundle.swift
  Sources/PackageModel/SwiftSDKs/SwiftSDK.swift
  Sources/PackageModel/SwiftSDKs/SwiftSDKBundle.swift
  Sources/PackageModel/SwiftSDKs/SwiftSDKBundleStore.swift
  Sources/PackageModel/SwiftSDKs/SwiftSDKConfigurationStore.swift
  Sources/PackageRegistryTool/PackageRegistryTool.swift
  Sources/SwiftSDKTool/Configuration/ConfigurationSubcommand.swift
  Sources/SwiftSDKTool/InstallSwiftSDK.swift
  Sources/SwiftSDKTool/ListSwiftSDKs.swift
  Sources/SwiftSDKTool/RemoveSwiftSDK.swift
  Sources/SwiftSDKTool/SwiftSDKSubcommand.swift
  Tests/PackageModelTests/SwiftSDKBundleTests.swift
  Tests/SPMBuildCoreTests/PluginInvocationTests.swift
Labels: bug, cross-compilation

#6991 [5.9] Handle macOS CLT `--show-sdk-platform-path` issues
  Sources/Commands/SwiftTestTool.swift
  Sources/CoreCommands/SwiftTool.swift
  Sources/PackageModel/Destination.swift
Labels: swift 5.9

#6986 Tests: cover testing multiple async executable targets
  Fixtures/Miscellaneous/TestableAsyncExe/Package.swift
  Fixtures/Miscellaneous/TestableAsyncExe/Sources/TestableAsyncExe1/main.swift
  Fixtures/Miscellaneous/TestableAsyncExe/Sources/TestableAsyncExe2/main.swift
  Fixtures/Miscellaneous/TestableAsyncExe/Sources/TestableAsyncExe3/NonMain.swift
  Fixtures/Miscellaneous/TestableAsyncExe/Sources/TestableAsyncExe4/NonMain.swift
  Fixtures/Miscellaneous/TestableAsyncExe/Tests/TestableAsyncExeTests/TestableAsyncExeTests.swift
  Tests/FunctionalTests/MiscellaneousTests.swift
Labels: next

#6999 [NFC] Fix deprecation in `IntegrationTests/SwiftPMTests.swift`
  IntegrationTests/Tests/IntegrationTests/SwiftPMTests.swift
Labels: no functional change

#7000 [NFC] Move manifests-related code to `Workspace+Manifests.swift`
  Sources/Workspace/CMakeLists.txt
  Sources/Workspace/PackageContainer/FileSystemPackageContainer.swift
  Sources/Workspace/PackageContainer/RegistryPackageContainer.swift
  Sources/Workspace/PackageContainer/SourceControlPackageContainer.swift
  Sources/Workspace/Workspace+Manifests.swift
  Sources/Workspace/Workspace.swift
Labels: no functional change

#7008 [NFC] Fix typos in `PluginScriptRunner.swift` comments
  Sources/SPMBuildCore/Plugins/PluginScriptRunner.swift
Labels: no functional change

#7012 Remove outdated check for Ubuntu 14.04 and Clang 3.6
  Sources/Commands/SwiftBuildTool.swift
Labels: dependencies

#7013 Add trailing newlines consistently in `InitPackage.swift`
  Sources/Workspace/InitPackage.swift
Labels: bug

#7019 [NFC] Remove unused imports of `TSCUtility.Diagnostics{Engine,}`
  Tests/PackageLoadingTests/PD_4_2_LoadingTests.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: no functional change

#7018 SwiftSyntax version in new macro template has trailing period in dependency version, causing error reading manifest
  Sources/PackageModel/InstalledSwiftPMConfiguration.swift
  Tests/PackageModelTests/InstalledSwiftPMConfigurationTests.swift
Labels: bug

#7017 [NFC] Build: remove unused `TestBuildCommand.indent` function
  Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
Labels: no functional change

#7020 llbuild: Support `is-mutated`/`is-command-timestamp` nodes
  Sources/Build/BuildManifest/LLBuildManifestBuilder+Swift.swift
  Sources/Build/BuildManifest/LLBuildManifestBuilder.swift
  Sources/Build/BuildOperation.swift
  Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
  Sources/Commands/Utilities/DOTManifestSerializer.swift
  Sources/LLBuildManifest/CMakeLists.txt
  Sources/LLBuildManifest/LLBuildManifest.swift
  Sources/LLBuildManifest/LLBuildManifestWriter.swift
  Sources/LLBuildManifest/ManifestWriter.swift
  Sources/LLBuildManifest/Node.swift
  Sources/LLBuildManifest/Tools.swift
  Tests/LLBuildManifestTests/LLBuildManifestTests.swift
Labels: build system, no functional change

#7014 Update iOS/tvOS deployment targets according to the SDKs
  Sources/PackageModel/Platform.swift
  Tests/BuildTests/BuildPlanTests.swift
  Tests/PackageGraphTests/PackageGraphTests.swift
  Tests/XCBuildSupportTests/PIFBuilderTests.swift
Labels: bug, dependencies

#7010 Codesign w/ debugging entitlement for backtraces on macOS
  CHANGELOG.md
  Sources/Build/BuildDescription/ProductBuildDescription.swift
  Sources/Build/BuildManifest/LLBuildManifestBuilder+Product.swift
  Sources/Build/BuildManifest/LLBuildManifestBuilder.swift
  Sources/CoreCommands/Options.swift
  Sources/CoreCommands/SwiftTool.swift
  Sources/SPMBuildCore/BuildParameters/BuildParameters+Debugging.swift
  Sources/SPMBuildCore/BuildParameters/BuildParameters.swift
  Sources/SPMBuildCore/CMakeLists.txt
  Tests/BuildTests/LLBuildManifestBuilderTests.swift
  Tests/BuildTests/MockBuildTestHelper.swift
  Tests/CommandsTests/BuildToolTests.swift
Labels: enhancement

#7031 Revert "refine location comparison when pre-loading package (#7002)"
  Sources/PackageGraph/PubGrub/ContainerProvider.swift
  Sources/PackageModel/PackageIdentity.swift
  Sources/PackageModel/PackageReference.swift
  Sources/Workspace/ManagedDependency.swift
  Sources/Workspace/Workspace+Dependencies.swift
  Sources/Workspace/Workspace+Manifests.swift
  Sources/Workspace/Workspace+Pinning.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: bug

#7028 [NFC] CoreCommands: simplify `*get-task-allow-entitlement` flags
  Sources/CoreCommands/Options.swift
  Sources/CoreCommands/SwiftTool.swift
Labels: no functional change

#7040 Ensure Xcode SDK paths are set when running test targets.
  Sources/Commands/Utilities/TestingSupport.swift
Labels: bug

#7041 Infer properties of derived test target.
  Sources/Build/BuildPlan/BuildPlan+Test.swift
  Sources/PackageGraph/ResolvedProduct.swift
Labels: bug
