Repository swiftlang/swift-package-manager, pull requests merged in 2023-02, with the labels that each got.

#6022 Add `async`-friendly `actor HTTPClient`
  Sources/Basics/AuthorizationProvider.swift
  Sources/Basics/CMakeLists.txt
  Sources/Basics/FileSystem/TemporaryFile.swift
  Sources/Basics/HTTPClient+URLSession.swift
  Sources/Basics/HTTPClient/HTTPClient.swift
  Sources/Basics/HTTPClient/HTTPClientConfiguration.swift
  Sources/Basics/HTTPClient/HTTPClientError.swift
  Sources/Basics/HTTPClient/HTTPClientHeaders.swift
  Sources/Basics/HTTPClient/HTTPClientRequest.swift
  Sources/Basics/HTTPClient/HTTPClientResponse.swift
  Sources/Basics/HTTPClient/HTTPMethod.swift
  Sources/Basics/HTTPClient/LegacyHTTPClient.swift
  Sources/Basics/HTTPClient/LegacyHTTPClientRequest.swift
  Sources/Basics/HTTPClient/URLSessionHTTPClient.swift
  Sources/Basics/SendableTimeInterval.swift
  Sources/PackageCollections/PackageIndex.swift
  Sources/PackageCollections/Providers/GitHubPackageMetadataProvider.swift
  Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift
  Sources/PackageCollectionsSigning/Certificate/CertificatePolicy.swift
  Sources/PackageRegistry/RegistryClient.swift
  Sources/SPMTestSupport/MockHTTPClient.swift
  Sources/SPMTestSupport/MockRegistry.swift
  Sources/SPMTestSupport/MockWorkspace.swift
  Sources/Workspace/Workspace+BinaryArtifacts.swift
  Tests/BasicsTests/FileSystem/TemporaryFileTests.swift
  Tests/BasicsTests/FileSystem/VFSTests.swift
  Tests/BasicsTests/HTTPClientTests.swift
  Tests/BasicsTests/LegacyHTTPClientTests.swift
  Tests/BasicsTests/URLSessionHTTPClientTests.swift
  Tests/PackageCollectionsTests/GitHubPackageMetadataProviderTests.swift
  Tests/PackageCollectionsTests/JSONPackageCollectionProviderTests.swift
  Tests/PackageCollectionsTests/PackageIndexTests.swift
  Tests/PackageRegistryTests/RegistryClientTests.swift
  Tests/WorkspaceTests/RegistryPackageContainerTests.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: concurrency

#6099 PackageModel: add `Sendable` conformance to `Manifest`
  Sources/Basics/Concurrency/ConcurrencyHelpers.swift
  Sources/Basics/Concurrency/ThreadSafeKeyValueStore.swift
  Sources/PackageModel/CMakeLists.txt
  Sources/PackageModel/Manifest/Manifest.swift
  Sources/PackageModel/Manifest/PackageConditionDescription.swift
  Sources/PackageModel/Manifest/PackageDependencyDescription.swift
  Sources/PackageModel/Manifest/PlatformDescription.swift
  Sources/PackageModel/Manifest/ProductDescription.swift
  Sources/PackageModel/Manifest/SystemPackageProviderDescription.swift
  Sources/PackageModel/Manifest/TargetBuildSettingDescription.swift
  Sources/PackageModel/Manifest/TargetDescription.swift
  Sources/PackageModel/PackageIdentity.swift
  Sources/PackageModel/PackageReference.swift
  Sources/PackageModel/Product.swift
  Sources/PackageModel/SwiftLanguageVersion.swift
  Sources/PackageModel/ToolsVersion.swift
  Sources/SourceControl/Repository.swift
Labels: concurrency

#6107 Add missing `TSCUtility.Version` import
  Sources/Commands/ToolWorkspaceDelegate.swift
  Sources/PackageCollections/Model/PackageTypes.swift
  Sources/PackageCollections/Model/TargetListResult.swift
  Sources/PackageCollections/PackageCollections+Validation.swift
  Sources/PackageCollections/Providers/GitHubPackageMetadataProvider.swift
  Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift
  Sources/PackageCollections/Providers/PackageMetadataProvider.swift
  Sources/PackageCollectionsTool/SwiftPackageCollectionsTool.swift
  Sources/PackageFingerprint/FilePackageFingerprintStorage.swift
  Sources/PackageFingerprint/PackageFingerprintStorage.swift
  Sources/PackageGraph/DependencyResolver.swift
  Sources/PackageGraph/PinsStore.swift
  Sources/PackageGraph/PubGrub/PubGrubDependencyResolver.swift
  Sources/PackageGraph/PubGrub/PubGrubPackageContainer.swift
  Sources/PackageLoading/ManifestJSONParser.swift
  Sources/PackageLoading/ManifestLoader.swift
  Sources/PackageLoading/ToolsVersionParser.swift
  Sources/PackageMetadata/PackageMetadata.swift
  Sources/PackageRegistry/RegistryClient.swift
  Sources/PackageRegistry/RegistryDownloadsManager.swift
  Sources/SPMTestSupport/ManifestExtensions.swift
  Sources/SPMTestSupport/MockManifestLoader.swift
  Sources/SPMTestSupport/MockPackageFingerprintStorage.swift
  Sources/SPMTestSupport/MockRegistry.swift
  Sources/SPMTestSupport/MockWorkspace.swift
  Sources/SPMTestSupport/PackageDependencyDescriptionExtensions.swift
  Sources/Workspace/FileSystemPackageContainer.swift
  Sources/Workspace/ManagedDependency.swift
  Sources/Workspace/RegistryPackageContainer.swift
  Sources/Workspace/ResolverPrecomputationProvider.swift
  Sources/Workspace/SourceControlPackageContainer.swift
  Sources/Workspace/Workspace+State.swift
  Sources/Workspace/Workspace.swift
  Tests/PackageCollectionsTests/GitHubPackageMetadataProviderTests.swift
  Tests/PackageCollectionsTests/PackageCollectionsTests.swift
  Tests/PackageCollectionsTests/PackageIndexAndCollectionsTests.swift
  Tests/PackageCollectionsTests/Utility.swift
  Tests/PackageFingerprintTests/FilePackageFingerprintStorageTests.swift
  Tests/PackageGraphTests/PubgrubTests.swift
  Tests/PackageRegistryTests/RegistryClientTests.swift
  Tests/PackageRegistryTests/RegistryDownloadsManagerTests.swift
  Tests/WorkspaceTests/PinsStoreTests.swift
  Tests/WorkspaceTests/RegistryPackageContainerTests.swift
  Tests/WorkspaceTests/SourceControlPackageContainerTests.swift
  Tests/WorkspaceTests/ToolsVersionSpecificationGenerationTests.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: bug

#6108 [5.8] Fix manifest source generation for `enableUpcomingFeature`/`enableExp…
  Sources/PackageDescription/BuildSettings.swift
  Sources/PackageLoading/ManifestJSONParser.swift
  Sources/PackageLoading/PackageBuilder.swift
  Sources/PackageModel/Manifest/TargetBuildSettingDescription.swift
  Sources/PackageModel/ManifestSourceGeneration.swift
  Tests/BuildTests/BuildPlanTests.swift
  Tests/PackageGraphTests/PackageGraphTests.swift
Labels: 5.8

#6112 [5.8] improve registry identity lookup cache
  Sources/PackageRegistry/RegistryClient.swift
  Sources/Workspace/Workspace.swift
  Tests/PackageRegistryTests/RegistryClientTests.swift
Labels: 5.8

#6115 [5.8] allow mirror between source control and registry dependencies
  Sources/PackageGraph/DependencyMirrors.swift
  Sources/PackageLoading/ManifestJSONParser.swift
  Sources/PackageModel/IdentityResolver.swift
  Sources/SPMTestSupport/MockDependency.swift
  Sources/SPMTestSupport/MockPackage.swift
  Sources/SPMTestSupport/MockTarget.swift
  Sources/SPMTestSupport/MockWorkspace.swift
  Sources/Workspace/Workspace.swift
  Tests/CommandsTests/PackageToolTests.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: 5.8

#6117 [5.8] PackageModel: partially address #5719
  Sources/PackageModel/UserToolchain.swift
  Tests/PackageModelTests/PackageModelTests.swift
Labels: 5.8

#6133 Fix `MockHashAlgorithm` conformance to `Sendable`
  Sources/Basics/Concurrency/ThreadSafeArrayStore.swift
  Sources/SPMTestSupport/MockHashAlgorithm.swift
Labels: concurrency

#6156 [5.8][Registry] Make 'Content-Version' optional for archive and manifest download API
  Documentation/Registry.md
  Sources/PackageRegistry/RegistryClient.swift
  Tests/PackageRegistryTests/RegistryClientTests.swift
Labels: 5.8

#6173 [5.8] Init template cleanup (#6144)
  CHANGELOG.md
  Documentation/Usage.md
  IntegrationTests/Tests/IntegrationTests/BasicTests.swift
  IntegrationTests/Tests/IntegrationTests/SwiftPMTests.swift
  Sources/Commands/PackageTools/Init.swift
  Sources/Workspace/InitPackage.swift
  Tests/CommandsTests/PackageToolTests.swift
  Tests/WorkspaceTests/InitTests.swift
Labels: 5.8

#6194 CrossCompilationDestinationsTool: fix `install` command help formatting
  Sources/CrossCompilationDestinationsTool/InstallDestination.swift
Labels: bug

#6195 PackageModel/Toolset: fix support for relative `rootPath`
  Sources/PackageModel/Toolset.swift
  Tests/PackageModelTests/ToolsetTests.swift
Labels: bug
