Repository swiftlang/swift-package-manager, pull requests merged in 2023-01, with the labels that each got.

#5996 [5.8] SwiftPM outputs raw diagnostics from SwiftDriver without trailing newlines
  Sources/Build/SwiftCompilerOutputParser.swift
  Tests/BuildTests/SwiftCompilerOutputParserTests.swift
  Tests/CommandsTests/BuildToolTests.swift
Labels: 5.8

#6013 [5.8] There's no need to pretty-print the JSON that a compiled manifest sent back to SwiftPM (#5995)
  Sources/PackageDescription/PackageDescription.swift
Labels: 5.8

#6001 Set `isDevelopment` to false for the release branch
  Sources/Basics/SwiftVersion.swift
Labels: 5.8

#5993 5.8: set `relatedDependenciesBranch` to 5.8 in `Package.swift`
  Package.swift
Labels: 5.8

#6014 main.swift: fix `swift-experimental-destination` invocation
  Sources/swift-package-manager/main.swift
Labels: bug

#6024 [5.8] remove an unnecessary import
  Sources/PackageGraph/PinsStore.swift
Labels: 5.8

#6025 [5.8] Pass through the package identity as a parameter to `willLoadManifest`/`didLoadManifest` callbacks (#6019
  Sources/Commands/ToolWorkspaceDelegate.swift
  Sources/CoreCommands/MinimalBuildTool.swift
  Sources/SPMTestSupport/MockWorkspace.swift
  Sources/Workspace/Workspace.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: 5.8

#6033 Basics: don't point users to bugs.swift.org with `InternalError`
  Sources/Basics/Errors.swift
Labels: bug

#6036 PackagePlugin: fix typo in `PackageManagerProxyError` case
  Sources/PackagePlugin/PackageManagerProxy.swift
Labels: bug

#6035 BuildPlan: provide user-actionable error description for `.noBuildableTarget`
  Sources/Build/BuildPlan.swift
Labels: enhancement

#6042 [5.8] update purge cache to warn when failing to delete files
  Sources/PackageLoading/ManifestLoader.swift
  Sources/PackageRegistry/RegistryDownloadsManager.swift
  Sources/SPMTestSupport/MockManifestLoader.swift
  Sources/SourceControl/RepositoryManager.swift
  Sources/Workspace/Workspace.swift
  Tests/PackageLoadingTests/PD_4_2_LoadingTests.swift
  Tests/PackageRegistryTests/RegistryDownloadsManagerTests.swift
  Tests/SourceControlTests/RepositoryManagerTests.swift
  Tests/WorkspaceTests/RegistryPackageContainerTests.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: 5.8

#6039 [5.8] PackagePlugin: fix typo in `PackageManagerProxyError` case
  Sources/PackagePlugin/PackageManagerProxy.swift
Labels: bug, 5.8

#6015 [5.8] main.swift: fix `swift-experimental-destination` invocation
  Sources/swift-package-manager/main.swift
Labels: bug, 5.8

#6064 [5.8] Enable use of product ID to distinguish duplicate product names
  Sources/PackageGraph/PackageGraph+Loading.swift
  Sources/PackageModel/PackageModel.swift
  Sources/PackageModel/Target.swift
  Tests/BuildTests/BuildPlanTests.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: 5.8

#6051 [5.8] Sanitize environment for XCBuild
  Sources/XCBuildSupport/XcodeBuildSystem.swift
Labels: 5.8

#6055 [5.8] Disable implementationOnly Foundation import for resource accessor
  CHANGELOG.md
  Documentation/ReleaseNotes/5.8.md
  Sources/Build/BuildPlan.swift
Labels: 5.8

#6073 [5.8] Enable Foundation-less manifests
  Sources/PackageLoading/ManifestLoader.swift
Labels: 5.8

#6070 [5.8] Warn instead of error when non-Swift sources may be included in a target that has module aliases
  Sources/PackageGraph/ModuleAliasTracker.swift
  Sources/PackageGraph/PackageGraph+Loading.swift
  Sources/PackageGraph/PackageGraph.swift
  Tests/BuildTests/ModuleAliasingBuildTests.swift
Labels: 5.8

#6058 [NFC] Basics: add `actor AsyncFileSystem` wrapper over `FileSystem`
  Sources/Basics/Archiver+Zip.swift
  Sources/Basics/CMakeLists.txt
  Sources/Basics/FileSystem/AsyncFileSystem.swift
  Sources/Basics/FileSystem/FileSystem+Extensions.swift
  Sources/Basics/FileSystem/TemporaryFile.swift
  Sources/Basics/FileSystem/VFSOverlay.swift
  Sources/Basics/FileSystem/VirtualFileSystem.swift
  Tests/BasicsTests/FileSystem/AsyncFileSystemTests.swift
  Tests/BasicsTests/FileSystem/FileSystemTests.swift
  Tests/BasicsTests/FileSystem/TemporaryFileTests.swift
  Tests/BasicsTests/FileSystem/VFSTests.swift
Labels: concurrency

#6085 [NFC] Basics: add `SendableBox` and `TokenBucket` helpers
  .swiftformat
  Package.swift
  Sources/Basics/CMakeLists.txt
  Sources/Basics/Concurrency/ConcurrencyHelpers.swift
  Sources/Basics/Concurrency/NSLock+Extensions.swift
  Sources/Basics/Concurrency/SendableBox.swift
  Sources/Basics/Concurrency/ThreadSafeArrayStore.swift
  Sources/Basics/Concurrency/ThreadSafeBox.swift
  Sources/Basics/Concurrency/ThreadSafeKeyValueStore.swift
  Sources/Basics/Concurrency/TokenBucket.swift
  Sources/Basics/ConcurrencyHelpers.swift
  Sources/Basics/FileSystem/AsyncFileSystem.swift
Labels: concurrency

#6088 Rename `-enable-future-feature` to `-enable-upcoming-feature` (#6084)
  Sources/PackageLoading/PackageBuilder.swift
  Tests/BuildTests/BuildPlanTests.swift
Labels: 5.8
