Repository swiftlang/swift-package-manager, pull requests merged in 2023-07, with the labels that each got.

#6666 Add support for Musl libc
  Fixtures/DependencyResolution/External/Complex/FisherYates/src/Fisher-Yates_Shuffle.swift
  Fixtures/Miscellaneous/EchoExecutable/Sources/secho/main.swift
  Sources/Basics/Cancellator.swift
  Sources/CoreCommands/SwiftTool.swift
  Sources/PackageDescription/PackageDescription.swift
  Tests/PackageLoadingTests/PD_5_3_LoadingTests.swift
Labels: linux

#6678 Update Swift SDK nomenclature
  Sources/CoreCommands/SwiftTool.swift
  Sources/PackageModel/Destination.swift
  Sources/PackageModel/SwiftSDKBundle.swift
  Sources/PackageModel/SwiftSDKConfigurationStore.swift
  Sources/SwiftSDKTool/Configuration/ConfigurationSubcommand.swift
  Sources/SwiftSDKTool/Configuration/ResetConfiguration.swift
  Sources/SwiftSDKTool/Configuration/SetConfiguration.swift
  Sources/SwiftSDKTool/Configuration/ShowConfiguration.swift
  Sources/SwiftSDKTool/InstallSwiftSDK.swift
  Sources/SwiftSDKTool/ListSwiftSDKs.swift
  Sources/SwiftSDKTool/RemoveSwiftSDK.swift
  Sources/SwiftSDKTool/SwiftSDKSubcommand.swift
  Tests/BuildTests/BuildPlanTests.swift
  Tests/PackageModelTests/DestinationTests.swift
  Tests/PackageModelTests/SwiftSDKBundleTests.swift
Labels: cross-compilation

#6679 [5.9] Update Swift SDK nomenclature
  Sources/CoreCommands/SwiftTool.swift
  Sources/PackageModel/Destination.swift
  Sources/PackageModel/SwiftSDKBundle.swift
  Sources/PackageModel/SwiftSDKConfigurationStore.swift
  Sources/SwiftSDKTool/Configuration/ConfigurationSubcommand.swift
  Sources/SwiftSDKTool/Configuration/ResetConfiguration.swift
  Sources/SwiftSDKTool/Configuration/SetConfiguration.swift
  Sources/SwiftSDKTool/Configuration/ShowConfiguration.swift
  Sources/SwiftSDKTool/InstallSwiftSDK.swift
  Sources/SwiftSDKTool/ListSwiftSDKs.swift
  Sources/SwiftSDKTool/RemoveSwiftSDK.swift
  Sources/SwiftSDKTool/SwiftSDKSubcommand.swift
  Tests/PackageModelTests/DestinationTests.swift
  Tests/PackageModelTests/SwiftSDKBundleTests.swift
Labels: 5.9, cross-compilation

#6707 [NFC] Rename `Destination` type to `SwiftSDK`
  Sources/Build/BuildDescription/ClangTargetBuildDescription.swift
  Sources/Build/BuildDescription/ProductBuildDescription.swift
  Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift
  Sources/Build/BuildOperation.swift
  Sources/Build/BuildPlan.swift
  Sources/Commands/PackageTools/APIDiff.swift
  Sources/Commands/PackageTools/DumpCommands.swift
  Sources/Commands/PackageTools/PluginCommand.swift
  Sources/Commands/SwiftRunTool.swift
  Sources/Commands/SwiftTestTool.swift
  Sources/Commands/Utilities/PluginDelegate.swift
  Sources/Commands/Utilities/TestingSupport.swift
  Sources/CoreCommands/SwiftTool.swift
  Sources/PackageLoading/ManifestLoader.swift
  Sources/PackageModel/CMakeLists.txt
  Sources/PackageModel/SwiftSDK.swift
  Sources/PackageModel/SwiftSDKBundle.swift
  Sources/PackageModel/SwiftSDKConfigurationStore.swift
  Sources/PackageModel/UserToolchain.swift
  Sources/SPMBuildCore/BuildParameters.swift
  Sources/SPMTestSupport/Toolchain.swift
  Sources/SwiftSDKTool/Configuration/ConfigurationSubcommand.swift
  Sources/SwiftSDKTool/Configuration/ResetConfiguration.swift
  Sources/SwiftSDKTool/Configuration/SetConfiguration.swift
  Sources/SwiftSDKTool/Configuration/ShowConfiguration.swift
  Sources/SwiftSDKTool/SwiftSDKSubcommand.swift
  Sources/Workspace/DefaultPluginScriptRunner.swift
  Sources/Workspace/Workspace+BinaryArtifacts.swift
  Sources/Workspace/Workspace.swift
  Sources/XCBuildSupport/XcodeBuildSystem.swift
  Sources/swift-bootstrap/main.swift
  Tests/BuildTests/BuildPlanTests.swift
  Tests/BuildTests/MockBuildTestHelper.swift
  Tests/CommandsTests/BuildToolTests.swift
  Tests/CommandsTests/PackageToolTests.swift
  Tests/FunctionalPerformanceTests/BuildPerfTests.swift
  Tests/FunctionalTests/CFamilyTargetTests.swift
  Tests/FunctionalTests/DependencyResolutionTests.swift
  Tests/FunctionalTests/MiscellaneousTests.swift
  Tests/FunctionalTests/ModuleAliasingFixtureTests.swift
  Tests/FunctionalTests/ModuleMapTests.swift
  Tests/FunctionalTests/ToolsVersionTests.swift
  Tests/PackageLoadingTests/PD_5_0_LoadingTests.swift
  Tests/PackageModelTests/DestinationTests.swift
  Tests/PackageModelTests/PackageModelTests.swift
  Tests/SPMBuildCoreTests/PluginInvocationTests.swift
  Tests/WorkspaceTests/InitTests.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: cross-compilation

#6714 [5.9] Don't link plugin dependencies to products
  Fixtures/Miscellaneous/Plugins/IncorrectDependencies/Package.swift
  Fixtures/Miscellaneous/Plugins/IncorrectDependencies/Plugins/MyPlugin/MyPlugin.swift
  Fixtures/Miscellaneous/Plugins/IncorrectDependencies/Sources/MyExecutable/MyExecutable.swift
  Fixtures/Miscellaneous/Plugins/IncorrectDependencies/Sources/MyLibrary/Empty.swift
  Fixtures/Miscellaneous/Plugins/IncorrectDependencies/Sources/MyPluginExecutable/MyPluginExecutable.swift
  Fixtures/Miscellaneous/Plugins/IncorrectDependencies/Tests/MyExecutableTests/MyExecutableTests.swift
  Sources/Build/BuildPlan.swift
  Tests/FunctionalTests/PluginTests.swift
Labels: 5.9

#6715 [5.9] Preserve port when computing the login URL
  Sources/PackageRegistry/RegistryClient.swift
  Sources/PackageRegistry/RegistryConfiguration.swift
  Sources/PackageRegistryTool/PackageRegistryTool+Auth.swift
  Tests/CommandsTests/PackageRegistryToolTests.swift
  Tests/PackageRegistryTests/RegistryConfigurationTests.swift
Labels: 5.9

#6720 [5.9] Enable armv7em CPU and none OS triples
  Sources/Basics/Triple.swift
  Sources/Build/BuildDescription/ProductBuildDescription.swift
  Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift
  Sources/Build/BuildOperation.swift
  Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
  Sources/Build/LLBuildManifestBuilder.swift
  Sources/Commands/PackageTools/PluginCommand.swift
  Sources/Commands/Utilities/PluginDelegate.swift
  Sources/PackageLoading/PackageBuilder.swift
  Sources/SPMBuildCore/BinaryTarget+Extensions.swift
  Sources/SPMBuildCore/BuildParameters.swift
  Sources/SPMBuildCore/BuildSystem.swift
  Sources/XCBuildSupport/XcodeBuildSystem.swift
  Tests/BuildTests/BuildPlanTests.swift
  Tests/BuildTests/ModuleAliasingBuildTests.swift
Labels: 5.9, cross-compilation

#6724 [5.9] Transition away from `Foundation.URL`
  Sources/Basics/CMakeLists.txt
  Sources/Basics/SourceControlURL.swift
  Sources/PackageCollections/PackageCollections+Validation.swift
  Sources/PackageCollections/Providers/GitHubPackageMetadataProvider.swift
  Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift
  Sources/PackageFingerprint/FilePackageFingerprintStorage.swift
  Sources/PackageFingerprint/Model.swift
  Sources/PackageGraph/DependencyMirrors.swift
  Sources/PackageGraph/PinsStore.swift
  Sources/PackageLoading/ManifestJSONParser.swift
  Sources/PackageLoading/RegistryReleaseMetadataSerialization.swift
  Sources/PackageMetadata/PackageMetadata.swift
  Sources/PackageModel/IdentityResolver.swift
  Sources/PackageModel/Manifest/PackageDependencyDescription.swift
  Sources/PackageModel/PackageIdentity.swift
  Sources/PackageModel/PackageReference.swift
  Sources/PackageModel/RegistryReleaseMetadata.swift
  Sources/PackageRegistry/RegistryClient.swift
  Sources/SPMTestSupport/ManifestExtensions.swift
  Sources/SPMTestSupport/MockDependency.swift
  Sources/SPMTestSupport/MockPackage.swift
  Sources/SPMTestSupport/MockWorkspace.swift
  Sources/SPMTestSupport/PackageDependencyDescriptionExtensions.swift
  Sources/SourceControl/GitRepository.swift
  Sources/SourceControl/Repository.swift
  Sources/Workspace/Workspace+State.swift
  Sources/Workspace/Workspace.swift
  Tests/PackageCollectionsTests/GitHubPackageMetadataProviderTests.swift
  Tests/PackageCollectionsTests/PackageIndexTests.swift
  Tests/PackageFingerprintTests/FilePackageFingerprintStorageTests.swift
  Tests/PackageGraphTests/PubgrubTests.swift
  Tests/PackageLoadingTests/PD_5_6_LoadingTests.swift
  Tests/PackageLoadingTests/TargetSourcesBuilderTests.swift
  Tests/PackageRegistryTests/PackageVersionChecksumTOFUTests.swift
  Tests/PackageRegistryTests/RegistryClientTests.swift
  Tests/SourceControlTests/RepositoryManagerTests.swift
  Tests/WorkspaceTests/PinsStoreTests.swift
  Tests/WorkspaceTests/SourceControlPackageContainerTests.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: 5.9

#6722 [5.9] fix `apple` and `darwin` triples disambiguation
  Sources/Basics/Triple.swift
  Sources/Build/BuildDescription/ProductBuildDescription.swift
  Sources/Build/BuildPlan.swift
  Sources/PackageModel/UserToolchain.swift
  Sources/SPMBuildCore/BuildParameters.swift
  Tests/BasicsTests/TripleTests.swift
Labels: bug, 5.9, cross-compilation

#6726 [5.9] Fix issues with excluding macros/plugins from dependency computation
  Fixtures/Miscellaneous/Plugins/MySourceGenPlugin/Package.swift
  Sources/Build/BuildPlan.swift
Labels: 5.9

#6709 [5.9] Improve handling of tool build flags
  Sources/Build/BuildDescription/ClangTargetBuildDescription.swift
  Sources/Build/BuildDescription/ProductBuildDescription.swift
  Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift
  Sources/Build/BuildPlan.swift
  Sources/CoreCommands/SwiftTool.swift
  Sources/PackageModel/BuildFlags.swift
  Sources/PackageModel/UserToolchain.swift
  Sources/XCBuildSupport/XcodeBuildSystem.swift
  Tests/BuildTests/BuildPlanTests.swift
  Tests/BuildTests/MockBuildTestHelper.swift
Labels: 5.9, cross-compilation

#6730 Add `SerializedJSON` type as string literal escaping helper
  Sources/Basics/ByteString+Extensions.swift
  Sources/Basics/CMakeLists.txt
  Sources/Basics/FileSystem/NativePathExtensions.swift
  Sources/Basics/Serialization/SerializedJSON.swift
  Tests/BasicsTests/Serialization/SerializedJSONTests.swift
  Tests/PackageModelTests/SwiftSDKBundleTests.swift
  Tests/PackageModelTests/SwiftSDKTests.swift
  Tests/PackageModelTests/ToolsetTests.swift
Labels: cross-compilation, test suite

#6729 [5.9] Fix CMake build to explicitly pick up ar and ranlib from toolchain.
  Utilities/bootstrap
Labels: 5.9

#6741 [5.9] Fix triples parsed by Driver not accepted by SwiftPM
  Package.swift
  Sources/Basics/CMakeLists.txt
  Sources/Basics/Triple+Basics.swift
  Sources/Basics/Triple.swift
  Sources/Basics/Vendor/README.md
  Sources/Basics/Vendor/Triple+Platforms.swift
  Sources/Basics/Vendor/Triple.swift
  Sources/PackageModel/UserToolchain.swift
  Sources/SPMBuildCore/BinaryTarget+Extensions.swift
  Sources/XCBuildSupport/XcodeBuildSystem.swift
  Tests/BasicsTests/TripleTests.swift
  Tests/FunctionalTests/MiscellaneousTests.swift
Labels: 5.9, cross-compilation

#6740 [5.9] Swift SDKs: fix search paths handling
  Sources/Build/BuildDescription/ClangTargetBuildDescription.swift
  Sources/Build/BuildDescription/ProductBuildDescription.swift
  Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift
  Sources/PackageModel/Toolchain.swift
  Sources/PackageModel/UserToolchain.swift
  Tests/BuildTests/BuildPlanTests.swift
  Tests/BuildTests/MockBuildTestHelper.swift
Labels: 5.9, cross-compilation

#6739 [5.9] Keychain credentials - better support for protocol and port
  Sources/Basics/AuthorizationProvider.swift
  Tests/BasicsTests/AuthorizationProviderTests.swift
Labels: 5.9

#6746 [5.9] Add availability to source module APIs
  Sources/PackagePlugin/PackageModel.swift
  Sources/PackagePlugin/Utilities.swift
  Tests/CommandsTests/PackageToolTests.swift
Labels: 5.9

#6749 [5.9] Keychain search to return all matches
  Sources/Basics/AuthorizationProvider.swift
Labels: 5.9

#6753 [5.9] Fix an XCBuild compatibility issue
  Sources/XCBuildSupport/PIF.swift
  Sources/XCBuildSupport/PIFBuilder.swift
Labels: 5.9

#6754 Fix CMake build to explicitly pick up ar and ranlib from toolchain.
  Utilities/bootstrap
Labels: 5.8
