Repository swiftlang/swift-package-manager, pull requests merged in 2023-05, with the labels that each got.

#6467 [5.9] Change TargetGroup enum param to packageAccess bool in target declaration
  Fixtures/Miscellaneous/TargetGrouping/libPkg/Package.swift
  Fixtures/Miscellaneous/TargetPackageAccess/libPkg/Package.swift
  Fixtures/Miscellaneous/TargetPackageAccess/libPkg/Sources/Core/Core.swift
  Fixtures/Miscellaneous/TargetPackageAccess/libPkg/Sources/DataManager/File.swift
  Fixtures/Miscellaneous/TargetPackageAccess/libPkg/Sources/DataModel/File.swift
  Fixtures/Miscellaneous/TargetPackageAccess/libPkg/Sources/ExampleApp/main.swift
  Fixtures/Miscellaneous/TargetPackageAccess/libPkg/Sources/MainLib/Lib.swift
  Fixtures/Miscellaneous/TargetPackageAccess/libPkg/Tests/BlackBoxTests/BlackBoxTests.swift
  Fixtures/Miscellaneous/TargetPackageAccess/libPkg/Tests/MainLibTests/MainLibTests.swift
  Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift
  Sources/Build/BuildPlan.swift
  Sources/CompilerPluginSupport/TargetExtensions.swift
  Sources/PackageDescription/PackageDescriptionSerialization.swift
  Sources/PackageDescription/PackageDescriptionSerializationConversion.swift
  Sources/PackageDescription/Target.swift
  Sources/PackageGraph/ResolvedProduct.swift
  Sources/PackageGraph/ResolvedTarget.swift
  Sources/PackageLoading/ManifestJSONParser.swift
  Sources/PackageLoading/ManifestLoader.swift
  Sources/PackageLoading/PackageBuilder.swift
  Sources/PackageModel/Manifest/TargetDescription.swift
  Sources/PackageModel/Target.swift
  Sources/SPMTestSupport/MockTarget.swift
  Sources/Workspace/Workspace.swift
  Tests/BuildTests/BuildPlanTests.swift
  Tests/PackageGraphTests/PackageGraphTests.swift
  Tests/PackageGraphTests/TargetTests.swift
  Tests/PackageLoadingTests/PD_5_3_LoadingTests.swift
Labels: 5.9

#6484 [5.9] Support macro targets in plugin context
  Sources/PackagePlugin/PackageModel.swift
  Sources/PackagePlugin/PluginContextDeserializer.swift
  Sources/PackagePlugin/PluginMessages.swift
  Sources/SPMBuildCore/PluginContextSerializer.swift
Labels: 5.9

#6488 [5.9] improve string interpolation of errors
  Sources/Basics/AuthorizationProvider.swift
  Sources/Basics/Cancellator.swift
  Sources/Basics/Errors.swift
  Sources/Basics/Observability.swift
  Sources/Basics/Triple.swift
  Sources/Build/BuildOperation.swift
  Sources/Commands/PackageTools/APIDiff.swift
  Sources/PackageCollections/PackageCollections.swift
  Sources/PackageCollections/PackageIndex.swift
  Sources/PackageCollections/Providers/GitHubPackageMetadataProvider.swift
  Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift
  Sources/PackageCollections/Storage/SQLitePackageCollectionsStorage.swift
  Sources/PackageCollectionsSigning/Certificate/CertificatePolicy.swift
  Sources/PackageCollectionsSigning/PackageCollectionSigning.swift
  Sources/PackageGraph/PinsStore.swift
  Sources/PackageLoading/ManifestJSONParser.swift
  Sources/PackageLoading/ManifestLoader.swift
  Sources/PackageLoading/Target+PkgConfig.swift
  Sources/PackageModel/ArtifactsArchiveMetadata.swift
  Sources/PackageModel/SwiftSDKBundle.swift
  Sources/PackageModel/Toolset.swift
  Sources/PackageModel/UserToolchain.swift
  Sources/PackageModel/WindowsToolchainInfo.swift
  Sources/PackageRegistry/ChecksumTOFU.swift
  Sources/PackageRegistry/RegistryClient.swift
  Sources/PackageRegistry/RegistryDownloadsManager.swift
  Sources/PackageRegistry/SignatureValidation.swift
  Sources/PackageRegistry/SigningEntityTOFU.swift
  Sources/PackageRegistryTool/PackageRegistryTool.swift
  Sources/PackageSigning/SignatureProvider.swift
  Sources/PackageSigning/SigningIdentity.swift
  Sources/SPMBuildCore/PluginContextSerializer.swift
  Sources/SPMBuildCore/PluginInvocation.swift
  Sources/SPMBuildCore/XCFrameworkMetadata.swift
  Sources/SPMLLBuild/llbuild.swift
  Sources/SPMTestSupport/MockWorkspace.swift
  Sources/SPMTestSupport/XCTAssertHelpers.swift
  Sources/SPMTestSupport/misc.swift
  Sources/SourceControl/RepositoryManager.swift
  Sources/Workspace/DefaultPluginScriptRunner.swift
  Sources/Workspace/SourceControlPackageContainer.swift
  Sources/Workspace/Workspace+BinaryArtifacts.swift
  Sources/Workspace/Workspace+Configuration.swift
  Sources/Workspace/Workspace+State.swift
  Sources/Workspace/Workspace.swift
  Sources/XCBuildSupport/PIFBuilder.swift
Labels: next, 5.9

#6495 [5.9] fix VersionSetSpecifier calculation for versions with pre-release identifiers
  Sources/PackageGraph/PubGrub/PartialSolution.swift
  Sources/PackageGraph/PubGrub/PubGrubDependencyResolver.swift
  Sources/PackageGraph/Version+Extensions.swift
  Tests/PackageGraphTests/PubgrubTests.swift
  Tests/PackageGraphTests/VersionSetSpecifierTests.swift
Labels: next, 5.9

#6505 [5.9] Fix use of XCTest minimum deployment target
  Sources/PackageGraph/PackageGraph+Loading.swift
  Tests/PackageGraphTests/PackageGraphTests.swift
Labels: 5.9

#6511 [5.9] Cherry-pick documentation updates
  Sources/PackageDescription/BuildSettings.swift
  Sources/PackageDescription/PackageDependency.swift
  Sources/PackageDescription/PackageDescription.docc/Curation/Extensions/Product-Executable.md
  Sources/PackageDescription/PackageDescription.docc/Curation/Platform.md
  Sources/PackageDescription/PackageDescription.docc/Curation/Plugin.md
  Sources/PackageDescription/PackageDescription.docc/Curation/PluginPermission.md
  Sources/PackageDescription/PackageDescription.docc/Curation/Product.md
  Sources/PackageDescription/PackageDescription.docc/Curation/SupportedPlatforms.md
  Sources/PackageDescription/PackageDescription.docc/Curation/Target-Dependency.md
  Sources/PackageDescription/PackageDescription.swift
  Sources/PackageDescription/PackageDescriptionSerializationConversion.swift
  Sources/PackageDescription/Product.swift
  Sources/PackageDescription/Resource.swift
  Sources/PackageDescription/SupportedPlatforms.swift
  Sources/PackageDescription/Target.swift
Labels: documentation, 5.9

#6514 [5.9] 🍒Allow enabling C++ interop without explicit version (#6416)
  Sources/PackageDescription/BuildSettings.swift
  Sources/PackageLoading/PackageBuilder.swift
  Tests/BuildTests/BuildPlanTests.swift
Labels: 5.9

#6426 Fix Swift SDK bundles not working due to quarantine
  Sources/Basics/FileSystem/FileSystem+Extensions.swift
  Sources/PackageModel/Destination.swift
  Sources/PackageModel/SwiftSDKBundle.swift
Labels: bug

#6542 [5.9] Remove 10.15 fallback for manifest/plugin compilation
  Sources/PackageLoading/ManifestLoader.swift
  Sources/PackageModel/ToolchainConfiguration.swift
  Sources/Workspace/DefaultPluginScriptRunner.swift
Labels: 5.9

#6540 [5.9] Run build tool plugins for C-family targets
  Sources/Build/BuildDescription/ClangTargetBuildDescription.swift
  Sources/Build/BuildDescription/SharedTargetBuildDescription.swift
  Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift
  Sources/Build/BuildDescription/TargetBuildDescription.swift
  Sources/Build/BuildPlan.swift
  Sources/Build/CMakeLists.txt
  Sources/Build/LLBuildManifestBuilder.swift
Labels: 5.9

#6538 [5.9] Enable package visibility feature in tools-version 5.9
  Fixtures/Miscellaneous/PackageNameFlag/appPkg/Package.swift
  Fixtures/Miscellaneous/PackageNameFlag/fooPkg/Package.swift
  Fixtures/Miscellaneous/TargetPackageAccess/libPkg/Package.swift
  Sources/PackageDescription/Target.swift
  Sources/PackageModel/PackageModel.swift
  Tests/BuildTests/BuildPlanTests.swift
Labels: 5.9

#6547 [5.8] Bump version to 5.8.1 to match the compiler
  Sources/Basics/SwiftVersion.swift
Labels: 5.8

#6552 [5.9] Add comma to executable template
  Sources/Workspace/InitPackage.swift
Labels: 5.9

#6555 Documentation fixes for `PluginNetworkPermissionScope`.
  Sources/PackageDescription/PackageDescription.docc/Curation/PluginPermission.md
  Sources/PackageDescription/Target.swift
Labels: documentation

#6558 [5.9] Cherry-pick documentation fixes for `PluginNetworkPermissionScope`. (#6555)
  Sources/PackageDescription/PackageDescription.docc/Curation/PluginPermission.md
  Sources/PackageDescription/Target.swift
Labels: documentation, 5.9

#6557 [5.9] Fix plugin templates
  Sources/Workspace/InitPackage.swift
Labels: 5.9

#6545 [5.9] Fix `Triple` formatting in error messages
  Sources/Basics/Triple.swift
  Tests/BasicsTests/TripleTests.swift
Labels: bug, 5.9

#6559 [5.9] Change `testPluginCanBeReferencedByProductName`
  Tests/FunctionalTests/PluginTests.swift
Labels: 5.9

#6427 [5.9] Fix Swift SDK bundles not working due to quarantine
  Sources/PackageModel/Destination.swift
  Sources/PackageModel/SwiftSDKBundle.swift
  Tests/PackageModelTests/SwiftSDKBundleTests.swift
Labels: bug, 5.9

#6578 [5.9] Revert "missing pinned version" change
  Sources/PackageGraph/PubGrub/PubGrubPackageContainer.swift
  Tests/PackageGraphTests/PubgrubTests.swift
Labels: 5.9

#6581 BuildPlan: infer `-lc++` based on run-time triple
  Sources/Build/BuildPlan.swift
  Tests/BuildTests/BuildPlanTests.swift
  Tests/BuildTests/MockBuildTestHelper.swift
Labels: bug

#6579 SwiftSDKBundle.swift: update strings to use "Swift SDK" naming
  Sources/PackageModel/SwiftSDKBundle.swift
Labels: bug

#6580 [5.9] SwiftSDKBundle: update strings to use "Swift SDK" naming
  Sources/PackageModel/SwiftSDKBundle.swift
Labels: bug, 5.9

#6544 Fix `Triple` formatting in error messages
  Sources/Basics/Triple.swift
  Tests/BasicsTests/TripleTests.swift
Labels: bug

#6584 [5.9] Improve error message for 'package-registry publish'
  Sources/PackageRegistry/RegistryClient.swift
Labels: 5.9

#6586 [5.9]🍒Remove the version parameter for C++ interop mode build setting (#6583)
  Sources/PackageDescription/BuildSettings.swift
  Sources/PackageLoading/ManifestJSONParser.swift
  Sources/PackageLoading/PackageBuilder.swift
  Sources/PackageModel/Manifest/TargetBuildSettingDescription.swift
  Sources/PackageModel/ManifestSourceGeneration.swift
  Tests/BuildTests/BuildPlanTests.swift
Labels: 5.9

#6582 [5.9] BuildPlan: infer `-lc++` based on run-time triple
  Sources/Build/BuildPlan.swift
  Tests/BuildTests/BuildPlanTests.swift
  Tests/BuildTests/MockBuildTestHelper.swift
Labels: bug, 5.9

#6590 [5.9] rdar://109108066 (Derive '-external-plugin-path' compiler arguments in SwiftPM)
  Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift
  Sources/PackageModel/Toolchain.swift
  Sources/PackageModel/ToolchainConfiguration.swift
  Sources/PackageModel/UserToolchain.swift
  Tests/BuildTests/MockBuildTestHelper.swift
Labels: 5.9

#6593 [5.9] Add token-file option to 'package-registry login'
  Sources/PackageRegistryTool/PackageRegistryTool+Auth.swift
Labels: 5.9

#6501 [5.8] Fix linking of bootstrap PackageCollectionsSigning
  Sources/PackageCollectionsSigning/CMakeLists.txt
Labels: 5.8

#6604 Commands/SwiftTestTool.swift: update TestCaseSpecifier doc comments
  Sources/Commands/SwiftTestTool.swift
Labels: documentation

#6614 [5.9] Registry login interactive mode cannot read password/token over 128 chars long
  Sources/PackageRegistryTool/PackageRegistryTool+Auth.swift
  Sources/PackageRegistryTool/PackageRegistryTool.swift
Labels: 5.9

#6608 Handle swift-sdk search paths
  Sources/Build/BuildDescription/ClangTargetBuildDescription.swift
  Sources/Build/BuildDescription/ProductBuildDescription.swift
  Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift
  Sources/PackageModel/Toolchain.swift
  Sources/PackageModel/UserToolchain.swift
  Tests/BuildTests/BuildPlanTests.swift
  Tests/BuildTests/MockBuildTestHelper.swift
Labels: bug, cross-compilation
