Repository swiftlang/swift-package-manager, pull requests merged in 2023-09, with the labels that each got.

#6717 Swift SDKs: implement `swiftResourcesPath`
  Sources/Build/BuildDescription/ProductBuildDescription.swift
  Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift
  Sources/PackageModel/Toolchain.swift
  Sources/PackageModel/UserToolchain.swift
  Tests/BuildTests/BuildPlanTests.swift
  Tests/BuildTests/MockBuildTestHelper.swift
Labels: cross-compilation

#6881 [5.9] Fix testable executables once more
  Sources/Build/BuildPlan.swift
Labels: 5.9

#6883 Revert "missing pinned version" change for 5.10
  Sources/PackageGraph/PubGrub/PubGrubPackageContainer.swift
  Tests/PackageGraphTests/PubgrubTests.swift
Labels: 5.10

#6879 Update Product.swift to render the api description correctly
  Sources/PackageDescription/Product.swift
Labels: bug, documentation

#6895 Remove mailing list mention in `README.md`
  README.md
Labels: documentation

#6894 Do not process code coverage when tests failed
  Sources/Commands/SwiftTestTool.swift
Labels: bug

#6907 [5.9] Compute path to `swift-plugin-server` on demand
  Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift
  Sources/PackageModel/Toolchain.swift
  Sources/PackageModel/ToolchainConfiguration.swift
  Sources/PackageModel/UserToolchain.swift
Labels: swift 5.9

#6897 Refine error message with package name suggestion
  Sources/PackageGraph/PackageGraph+Loading.swift
  Sources/PackageGraph/PackageGraph.swift
  Tests/PackageGraphTests/PackageGraphTests.swift
Labels: enhancement

#6906 [5.9] Avoid host triple computation in `BuildParameters.forTriple()`
  Sources/SPMBuildCore/BuildParameters.swift
Labels: swift 5.9

#6918 Fix remaining mentions of "cross-compilation destinations"
  Sources/SwiftSDKTool/Configuration/ConfigureSwiftSDK.swift
  Sources/SwiftSDKTool/Configuration/ResetConfiguration.swift
  Sources/SwiftSDKTool/Configuration/SetConfiguration.swift
  Sources/SwiftSDKTool/Configuration/ShowConfiguration.swift
  Sources/SwiftSDKTool/ListSwiftSDKs.swift
  Sources/SwiftSDKTool/SwiftSDKSubcommand.swift
Labels: bug, cross-compilation

#6928 [5.10] Rename "destination" to "Swift SDK" in comments and code
  Sources/PackageModel/SwiftSDK.swift
  Sources/PackageModel/SwiftSDKBundle.swift
  Sources/PackageModel/UserToolchain.swift
  Sources/SwiftSDKTool/Configuration/ConfigurationSubcommand.swift
  Sources/SwiftSDKTool/Configuration/ResetConfiguration.swift
  Sources/SwiftSDKTool/Configuration/SetConfiguration.swift
  Sources/SwiftSDKTool/Configuration/ShowConfiguration.swift
  Sources/SwiftSDKTool/InstallSwiftSDK.swift
  Sources/SwiftSDKTool/ListSwiftSDKs.swift
  Sources/SwiftSDKTool/README.md
  Sources/SwiftSDKTool/RemoveSwiftSDK.swift
  Sources/SwiftSDKTool/SwiftSDKSubcommand.swift
  Tests/BuildTests/BuildPlanTests.swift
  Tests/PackageModelTests/PackageModelTests.swift
  Tests/PackageModelTests/SwiftSDKTests.swift
Labels: cross-compilation, swift 5.10

#6921 [5.10] Fix remaining mentions of "cross-compilation destinations"
  Sources/SwiftSDKTool/Configuration/ConfigureSwiftSDK.swift
  Sources/SwiftSDKTool/Configuration/ResetConfiguration.swift
  Sources/SwiftSDKTool/Configuration/SetConfiguration.swift
  Sources/SwiftSDKTool/Configuration/ShowConfiguration.swift
  Sources/SwiftSDKTool/ListSwiftSDKs.swift
  Sources/SwiftSDKTool/SwiftSDKSubcommand.swift
Labels: bug, cross-compilation, swift 5.10

#6925 [5.10] Fix backward compatibility in host triple checks
  Sources/Basics/Triple+Basics.swift
  Sources/PackageModel/SwiftSDKBundle.swift
  Tests/BasicsTests/TripleTests.swift
Labels: bug, cross-compilation, swift 5.10

#6910 [5.9] Resolve sandbox issues on external volumes
  Sources/Basics/Sandbox.swift
  Sources/Build/BuildOperation.swift
  Sources/Build/LLBuildManifestBuilder.swift
  Sources/PackageLoading/ManifestLoader.swift
  Sources/Workspace/DefaultPluginScriptRunner.swift
  Tests/BasicsTests/SandboxTests.swift
Labels: swift 5.9

#6927 Rename "destination" to "Swift SDK" in comments and code
  Sources/PackageModel/SwiftSDK.swift
  Sources/PackageModel/SwiftSDKBundle.swift
  Sources/PackageModel/UserToolchain.swift
  Sources/SwiftSDKTool/Configuration/ConfigurationSubcommand.swift
  Sources/SwiftSDKTool/Configuration/ResetConfiguration.swift
  Sources/SwiftSDKTool/Configuration/SetConfiguration.swift
  Sources/SwiftSDKTool/Configuration/ShowConfiguration.swift
  Sources/SwiftSDKTool/InstallSwiftSDK.swift
  Sources/SwiftSDKTool/ListSwiftSDKs.swift
  Sources/SwiftSDKTool/README.md
  Sources/SwiftSDKTool/RemoveSwiftSDK.swift
  Sources/SwiftSDKTool/SwiftSDKSubcommand.swift
  Tests/BuildTests/BuildPlanTests.swift
  Tests/PackageModelTests/PackageModelTests.swift
  Tests/PackageModelTests/SwiftSDKTests.swift
Labels: cross-compilation

#6719 Swift SDKs: fix `toolset.linker.path` not passed to `-ld-path`
  Sources/PackageModel/UserToolchain.swift
  Tests/BuildTests/BuildPlanTests.swift
Labels: cross-compilation

#6819 Fix backward compatibility in host triple checks
  Sources/Basics/Triple+Basics.swift
  Sources/PackageModel/SwiftSDKBundle.swift
  Tests/BasicsTests/TripleTests.swift
  Tests/PackageModelTests/SwiftSDKBundleTests.swift
Labels: bug, cross-compilation

#6932 [5.10] Add and fix missing `Triple` tests
  Sources/Basics/Triple+Basics.swift
  Sources/Basics/Vendor/Triple+Platforms.swift
  Sources/Basics/Vendor/Triple.swift
  Tests/BasicsTests/TripleTests.swift
Labels: bug, cross-compilation, swift 5.10

#6886 [5.9] Reduce XCTest minimum deployment target computation
  Sources/Build/BuildDescription/ProductBuildDescription.swift
  Sources/Build/BuildPlan.swift
  Sources/PackageGraph/PackageGraph+Loading.swift
  Sources/PackageGraph/ResolvedProduct.swift
  Sources/PackageModel/MinimumDeploymentTarget.swift
  Sources/PackageModel/Platform.swift
  Sources/SPMTestSupport/PackageGraphTester.swift
  Sources/XCBuildSupport/PIFBuilder.swift
  Tests/BuildTests/BuildPlanTests.swift
  Tests/CommandsTests/PackageToolTests.swift
  Tests/PackageGraphTests/TargetTests.swift
Labels: swift 5.9

#6920 Support qualifiers for ambiguous plugin commands
  Fixtures/Miscellaneous/Plugins/AmbiguousCommands/Dependencies/A/Package.swift
  Fixtures/Miscellaneous/Plugins/AmbiguousCommands/Dependencies/A/Plugins/A.swift
  Fixtures/Miscellaneous/Plugins/AmbiguousCommands/Dependencies/B/Package.swift
  Fixtures/Miscellaneous/Plugins/AmbiguousCommands/Dependencies/B/Plugins/B.swift
  Fixtures/Miscellaneous/Plugins/AmbiguousCommands/Package.swift
  Fixtures/Miscellaneous/Plugins/AmbiguousCommands/Sources/main.swift
  Sources/Commands/PackageTools/PluginCommand.swift
  Sources/Commands/PackageTools/SwiftPackageTool.swift
  Tests/CommandsTests/PackageToolTests.swift
Labels: enhancement, plugins

#6942 Sort `swift experimental-sdk list` stdout output
  Sources/PackageModel/SwiftSDKBundle.swift
  Sources/SwiftSDKTool/ListSwiftSDKs.swift
  Tests/PackageModelTests/SwiftSDKBundleTests.swift
Labels: enhancement, cross-compilation

#6842 Add and fix missing `Triple` tests
  Sources/Basics/Triple+Basics.swift
  Tests/BasicsTests/TripleTests.swift
Labels: bug, cross-compilation

#6944 Add "Creating a Macro Package" to `Usage.md`
  Documentation/Usage.md
Labels: documentation

#6958 [5.9] Partially revert #6726
  Sources/Build/BuildPlan.swift
Labels: swift 5.9
