Repository swiftlang/swift-package-manager, pull requests merged in 2023-08, with the labels that each got.

#6764 [5.9] Fix another XCBuild compatibility issue
  Sources/XCBuildSupport/PIFBuilder.swift
Labels: 5.9

#6768 Add subcommands to install and uninstall packages
  Sources/Basics/FileSystem/FileSystem+Extensions.swift
  Sources/Commands/CMakeLists.txt
  Sources/Commands/PackageTools/InstalledPackages.swift
  Sources/Commands/PackageTools/SwiftPackageTool.swift
Labels: enhancement

#6781 Set `-user-module-version` for any version-based package
  Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift
  Tests/BuildTests/BuildPlanTests.swift
Labels: enhancement

#6791 plugins: Build command plugin dependencies for the host, not the target
  Sources/Commands/PackageTools/PluginCommand.swift
  Sources/CoreCommands/SwiftTool.swift
  Sources/SPMBuildCore/Triple+Extensions.swift
Labels: cross-compilation

#6798 [5.9] Update swift-syntax version in macro template
  Sources/Workspace/InitPackage.swift
Labels: 5.9

#6799 [5.9] Build command plugin dependencies for the host, not the target
  Sources/Commands/PackageTools/PluginCommand.swift
  Sources/CoreCommands/SwiftTool.swift
  Sources/SPMBuildCore/Triple+Extensions.swift
Labels: bug, 5.9, cross-compilation

#6770 [5.9] PackageModel: honour `.librarian` for toolsets
  Sources/PackageModel/UserToolchain.swift
  Tests/BuildTests/BuildPlanTests.swift
Labels: bug, 5.9, cross-compilation

#6691 [5.9] Remove extra paths added to LD_LIBRARY_PATH on Linux when running tests
  Sources/Commands/Utilities/TestingSupport.swift
Labels: 5.9

#6692 [5.8] Remove extra paths added to LD_LIBRARY_PATH on Linux when running tests
  Sources/Commands/Utilities/TestingSupport.swift
Labels: 5.8

#6732 Improve handling of non-macOS Darwin triples (reprise)
  Sources/Basics/Triple+Basics.swift
  Sources/Build/BuildDescription/ProductBuildDescription.swift
  Sources/Build/BuildPlan.swift
  Sources/SPMBuildCore/BinaryTarget+Extensions.swift
  Sources/SPMBuildCore/BuildParameters.swift
  Sources/SPMBuildCore/XCFrameworkMetadata.swift
  Tests/BuildTests/BuildPlanTests.swift
  Tests/SPMBuildCoreTests/XCFrameworkMetadataTests.swift
Labels: cross-compilation

#6843 [5.9] Add and fix missing Triple tests, fix soundness checks
  Sources/Basics/Triple+Basics.swift
  Sources/Basics/Vendor/Triple+Platforms.swift
  Sources/Basics/Vendor/Triple.swift
  Tests/BasicsTests/TripleTests.swift
  Utilities/soundness.sh
Labels: bug, 5.9, cross-compilation

#6839 Update CHANGELOG.md to reflect 5.9 scope
  CHANGELOG.md
Labels: documentation

#6820 [5.9] Fix backward compatibility in host triple checks
  Sources/PackageModel/SwiftSDKBundle.swift
  Tests/PackageModelTests/SwiftSDKBundleTests.swift
Labels: bug, 5.9, cross-compilation

#6834 Preserve environment in `tripleString(forPlatformVersion:)`
  Sources/Basics/Triple+Basics.swift
  Tests/BasicsTests/TripleTests.swift
Labels: cross-compilation

#6869 [5.9] Remove `swiftpm-xctest-helper`
  Package.swift
  Sources/Commands/Utilities/TestingSupport.swift
  Sources/SPMTestSupport/SwiftPMProduct.swift
  Sources/swiftpm-xctest-helper/main.swift
  Tests/FunctionalTests/SwiftPMXCTestHelperTests.swift
  Utilities/bootstrap
Labels: 5.9
