Repository swiftlang/swift-package-manager, pull requests merged in 2023-04, with the labels that each got.

#6370 [5.9] Expected signing entity verification
  Sources/PackageModel/RegistryReleaseMetadata.swift
  Sources/SPMTestSupport/MockPackage.swift
  Sources/SPMTestSupport/MockWorkspace.swift
  Sources/Workspace/Workspace.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: 5.9

#6371 Do not pollute home directory with test data
  Tests/CommandsTests/SwiftToolTests.swift
Labels: 5.9

#6372 [5.9] Update registry service spec per SE-0391
  Documentation/Registry.md
Labels: 5.9

#6374 rdar://107033737 (Expose `PackageVersionMetadata` from `PackageSearchClient`)
  Sources/PackageMetadata/PackageMetadata.swift
Labels: 5.9

#6380 PackageModel, CoreCommands: fix build flags not passed
  Sources/CoreCommands/SwiftTool.swift
  Sources/PackageModel/BuildFlags.swift
Labels: bug

#6365 [5.9] Support Target Grouping
  Fixtures/Miscellaneous/TargetGrouping/libPkg/Package.swift
  Fixtures/Miscellaneous/TargetGrouping/libPkg/Sources/Core/Core.swift
  Fixtures/Miscellaneous/TargetGrouping/libPkg/Sources/DataManager/File.swift
  Fixtures/Miscellaneous/TargetGrouping/libPkg/Sources/DataModel/File.swift
  Fixtures/Miscellaneous/TargetGrouping/libPkg/Sources/ExampleApp/main.swift
  Fixtures/Miscellaneous/TargetGrouping/libPkg/Sources/MainLib/Lib.swift
  Fixtures/Miscellaneous/TargetGrouping/libPkg/Tests/BlackBoxTests/BlackBoxTests.swift
  Fixtures/Miscellaneous/TargetGrouping/libPkg/Tests/MainLibTests/MainLibTests.swift
  Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift
  Sources/Build/BuildPlan.swift
  Sources/CompilerPluginSupport/TargetExtensions.swift
  Sources/PackageDescription/PackageDescriptionSerialization.swift
  Sources/PackageDescription/PackageDescriptionSerializationConversion.swift
  Sources/PackageDescription/Target.swift
  Sources/PackageGraph/ResolvedProduct.swift
  Sources/PackageGraph/ResolvedTarget.swift
  Sources/PackageLoading/ManifestJSONParser.swift
  Sources/PackageLoading/ManifestLoader.swift
  Sources/PackageLoading/PackageBuilder.swift
  Sources/PackageModel/Manifest/TargetDescription.swift
  Sources/PackageModel/Target.swift
  Sources/SPMTestSupport/MockTarget.swift
  Sources/Workspace/Workspace.swift
  Tests/BuildTests/BuildPlanTests.swift
  Tests/PackageGraphTests/PackageGraphTests.swift
  Tests/PackageGraphTests/TargetTests.swift
  Tests/PackageLoadingTests/PD_5_3_LoadingTests.swift
Labels: 5.9

#6381 [5.9] PackageModel, CoreCommands: fix build flags not passed
  Sources/CoreCommands/SwiftTool.swift
  Sources/PackageModel/BuildFlags.swift
Labels: bug, 5.9

#6385 [5.9] Set a default value to the group param for a macro target
  Sources/CompilerPluginSupport/TargetExtensions.swift
Labels: 5.9

#6382 Fix symlinked `swift-experimental-destination` invocations
  Sources/CrossCompilationDestinationsTool/DestinationCommand.swift
  Sources/CrossCompilationDestinationsTool/InstallDestination.swift
  Sources/CrossCompilationDestinationsTool/SwiftDestinationTool.swift
  Sources/PackageModel/DestinationBundle.swift
  Sources/swift-experimental-destination/SwiftDestinationTool.swift
Labels: bug

#6383 [5.9] Fix symlinked `swift-experimental-destination` invocations
  Sources/CrossCompilationDestinationsTool/DestinationCommand.swift
  Sources/CrossCompilationDestinationsTool/InstallDestination.swift
  Sources/CrossCompilationDestinationsTool/SwiftDestinationTool.swift
  Sources/PackageModel/DestinationBundle.swift
  Sources/swift-experimental-destination/SwiftDestinationTool.swift
Labels: bug, 5.9

#6349 CMake updates for 5.9 release
  CMakeLists.txt
  Sources/CMakeLists.txt
  Sources/Commands/CMakeLists.txt
  Sources/CoreCommands/CMakeLists.txt
  Sources/CrossCompilationDestinationsTool/CMakeLists.txt
  Sources/PackageCollections/CMakeLists.txt
  Sources/PackageCollectionsModel/CMakeLists.txt
  Sources/PackageCollectionsSigning/CMakeLists.txt
  Sources/PackageCollectionsSigningLibc/CMakeLists.txt
  Sources/PackageCollectionsTool/CMakeLists.txt
  Sources/PackageMetadata/CMakeLists.txt
  Sources/PackageRegistryTool/CMakeLists.txt
  Sources/Workspace/CMakeLists.txt
  Sources/XCBuildSupport/CMakeLists.txt
  Sources/swift-package-collection/CMakeLists.txt
  Sources/swift-package-registry/CMakeLists.txt
Labels: 5.9

#4872 Tests: use `FileManager` instead of `cp`
  IntegrationTests/Tests/IntegrationTests/Helpers.swift
  Sources/SPMTestSupport/misc.swift
Labels: windows

#6386 [5.9] Documentation on registry usage
  Documentation/PackageRegistryUsage.md
Labels: 5.9

#6398 [5.9] sort identities from url lookup to make lookup result consistent
  Sources/Workspace/Workspace.swift
Labels: 5.9

#6401 [5.9] Fix product lookup
  Sources/PackageGraph/PackageGraph+Loading.swift
  Tests/PackageGraphTests/PackageGraphTests.swift
Labels: 5.9

#6406 [5.9] ManifestSourceGeneration incorrectly writes out `DriverKit` instead of `driverKit` (#6405)
  Sources/PackageModel/ManifestSourceGeneration.swift
  Tests/WorkspaceTests/ManifestSourceGenerationTests.swift
Labels: 5.9

#6393 [5.9] Cross-compilation: fix support for `.tar.gz` bundles
  Package.swift
  Sources/Basics/Archiver/Archiver.swift
  Sources/Basics/Archiver/TarArchiver.swift
  Sources/Basics/Archiver/UniversalArchiver.swift
  Sources/Basics/Archiver/ZipArchiver.swift
  Sources/Basics/CMakeLists.txt
  Sources/Basics/Cancellator.swift
  Sources/Basics/FileSystem/Path+Extensions.swift
  Sources/CoreCommands/SwiftTool.swift
  Sources/CrossCompilationDestinationsTool/InstallDestination.swift
  Sources/PackageModel/DestinationBundle.swift
  Tests/BasicsTests/Archiver/Inputs/archive.tar.gz
  Tests/BasicsTests/Archiver/Inputs/archive.zip
  Tests/BasicsTests/Archiver/Inputs/invalid_archive.tar.gz
  Tests/BasicsTests/Archiver/Inputs/invalid_archive.zip
  Tests/BasicsTests/Archiver/TarArchiverTests.swift
  Tests/BasicsTests/Archiver/UniversalArchiverTests.swift
  Tests/BasicsTests/Archiver/ZipArchiverTests.swift
  Tests/CommandsTests/SwiftToolTests.swift
Labels: 5.9

#6413 [5.9] Add publication time to registry package release metadata
  Documentation/Registry.md
  Sources/PackageMetadata/PackageMetadata.swift
  Sources/PackageRegistry/RegistryClient.swift
  Sources/SPMTestSupport/MockRegistry.swift
  Tests/WorkspaceTests/RegistryPackageContainerTests.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: 5.9

#6417 [5.9] A few fixes for building SwiftPM for MacCatalyst
  Sources/Basics/Cancellator.swift
  Sources/swiftpm-xctest-helper/main.swift
  Tests/PackageCollectionsSigningTests/Utilities.swift
Labels: 5.9

#6418 [5.9] Add author and signer to package collection models
  Fixtures/Collections/JSON/good.json
  Fixtures/Collections/JSON/good_signed.json
  Package.swift
  Sources/PackageCollections/Model/PackageTypes.swift
  Sources/PackageCollections/PackageCollections.swift
  Sources/PackageCollections/Providers/JSONPackageCollectionProvider.swift
  Sources/PackageCollectionsModel/Formats/v1.md
  Sources/PackageCollectionsModel/PackageCollectionModel+v1.swift
  Sources/PackageMetadata/PackageMetadata.swift
  Tests/PackageCollectionsModelTests/PackageCollectionModelTests.swift
  Tests/PackageCollectionsTests/JSONPackageCollectionProviderTests.swift
  Tests/PackageCollectionsTests/PackageCollectionValidationTests.swift
  Tests/PackageCollectionsTests/PackageCollectionsModelTests.swift
  Tests/PackageCollectionsTests/PackageCollectionsTests.swift
  Tests/PackageCollectionsTests/PackageIndexAndCollectionsTests.swift
  Tests/PackageCollectionsTests/Utility.swift
Labels: 5.9

#6423 [5.9] Fix iOS buid
  Sources/Basics/Cancellator.swift
Labels: 5.9

#6428 Use exact SwiftCrypto version to work around self-hosting failure
  Package.swift
Labels: bug

#6436 Basics: remove `AsyncFileSystem` as unused
  Sources/Basics/CMakeLists.txt
  Sources/Basics/FileSystem/AsyncFileSystem.swift
  Sources/Basics/HTTPClient/HTTPClientRequest.swift
  Tests/BasicsTests/FileSystem/AsyncFileSystemTests.swift
  Tests/BasicsTests/URLSessionHTTPClientTests.swift
Labels: concurrency

#5910 refactor RelativePath to allow late stage canonicalization in support of windows
  Sources/Build/BuildDescription/ClangTargetBuildDescription.swift
  Sources/Build/BuildDescription/ProductBuildDescription.swift
  Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift
  Sources/Build/BuildOperation.swift
  Sources/Build/BuildOperationBuildSystemDelegateHandler.swift
  Sources/Build/LLBuildManifestBuilder.swift
  Sources/Commands/PackageTools/PluginCommand.swift
  Sources/Commands/SwiftRunTool.swift
  Sources/Commands/Utilities/PluginDelegate.swift
  Sources/PackageLoading/TargetSourcesBuilder.swift
  Sources/PackageModel/Resource.swift
  Sources/PackageModel/ToolsVersion.swift
  Sources/PackageModel/Toolset.swift
  Sources/PackageModel/UserToolchain.swift
  Sources/PackageRegistry/RegistryDownloadsManager.swift
  Sources/SPMBuildCore/BuildParameters.swift
  Sources/SPMBuildCore/BuildSystem.swift
  Sources/SPMBuildCore/PluginInvocation.swift
  Sources/SPMTestSupport/MockDependency.swift
  Sources/SPMTestSupport/MockPackage.swift
  Sources/SPMTestSupport/misc.swift
  Sources/SourceControl/RepositoryManager.swift
  Sources/Workspace/ManagedDependency.swift
  Sources/Workspace/Workspace+State.swift
  Sources/Workspace/Workspace.swift
  Sources/XCBuildSupport/XcodeBuildSystem.swift
  Tests/BasicsTests/Archiver/TarArchiverTests.swift
  Tests/BasicsTests/Archiver/UniversalArchiverTests.swift
  Tests/BasicsTests/Archiver/ZipArchiverTests.swift
  Tests/BuildTests/BuildPlanTests.swift
  Tests/BuildTests/LLBuildManifestTests.swift
  Tests/BuildTests/MockBuildTestHelper.swift
  Tests/BuildTests/ModuleAliasingBuildTests.swift
  Tests/CommandsTests/PackageRegistryToolTests.swift
  Tests/CommandsTests/PackageToolTests.swift
  Tests/FunctionalTests/MiscellaneousTests.swift
  Tests/PackageGraphPerformanceTests/DependencyResolverPerfTests.swift
  Tests/PackageGraphPerformanceTests/PackageGraphPerfTests.swift
  Tests/PackageGraphTests/PackageGraphTests.swift
  Tests/PackageLoadingPerformanceTests/ManifestLoadingTests.swift
  Tests/PackageLoadingTests/PD_4_0_LoadingTests.swift
  Tests/PackageLoadingTests/PD_4_2_LoadingTests.swift
  Tests/PackageLoadingTests/PD_5_0_LoadingTests.swift
  Tests/PackageLoadingTests/PD_5_5_LoadingTests.swift
  Tests/PackageLoadingTests/PackageBuilderTests.swift
  Tests/PackageLoadingTests/PkgConfigParserTests.swift
  Tests/PackageLoadingTests/PkgConfigTests.swift
  Tests/PackageLoadingTests/TargetSourcesBuilderTests.swift
  Tests/PackageModelTests/ManifestTests.swift
  Tests/SPMBuildCoreTests/ArtifactsArchiveMetadataTests.swift
  Tests/SPMBuildCoreTests/PluginInvocationTests.swift
  Tests/SourceControlTests/GitRepositoryTests.swift
  Tests/SourceControlTests/InMemoryGitRepositoryTests.swift
  Tests/SourceControlTests/RepositoryManagerTests.swift
  Tests/WorkspaceTests/ManifestSourceGenerationTests.swift
  Tests/WorkspaceTests/SourceControlPackageContainerTests.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
  Tests/XCBuildSupportTests/PIFBuilderTests.swift
Labels: windows

#6444 [5.9] Expose `SigningEntity` via package metadata
  Sources/PackageMetadata/PackageMetadata.swift
  Sources/PackageModel/RegistryReleaseMetadata.swift
Labels: 5.9

#6434 NFC: 5.9 Documentation update.
  Sources/PackageDescription/BuildSettings.swift
  Sources/PackageDescription/PackageDescription.swift
  Sources/PackageDescription/Resource.swift
  Sources/PackageDescription/SupportedPlatforms.swift
  Sources/PackageDescription/Target.swift
Labels: documentation

#6452 [5.9] quiet down redundant warnings for binary targets with multiple info.plist
  Sources/Workspace/Workspace+BinaryArtifacts.swift
Labels: 5.9

#6456 [5.9] Newly created build tool and command plugin templates should have conditional support for XcodeProjectPlugin #6446
  Sources/Workspace/InitPackage.swift
  Tests/WorkspaceTests/InitTests.swift
Labels: 5.9

#6458 [5.8] skip testCompilationDiagnostics
  Tests/SPMBuildCoreTests/PluginInvocationTests.swift
Labels: 5.8

#6430 [5.8] On ELF platforms, only add runpaths as needed (#6321)
  Package.swift
  Utilities/bootstrap
Labels: 5.8

#6441 [5.9] Update to swift-certificates 0.4.0
  Fixtures/Signing/Certificates/TestIntermediateCA.cer
  Fixtures/Signing/Certificates/TestRootCA.cer
  Fixtures/Signing/Certificates/Test_ec.cer
  Fixtures/Signing/Certificates/Test_ec_key.p8
  Fixtures/Signing/Certificates/Test_ec_self_signed.cer
  Fixtures/Signing/Certificates/Test_ec_self_signed_key.p8
  Fixtures/Signing/Certificates/Test_rsa.cer
  Fixtures/Signing/Certificates/Test_rsa_key.p8
  Fixtures/Signing/Certificates/Test_rsa_self_signed.cer
  Fixtures/Signing/Certificates/Test_rsa_self_signed_key.p8
  Package.swift
  Sources/PackageSigning/SignatureProvider.swift
  Sources/PackageSigning/VerifierPolicies.swift
  Tests/PackageSigningTests/SigningIdentityTests.swift
  Tests/PackageSigningTests/SigningTests.swift
Labels: 5.9

#6460 [5.9] Update macro API
  Sources/CompilerPluginSupport/TargetExtensions.swift
  Sources/PackageDescription/Target.swift
  Sources/PackageModel/Manifest/TargetDescription.swift
  Tests/PackageLoadingTests/PD_Next_LoadingTests.swift
Labels: 5.9

#6466 [5.9] Bump swift-certificates to 0.4.1
  Package.swift
Labels: 5.9

#6470 Workspace: log both branch and revision during checkout
  Sources/Workspace/CheckoutState.swift
  Sources/Workspace/Workspace.swift
Labels: enhancement

#6474 Disable development mode for 5.9 branch
  Fixtures/Miscellaneous/CXX17CompilerCrash/v5_8/Package.swift
  Fixtures/Miscellaneous/Plugins/PluginsAndSnippets/Package.swift
  Sources/Basics/SwiftVersion.swift
  Tests/BuildTests/BuildPlanTests.swift
Labels: 5.9

#6481 [5.9] Disable `testImportOfMissedDepWarning`
  Tests/CommandsTests/BuildToolTests.swift
Labels: 5.9

#6471 [5.9] Editorial review changes of PackageDescription documentation.
  Sources/PackageDescription/BuildSettings.swift
  Sources/PackageDescription/PackageDependency.swift
  Sources/PackageDescription/PackageDescription.docc/Curation/Extensions/Product-Executable.md
  Sources/PackageDescription/PackageDescription.docc/Curation/Platform.md
  Sources/PackageDescription/PackageDescription.docc/Curation/Plugin.md
  Sources/PackageDescription/PackageDescription.docc/Curation/PluginPermission.md
  Sources/PackageDescription/PackageDescription.docc/Curation/Product.md
  Sources/PackageDescription/PackageDescription.docc/Curation/SupportedPlatforms.md
  Sources/PackageDescription/PackageDescription.docc/Curation/Target-Dependency.md
  Sources/PackageDescription/PackageDescription.swift
  Sources/PackageDescription/PackageDescriptionSerializationConversion.swift
  Sources/PackageDescription/Product.swift
  Sources/PackageDescription/Resource.swift
  Sources/PackageDescription/Target.swift
Labels: documentation

#6486 [5.9] Use assertMacroExpansion in test cases of macro template
  Sources/Workspace/InitPackage.swift
Labels: 5.9
