Repository swiftlang/swift-package-manager, pull requests merged in 2023-03, with the labels that each got.

#6202 Fix `InstallDestination.run` function not invoked by ArgumentParser
  Sources/CoreCommands/SwiftToolObservabilityHandler.swift
  Sources/CrossCompilationDestinationsTool/InstallDestination.swift
Labels: bug

#6198 [5.8] Change executable template to use `main.swift`
  Sources/Workspace/InitPackage.swift
  Tests/CommandsTests/PackageToolTests.swift
  Tests/WorkspaceTests/InitTests.swift
Labels: 5.8

#6205 PackageModel: fix error reporting for invalid toolsets
  Sources/PackageModel/Destination.swift
  Sources/PackageModel/Toolset.swift
  Tests/PackageModelTests/DestinationTests.swift
Labels: bug

#6208 DriverSupport: fix `swiftc` path in `DriverSupportUtils`
  Sources/DriverSupport/DriverSupportUtils.swift
Labels: bug

#6222 CrossCompilationDestinationsTool: add diagnostics for no destinations
  Sources/CrossCompilationDestinationsTool/ListDestinations.swift
Labels: bug

#6261 Destinations: add `configuration set` subcommand
  Sources/CrossCompilationDestinationsTool/CMakeLists.txt
  Sources/CrossCompilationDestinationsTool/Configuration/ConfigurationCommand.swift
  Sources/CrossCompilationDestinationsTool/Configuration/ConfigureDestination.swift
  Sources/CrossCompilationDestinationsTool/Configuration/ResetConfiguration.swift
  Sources/CrossCompilationDestinationsTool/Configuration/SetConfiguration.swift
  Sources/CrossCompilationDestinationsTool/Configuration/ShowConfiguration.swift
  Sources/PackageModel/DestinationConfigurationStore.swift
Labels: enhancement

#6089 Basics: make `ObservabilityScope` conform to `Sendable`
  Sources/Basics/HTTPClient/HTTPClient.swift
  Sources/Basics/Observability.swift
  Sources/Basics/SendableTimeInterval.swift
  Sources/CoreCommands/SwiftToolObservabilityHandler.swift
  Sources/SPMBuildCore/PluginInvocation.swift
Labels: concurrency

#6291 Destinations: allow removing by artifact ID
  Sources/CrossCompilationDestinationsTool/RemoveDestination.swift
  Sources/PackageModel/Destination.swift
  Sources/PackageModel/DestinationBundle.swift
Labels: enhancement

#6324 [5.9] Post branch adjustments for 5.9
  Package.swift
  Sources/Basics/SwiftVersion.swift
Labels: 5.9

#6319 Destinations: fix missing `remove` command message
  Sources/CrossCompilationDestinationsTool/RemoveDestination.swift
Labels: bug

#6327 [5.9] Turn development mode back on
  Sources/Basics/SwiftVersion.swift
Labels: 5.9

#6326 [5.9] Plugin import scanner isn't passing in the library directory (#6323)
  Sources/Workspace/Workspace.swift
  Tests/SPMBuildCoreTests/PluginInvocationTests.swift
Labels: 5.9

#6335 [5.9] Rearrangement in preparation for 5.9 branching
  CHANGELOG.md
  Fixtures/Miscellaneous/PackageNameFlag/appPkg/Package.swift
  Fixtures/Miscellaneous/PackageNameFlag/fooPkg/Package.swift
  Fixtures/Resources/EmbedInCodeSimple/Package.swift
  Sources/PackageDescription/Resource.swift
  Sources/PackageModel/PackageModel.swift
Labels: 5.9

#6334 [5.9] rdar://105991217 (Make macros testable)
  Sources/Build/BuildDescription/ProductBuildDescription.swift
  Sources/Build/BuildDescription/SwiftTargetBuildDescription.swift
  Sources/Build/BuildPlan.swift
  Sources/PackageModel/Target.swift
Labels: 5.9

#6336 [5.9] better diagnostics when potentially duplicate packages are found
  Sources/PackageGraph/PackageGraph+Loading.swift
  Sources/PackageLoading/PackageBuilder.swift
  Sources/SPMTestSupport/ManifestExtensions.swift
  Tests/PackageGraphTests/PackageGraphTests.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: 5.9

#6338 [5.9] better diagnostics for networking errors
  Sources/Basics/Errors.swift
  Sources/Basics/HTTPClient/URLSessionHTTPClient.swift
  Sources/PackageRegistry/RegistryClient.swift
  Sources/Workspace/Workspace+BinaryArtifacts.swift
  Tests/BasicsTests/URLSessionHTTPClientTests.swift
Labels: 5.9

#6337 [5.9] improve diagnostics when registry configuration is broken
  Sources/Workspace/Workspace+Configuration.swift
Labels: 5.9

#6342 [5.9] Fix compilation error in Swift 5.7.2
  Sources/PackageGraph/PackageGraph+Loading.swift
Labels: 5.9

#6343 Destinations: throw error on duplicate artifact ID
  Sources/CrossCompilationDestinationsTool/InstallDestination.swift
  Sources/PackageModel/Destination.swift
  Sources/PackageModel/DestinationBundle.swift
  Sources/PackageModel/DestinationConfigurationStore.swift
  Tests/PackageModelTests/DestinationBundleTests.swift
Labels: bug

#6340 [5.9] Reduce errors from manifest signature validation (#6325)
  Sources/PackageLoading/ManifestSignatureParser.swift
  Sources/PackageRegistry/RegistryClient.swift
  Sources/PackageRegistry/SignatureValidation.swift
  Tests/PackageRegistryTests/SignatureValidationTests.swift
Labels: 5.9

#6344 [5.9] Destinations: throw error on duplicate artifact ID
  Sources/CrossCompilationDestinationsTool/InstallDestination.swift
  Sources/PackageModel/Destination.swift
  Sources/PackageModel/DestinationBundle.swift
  Sources/PackageModel/DestinationConfigurationStore.swift
  Tests/PackageModelTests/DestinationBundleTests.swift
Labels: bug, 5.9

#6346 [5.9] cleanup mirror config command
  Sources/Commands/PackageTools/Config.swift
  Sources/PackageGraph/DependencyMirrors.swift
  Sources/PackageGraph/PinsStore.swift
  Sources/SPMTestSupport/MockWorkspace.swift
  Sources/Workspace/Workspace.swift
  Tests/CommandsTests/PackageToolTests.swift
  Tests/WorkspaceTests/MirrorsConfigurationTests.swift
  Tests/WorkspaceTests/PinsStoreTests.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: 5.9

#6350 [5.9] Package manifest checksum TOFU
  Sources/PackageFingerprint/FilePackageFingerprintStorage.swift
  Sources/PackageFingerprint/Model.swift
  Sources/PackageFingerprint/PackageFingerprintStorage.swift
  Sources/PackageRegistry/ChecksumTOFU.swift
  Sources/PackageRegistry/RegistryClient.swift
  Sources/PackageRegistry/RegistryDownloadsManager.swift
  Sources/PackageRegistryTool/PackageRegistryTool+Auth.swift
  Sources/PackageRegistryTool/PackageRegistryTool+Publish.swift
  Sources/SPMTestSupport/MockPackageFingerprintStorage.swift
  Sources/SPMTestSupport/MockRegistry.swift
  Sources/Workspace/SourceControlPackageContainer.swift
  Sources/Workspace/Workspace.swift
  Tests/PackageFingerprintTests/FilePackageFingerprintStorageTests.swift
  Tests/PackageRegistryTests/PackageVersionChecksumTOFUTests.swift
  Tests/PackageRegistryTests/RegistryClientTests.swift
  Tests/PackageRegistryTests/RegistryDownloadsManagerTests.swift
  Tests/WorkspaceTests/RegistryPackageContainerTests.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: 5.9

#6345 PackageLoading: anchor relative paths for Windows
  Sources/PackageLoading/PackageBuilder.swift
Labels: windows

#6352 [5.9] Add templates for build tool plugins and command plugins (#6111)
  CHANGELOG.md
  Sources/Commands/PackageTools/Init.swift
  Sources/Workspace/InitPackage.swift
  Tests/WorkspaceTests/InitTests.swift
Labels: 5.9

#6355 change validation to throw instead of pre-condition to avoid crashes
  Sources/Workspace/Workspace.swift
Labels: 5.9
