Repository swiftlang/swift-package-manager, pull requests merged in 2024-09, with the labels that each got.

#7933 [cxx-interop] Improve wording of doc comment
  Sources/PackageDescription/BuildSettings.swift
Labels: documentation

#7935 Fix link in `CHANGELOG.md`, add `swift sdk install --checksum` item
  CHANGELOG.md
Labels: documentation

#7944 `CheckoutState.swift`: Fix typo in comment
  Sources/Workspace/CheckoutState.swift
Labels: bug, documentation

#7964 Address concurrency warnings
  Sources/Basics/Concurrency/AsyncProcess.swift
  Sources/PackageCollections/Storage/SQLitePackageCollectionsStorage.swift
  Sources/PackageGraph/PackageContainer.swift
  Sources/PackageGraph/Resolution/PubGrub/PubGrubDependencyResolver.swift
  Sources/PackageRegistry/ChecksumTOFU.swift
  Sources/PackageRegistry/RegistryClient.swift
  Sources/SPMBuildCore/Plugins/PluginInvocation.swift
  Sources/SPMBuildCore/Plugins/PluginScriptRunner.swift
  Sources/Workspace/PackageContainer/FileSystemPackageContainer.swift
  Sources/Workspace/PackageContainer/RegistryPackageContainer.swift
  Sources/Workspace/PackageContainer/SourceControlPackageContainer.swift
  Sources/Workspace/Workspace+Editing.swift
  Sources/Workspace/Workspace+Manifests.swift
  Sources/Workspace/Workspace.swift
  Sources/_InternalTestSupport/MockWorkspace.swift
Labels: bug, concurrency

#7963 Fixup warnings in tests
  Tests/BasicsTests/AsyncProcessTests.swift
  Tests/CommandsTests/TestCommandTests.swift
  Tests/FunctionalTests/PluginTests.swift
  Tests/PackageRegistryTests/RegistryClientTests.swift
  Tests/SourceControlTests/RepositoryManagerTests.swift
  Tests/WorkspaceTests/InitTests.swift
  Tests/WorkspaceTests/SourceControlPackageContainerTests.swift
Labels: bug, concurrency

#7959 APIDiff.swift: Address warning by using task group instead of semaphore
  Sources/Commands/PackageCommands/APIDiff.swift
Labels: concurrency

#7960 [6.0.1] Remove `@MainActor` from XCTest glue.
  Sources/Build/LLBuildCommands.swift
Labels: bug, concurrency, swift test, swift 6.0

#7969 PackageDescription: add 2024 Darwin OS versions to `SupportedPlatforms`
  Sources/PackageDescription/SupportedPlatforms.swift
Labels: bug, package manifests

#7981 Refactor withCheckedThrowingContinuation calls to get rid of warnings
  Sources/Basics/HTTPClient/LegacyHTTPClient.swift
  Sources/PackageRegistry/RegistryDownloadsManager.swift
  Sources/PackageRegistry/SignatureValidation.swift
  Sources/PackageRegistry/SigningEntityTOFU.swift
  Sources/SourceControl/RepositoryManager.swift
Labels: bug, concurrency

#7980 Workspace: fix warning applying @Sendable annotation
  Sources/Workspace/Workspace+BinaryArtifacts.swift
Labels: bug, concurrency

#7979 Workspace: use TaskGroup to fix concurrency warning
  Sources/Workspace/Workspace+Dependencies.swift
Labels: concurrency

#7982 [6.0.0] Add 2024 Darwin OS versions to `SupportedPlatforms`
  Sources/PackageDescription/SupportedPlatforms.swift
Labels: package manifests, swift 6.0

#7941 Fix discrepancies with usage of package display name/package identity in `swift package edit` command
  Sources/Commands/PackageCommands/EditCommands.swift
  Sources/Workspace/Workspace+Editing.swift
  Sources/Workspace/Workspace.swift
  Sources/_InternalTestSupport/MockWorkspace.swift
  Sources/_InternalTestSupport/PackageGraphTester.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
Labels: add to change log

#7974 [6.0.1] Add 2024 Darwin OS versions to `SupportedPlatforms`
  Sources/PackageDescription/SupportedPlatforms.swift
Labels: swift 6.0

#7927 Add `OSFileSystem` to complement `MockFileSystem`
  Sources/_AsyncFileSystem/MockFileSystem.swift
  Sources/_AsyncFileSystem/OSFileSystem.swift
  Sources/_AsyncFileSystem/OpenWritableFile.swift
  Tests/_AsyncFileSystemTests/AsyncFileSystemTests.swift
Labels: concurrency

#7967 Remove `@MainActor` from XCTest glue.
  Sources/Build/LLBuildCommands.swift
Labels: bug, concurrency, swift test

#7993 Apply @Sendable annotation to address the compiler warning
  Sources/PackageRegistry/RegistryDownloadsManager.swift
Labels: concurrency

#7988 [6.0] Remove `@MainActor` from XCTest glue.
  Sources/Build/LLBuildCommands.swift
Labels: bug, concurrency, swift test

#8003 Enable WMO for Embedded targets automatically
  Sources/Build/BuildDescription/SwiftModuleBuildDescription.swift
  Sources/Build/BuildManifest/LLBuildManifestBuilder+Swift.swift
  Sources/SPMBuildCore/BuildParameters/BuildParameters.swift
  Tests/BuildTests/BuildPlanTests.swift
Labels: embedded
