Repository swiftlang/swift-package-manager, pull requests merged in 2025-03, with the labels that each got.

#6650 Remove use of `NSString.replacingOccurrences(of:with:)`
  Sources/Basics/Concurrency/AsyncProcess.swift
  Sources/Basics/FileSystem/AbsolutePath.swift
  Sources/Basics/FileSystem/NativePathExtensions.swift
  Sources/Basics/Netrc.swift
  Sources/Basics/Sandbox.swift
  Sources/Basics/Serialization/SerializedJSON.swift
  Sources/Commands/Utilities/DOTManifestSerializer.swift
  Sources/PackageLoading/ManifestLoader.swift
  Sources/PackageLoading/ModuleMapGenerator.swift
  Sources/PackageModel/ManifestSourceGeneration.swift
  Sources/PackageRegistry/RegistryClient.swift
  Sources/SourceControl/GitRepository.swift
  Sources/_InternalTestSupport/misc.swift
Labels: next

#8339 Clarify formatting changes in `CONTRIBUTING.md`
  CONTRIBUTING.md
Labels: documentation

#8349 Fix Swift 6.0 trailing comma compatibility
  Sources/PackageRegistry/RegistryDownloadsManager.swift
Labels: bug

#8210 Tests: Skip failing tests on windows
  IntegrationTests/Tests/IntegrationTests/BasicTests.swift
  IntegrationTests/Tests/IntegrationTests/SwiftPMTests.swift
  Sources/_InternalTestSupport/misc.swift
  Tests/BasicsTests/AsyncProcessTests.swift
  Tests/BasicsTests/ConcurrencyHelpersTests.swift
  Tests/BasicsTests/Environment/EnvironmentTests.swift
  Tests/BasicsTests/FileSystem/PathTests.swift
  Tests/BasicsTests/FileSystem/VFSTests.swift
  Tests/BasicsTests/HTTPClientTests.swift
  Tests/BasicsTests/LegacyHTTPClientTests.swift
  Tests/BasicsTests/Serialization/SerializedJSONTests.swift
  Tests/BuildTests/BuildPlanTests.swift
  Tests/BuildTests/BuildSystemDelegateTests.swift
  Tests/BuildTests/LLBuildManifestBuilderTests.swift
  Tests/BuildTests/PluginsBuildPlanTests.swift
  Tests/BuildTests/PrepareForIndexTests.swift
  Tests/PackageGraphPerformanceTests/PackageGraphPerfTests.swift
  Tests/PackageGraphTests/ModulesGraphTests.swift
  Tests/PackageLoadingTests/PackageBuilderTests.swift
  Tests/PackageLoadingTests/PkgConfigParserTests.swift
  Tests/PackageLoadingTests/PkgConfigTests.swift
  Tests/PackageModelTests/PackageModelTests.swift
  Tests/QueryEngineTests/QueryEngineTests.swift
  Tests/SourceControlTests/GitRepositoryTests.swift
  Tests/SourceControlTests/RepositoryManagerTests.swift
  Tests/SourceKitLSPAPITests/SourceKitLSPAPITests.swift
  Tests/WorkspaceTests/ManifestSourceGenerationTests.swift
  Tests/WorkspaceTests/RegistryPackageContainerTests.swift
  Tests/WorkspaceTests/SourceControlPackageContainerTests.swift
  Tests/WorkspaceTests/WorkspaceTests.swift
  Utilities/README.md
  Utilities/build-using-self
Labels: test suite
